// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <TColgp_HArray1OfXY.hxx>

#include <Standard_Type.hxx>

#include <Standard_RangeError.hxx>
#include <Standard_DimensionMismatch.hxx>
#include <Standard_OutOfRange.hxx>
#include <Standard_OutOfMemory.hxx>
#include <gp_XY.hxx>
#include <TColgp_Array1OfXY.hxx>

 


IMPLEMENT_STANDARD_TYPE(TColgp_HArray1OfXY)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(TColgp_HArray1OfXY)


IMPLEMENT_DOWNCAST(TColgp_HArray1OfXY,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(TColgp_HArray1OfXY)


#define ItemHArray1 gp_XY
#define ItemHArray1_hxx <gp_XY.hxx>
#define TheArray1 TColgp_Array1OfXY
#define TheArray1_hxx <TColgp_Array1OfXY.hxx>
#define TCollection_HArray1 TColgp_HArray1OfXY
#define TCollection_HArray1_hxx <TColgp_HArray1OfXY.hxx>
#define Handle_TCollection_HArray1 Handle_TColgp_HArray1OfXY
#define TCollection_HArray1_Type_() TColgp_HArray1OfXY_Type_()
#include <TCollection_HArray1.gxx>

