// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <TopTools_DataMapOfShapeListOfShape.hxx>

#ifndef _Standard_DomainError_HeaderFile
#include <Standard_DomainError.hxx>
#endif
#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _TopoDS_Shape_HeaderFile
#include <TopoDS_Shape.hxx>
#endif
#ifndef _TopTools_ListOfShape_HeaderFile
#include <TopTools_ListOfShape.hxx>
#endif
#ifndef _TopTools_ShapeMapHasher_HeaderFile
#include <TopTools_ShapeMapHasher.hxx>
#endif
#ifndef _TopTools_DataMapNodeOfDataMapOfShapeListOfShape_HeaderFile
#include <TopTools_DataMapNodeOfDataMapOfShapeListOfShape.hxx>
#endif
#ifndef _TopTools_DataMapIteratorOfDataMapOfShapeListOfShape_HeaderFile
#include <TopTools_DataMapIteratorOfDataMapOfShapeListOfShape.hxx>
#endif
 

#define TheKey TopoDS_Shape
#define TheKey_hxx <TopoDS_Shape.hxx>
#define TheItem TopTools_ListOfShape
#define TheItem_hxx <TopTools_ListOfShape.hxx>
#define Hasher TopTools_ShapeMapHasher
#define Hasher_hxx <TopTools_ShapeMapHasher.hxx>
#define TCollection_DataMapNode TopTools_DataMapNodeOfDataMapOfShapeListOfShape
#define TCollection_DataMapNode_hxx <TopTools_DataMapNodeOfDataMapOfShapeListOfShape.hxx>
#define TCollection_DataMapIterator TopTools_DataMapIteratorOfDataMapOfShapeListOfShape
#define TCollection_DataMapIterator_hxx <TopTools_DataMapIteratorOfDataMapOfShapeListOfShape.hxx>
#define Handle_TCollection_DataMapNode Handle_TopTools_DataMapNodeOfDataMapOfShapeListOfShape
#define TCollection_DataMapNode_Type_() TopTools_DataMapNodeOfDataMapOfShapeListOfShape_Type_()
#define TCollection_DataMap TopTools_DataMapOfShapeListOfShape
#define TCollection_DataMap_hxx <TopTools_DataMapOfShapeListOfShape.hxx>
#include <TCollection_DataMap.gxx>

