// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <StepToTopoDS_DataMapOfTRI.hxx>

#ifndef _Standard_DomainError_HeaderFile
#include <Standard_DomainError.hxx>
#endif
#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _StepShape_TopologicalRepresentationItem_HeaderFile
#include <StepShape_TopologicalRepresentationItem.hxx>
#endif
#ifndef _TopoDS_Shape_HeaderFile
#include <TopoDS_Shape.hxx>
#endif
#ifndef _TColStd_MapTransientHasher_HeaderFile
#include <TColStd_MapTransientHasher.hxx>
#endif
#ifndef _StepToTopoDS_DataMapNodeOfDataMapOfTRI_HeaderFile
#include <StepToTopoDS_DataMapNodeOfDataMapOfTRI.hxx>
#endif
#ifndef _StepToTopoDS_DataMapIteratorOfDataMapOfTRI_HeaderFile
#include <StepToTopoDS_DataMapIteratorOfDataMapOfTRI.hxx>
#endif
 

#define TheKey Handle_StepShape_TopologicalRepresentationItem
#define TheKey_hxx <StepShape_TopologicalRepresentationItem.hxx>
#define TheItem TopoDS_Shape
#define TheItem_hxx <TopoDS_Shape.hxx>
#define Hasher TColStd_MapTransientHasher
#define Hasher_hxx <TColStd_MapTransientHasher.hxx>
#define TCollection_DataMapNode StepToTopoDS_DataMapNodeOfDataMapOfTRI
#define TCollection_DataMapNode_hxx <StepToTopoDS_DataMapNodeOfDataMapOfTRI.hxx>
#define TCollection_DataMapIterator StepToTopoDS_DataMapIteratorOfDataMapOfTRI
#define TCollection_DataMapIterator_hxx <StepToTopoDS_DataMapIteratorOfDataMapOfTRI.hxx>
#define Handle_TCollection_DataMapNode Handle_StepToTopoDS_DataMapNodeOfDataMapOfTRI
#define TCollection_DataMapNode_Type_() StepToTopoDS_DataMapNodeOfDataMapOfTRI_Type_()
#define TCollection_DataMap StepToTopoDS_DataMapOfTRI
#define TCollection_DataMap_hxx <StepToTopoDS_DataMapOfTRI.hxx>
#include <TCollection_DataMap.gxx>

