SET(CTEST_PROJECT_NAME "OCE")
SET(CTEST_NIGHTLY_START_TIME "00:00:00 EST")

SET(CTEST_DROP_METHOD "http")
SET(CTEST_DROP_SITE "my.cdash.org")
SET(CTEST_DROP_LOCATION "/submit.php?project=OCE")
SET(CTEST_DROP_SITE_CDASH TRUE)
