#pragma once

#include "../TKernel/Precompiled.h"
#include "../TKMath/Precompiled.h"
#include "../TKGeomBase/Precompiled.h"
#include "../TKG2d/Precompiled.h"
#include "../TKG3d/Precompiled.h"
#include "../TKBrep/Precompiled.h"
#include "../TKGeomAlgo/Precompiled.h"

#include "Geom2dGcc.hxx"
#include "Geom2dHatch_Hatcher.hxx"
#include "GccEnt.hxx"
#include "GeomAPI.hxx"
#include "GeomAPI_IntCS.hxx"
#include "GeomAPI_IntSS.hxx"
#include "GeomFill.hxx"
#include "GeomInt_IntSS.hxx"
#include "GeomPlate_Surface.hxx"
#include "Hatch_Hatcher.hxx"
#include "Intf.hxx"
#include "IntSurf.hxx"
#include "Law.hxx"
#include "LocalAnalysis.hxx"
#include "NLPlate_NLPlate.hxx"
#include "Plate_Plate.hxx"
