// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XSDRAWSTLVRML_DataMapIteratorOfCoordsMap.hxx>

#include <Standard_NoSuchObject.hxx>
#include <TColStd_DataMapOfIntegerReal.hxx>
#include <TColStd_MapIntegerHasher.hxx>
#include <XSDRAWSTLVRML_CoordsMap.hxx>
#include <XSDRAWSTLVRML_DataMapNodeOfCoordsMap.hxx>
 

#define TheKey Standard_Integer
#define TheKey_hxx <Standard_Integer.hxx>
#define TheItem TColStd_DataMapOfIntegerReal
#define TheItem_hxx <TColStd_DataMapOfIntegerReal.hxx>
#define Hasher TColStd_MapIntegerHasher
#define Hasher_hxx <TColStd_MapIntegerHasher.hxx>
#define TCollection_DataMapNode XSDRAWSTLVRML_DataMapNodeOfCoordsMap
#define TCollection_DataMapNode_hxx <XSDRAWSTLVRML_DataMapNodeOfCoordsMap.hxx>
#define TCollection_DataMapIterator XSDRAWSTLVRML_DataMapIteratorOfCoordsMap
#define TCollection_DataMapIterator_hxx <XSDRAWSTLVRML_DataMapIteratorOfCoordsMap.hxx>
#define Handle_TCollection_DataMapNode Handle_XSDRAWSTLVRML_DataMapNodeOfCoordsMap
#define TCollection_DataMapNode_Type_() XSDRAWSTLVRML_DataMapNodeOfCoordsMap_Type_()
#define TCollection_DataMap XSDRAWSTLVRML_CoordsMap
#define TCollection_DataMap_hxx <XSDRAWSTLVRML_CoordsMap.hxx>
#include <TCollection_DataMapIterator.gxx>

