// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <BRepFill_ListOfOffsetWire.hxx>

#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _BRepFill_ListIteratorOfListOfOffsetWire_HeaderFile
#include <BRepFill_ListIteratorOfListOfOffsetWire.hxx>
#endif
#ifndef _BRepFill_OffsetWire_HeaderFile
#include <BRepFill_OffsetWire.hxx>
#endif
#ifndef _BRepFill_ListNodeOfListOfOffsetWire_HeaderFile
#include <BRepFill_ListNodeOfListOfOffsetWire.hxx>
#endif
 

#define Item BRepFill_OffsetWire
#define Item_hxx <BRepFill_OffsetWire.hxx>
#define TCollection_ListNode BRepFill_ListNodeOfListOfOffsetWire
#define TCollection_ListNode_hxx <BRepFill_ListNodeOfListOfOffsetWire.hxx>
#define TCollection_ListIterator BRepFill_ListIteratorOfListOfOffsetWire
#define TCollection_ListIterator_hxx <BRepFill_ListIteratorOfListOfOffsetWire.hxx>
#define Handle_TCollection_ListNode Handle_BRepFill_ListNodeOfListOfOffsetWire
#define TCollection_ListNode_Type_() BRepFill_ListNodeOfListOfOffsetWire_Type_()
#define TCollection_List BRepFill_ListOfOffsetWire
#define TCollection_List_hxx <BRepFill_ListOfOffsetWire.hxx>
#include <TCollection_List.gxx>

