// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <Geom_HSequenceOfSurface.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _Geom_Surface_HeaderFile
#include <Geom_Surface.hxx>
#endif
#ifndef _Geom_SequenceOfSurface_HeaderFile
#include <Geom_SequenceOfSurface.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(Geom_HSequenceOfSurface)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(Geom_HSequenceOfSurface)


IMPLEMENT_DOWNCAST(Geom_HSequenceOfSurface,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(Geom_HSequenceOfSurface)


#define Item Handle_Geom_Surface
#define Item_hxx <Geom_Surface.hxx>
#define TheSequence Geom_SequenceOfSurface
#define TheSequence_hxx <Geom_SequenceOfSurface.hxx>
#define TCollection_HSequence Geom_HSequenceOfSurface
#define TCollection_HSequence_hxx <Geom_HSequenceOfSurface.hxx>
#define Handle_TCollection_HSequence Handle_Geom_HSequenceOfSurface
#define TCollection_HSequence_Type_() Geom_HSequenceOfSurface_Type_()
#include <TCollection_HSequence.gxx>

