// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _TColStd_QueueOfInteger_HeaderFile
#define _TColStd_QueueOfInteger_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineAlloc_HeaderFile
#include <Standard_DefineAlloc.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

#ifndef _Standard_Address_HeaderFile
#include <Standard_Address.hxx>
#endif
#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
#ifndef _Handle_TColStd_QueueNodeOfQueueOfInteger_HeaderFile
#include <Handle_TColStd_QueueNodeOfQueueOfInteger.hxx>
#endif
#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
class Standard_NoSuchObject;
class TColStd_QueueNodeOfQueueOfInteger;



class TColStd_QueueOfInteger  {
public:

  DEFINE_STANDARD_ALLOC

  
  Standard_EXPORT   TColStd_QueueOfInteger();
  
  Standard_EXPORT    const TColStd_QueueOfInteger& Assign(const TColStd_QueueOfInteger& Other) ;
   const TColStd_QueueOfInteger& operator =(const TColStd_QueueOfInteger& Other) 
{
  return Assign(Other);
}
  
        Standard_Integer Length() const;
  
        Standard_Boolean IsEmpty() const;
  
  Standard_EXPORT    const Standard_Integer& Front() const;
  
  Standard_EXPORT     void Clear() ;
~TColStd_QueueOfInteger()
{
  Clear();
}
  
  Standard_EXPORT     void Push(const Standard_Integer& T) ;
  
  Standard_EXPORT     void Pop() ;
  
  Standard_EXPORT     Standard_Integer& ChangeFront() ;





protected:





private:

  
  Standard_EXPORT   TColStd_QueueOfInteger(const TColStd_QueueOfInteger& Other);


Standard_Address myFront;
Standard_Address myEnd;
Standard_Integer myLength;


};

#define Item Standard_Integer
#define Item_hxx <Standard_Integer.hxx>
#define TCollection_QueueNode TColStd_QueueNodeOfQueueOfInteger
#define TCollection_QueueNode_hxx <TColStd_QueueNodeOfQueueOfInteger.hxx>
#define Handle_TCollection_QueueNode Handle_TColStd_QueueNodeOfQueueOfInteger
#define TCollection_QueueNode_Type_() TColStd_QueueNodeOfQueueOfInteger_Type_()
#define TCollection_Queue TColStd_QueueOfInteger
#define TCollection_Queue_hxx <TColStd_QueueOfInteger.hxx>

#include <TCollection_Queue.lxx>

#undef Item
#undef Item_hxx
#undef TCollection_QueueNode
#undef TCollection_QueueNode_hxx
#undef Handle_TCollection_QueueNode
#undef TCollection_QueueNode_Type_
#undef TCollection_Queue
#undef TCollection_Queue_hxx


// other Inline functions and methods (like "C++: function call" methods)


#endif
