// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _Aspect_FillMethod_HeaderFile
#define _Aspect_FillMethod_HeaderFile

//! Defines type of degeneration model of the <br>
//!          graphic structure. <br>
enum Aspect_FillMethod {
Aspect_FM_NONE,
Aspect_FM_CENTERED,
Aspect_FM_TILED,
Aspect_FM_STRETCH
};

#ifndef _Standard_PrimitiveTypes_HeaderFile
#include <Standard_PrimitiveTypes.hxx>
#endif

#endif
