// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _Handle_ShapeExtend_MsgRegistrator_HeaderFile
#define _Handle_ShapeExtend_MsgRegistrator_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif

#ifndef _Handle_ShapeExtend_BasicMsgRegistrator_HeaderFile
#include <Handle_ShapeExtend_BasicMsgRegistrator.hxx>
#endif

class Standard_Transient;
class Handle(Standard_Type);
class Handle(ShapeExtend_BasicMsgRegistrator);
class ShapeExtend_MsgRegistrator;

DEFINE_STANDARD_HANDLE(ShapeExtend_MsgRegistrator,ShapeExtend_BasicMsgRegistrator)

#endif
