// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _Handle_RWHeaderSection_GeneralModule_HeaderFile
#define _Handle_RWHeaderSection_GeneralModule_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif

#ifndef _Handle_StepData_GeneralModule_HeaderFile
#include <Handle_StepData_GeneralModule.hxx>
#endif

class Standard_Transient;
class Handle(Standard_Type);
class Handle(StepData_GeneralModule);
class RWHeaderSection_GeneralModule;

DEFINE_STANDARD_HANDLE(RWHeaderSection_GeneralModule,StepData_GeneralModule)

#endif
