// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _Handle_Graphic2d_SequenceNodeOfSequenceOfBuffer_HeaderFile
#define _Handle_Graphic2d_SequenceNodeOfSequenceOfBuffer_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif

#ifndef _Handle_TCollection_SeqNode_HeaderFile
#include <Handle_TCollection_SeqNode.hxx>
#endif

class Standard_Transient;
class Handle(Standard_Type);
class Handle(TCollection_SeqNode);
class Graphic2d_SequenceNodeOfSequenceOfBuffer;

DEFINE_STANDARD_HANDLE(Graphic2d_SequenceNodeOfSequenceOfBuffer,TCollection_SeqNode)

#endif
