// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _PBRep_PolygonOnTriangulation_HeaderFile
#define _PBRep_PolygonOnTriangulation_HeaderFile

#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Handle_PBRep_PolygonOnTriangulation_HeaderFile
#include <Handle_PBRep_PolygonOnTriangulation.hxx>
#endif

#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
#ifndef _Handle_PPoly_PolygonOnTriangulation_HeaderFile
#include <Handle_PPoly_PolygonOnTriangulation.hxx>
#endif
#ifndef _Handle_PPoly_Triangulation_HeaderFile
#include <Handle_PPoly_Triangulation.hxx>
#endif
#ifndef _PBRep_CurveRepresentation_HeaderFile
#include <PBRep_CurveRepresentation.hxx>
#endif
class PPoly_PolygonOnTriangulation;
class PPoly_Triangulation;
class PTopLoc_Location;


class PBRep_PolygonOnTriangulation : public PBRep_CurveRepresentation {

public:

  
  Standard_EXPORT   PBRep_PolygonOnTriangulation(const Handle(PPoly_PolygonOnTriangulation)& P,const Handle(PPoly_Triangulation)& T,const PTopLoc_Location& L);
  //! returns True. <br>
  Standard_EXPORT   virtual  Standard_Boolean IsPolygonOnTriangulation() const;
  
  Standard_EXPORT     Handle_PPoly_PolygonOnTriangulation PolygonOnTriangulation() const;
  
  Standard_EXPORT     Handle_PPoly_Triangulation Triangulation() const;

  PBRep_PolygonOnTriangulation( )
{
  
}
PBRep_PolygonOnTriangulation(const Storage_stCONSTclCOM& a) : PBRep_CurveRepresentation(a)
{
  
}
    Handle(PPoly_PolygonOnTriangulation) _CSFDB_GetPBRep_PolygonOnTriangulationmyPolygon() const { return myPolygon; }
    void _CSFDB_SetPBRep_PolygonOnTriangulationmyPolygon(const Handle(PPoly_PolygonOnTriangulation)& p) { myPolygon = p; }
    Handle(PPoly_Triangulation) _CSFDB_GetPBRep_PolygonOnTriangulationmyTriangulation() const { return myTriangulation; }
    void _CSFDB_SetPBRep_PolygonOnTriangulationmyTriangulation(const Handle(PPoly_Triangulation)& p) { myTriangulation = p; }



  DEFINE_STANDARD_RTTI(PBRep_PolygonOnTriangulation)

protected:




private: 


Handle_PPoly_PolygonOnTriangulation myPolygon;
Handle_PPoly_Triangulation myTriangulation;


};





// other Inline functions and methods (like "C++: function call" methods)


#endif
