// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _StepBasic_DocumentProductEquivalence_HeaderFile
#define _StepBasic_DocumentProductEquivalence_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_StepBasic_DocumentProductEquivalence_HeaderFile
#include <Handle_StepBasic_DocumentProductEquivalence.hxx>
#endif

#ifndef _StepBasic_DocumentProductAssociation_HeaderFile
#include <StepBasic_DocumentProductAssociation.hxx>
#endif


//! Representation of STEP entity DocumentProductEquivalence <br>
class StepBasic_DocumentProductEquivalence : public StepBasic_DocumentProductAssociation {

public:

  //! Empty constructor <br>
  Standard_EXPORT   StepBasic_DocumentProductEquivalence();




  DEFINE_STANDARD_RTTI(StepBasic_DocumentProductEquivalence)

protected:




private: 




};





// other Inline functions and methods (like "C++: function call" methods)


#endif
