// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _V2d_ViewerPointer_HeaderFile
#define _V2d_ViewerPointer_HeaderFile

class V2d_Viewer;

typedef V2d_Viewer* V2d_ViewerPointer;

#endif
