// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <MeshVS_DataMapOfTwoColorsMapOfInteger.hxx>

#include <Standard_DomainError.hxx>
#include <Standard_NoSuchObject.hxx>
#include <TColStd_MapOfInteger.hxx>
#include <MeshVS_TwoColorsHasher.hxx>
#include <MeshVS_DataMapNodeOfDataMapOfTwoColorsMapOfInteger.hxx>
#include <MeshVS_DataMapIteratorOfDataMapOfTwoColorsMapOfInteger.hxx>
 

#define TheKey MeshVS_TwoColors
#define TheKey_hxx <MeshVS_TwoColors.hxx>
#define TheItem TColStd_MapOfInteger
#define TheItem_hxx <TColStd_MapOfInteger.hxx>
#define Hasher MeshVS_TwoColorsHasher
#define Hasher_hxx <MeshVS_TwoColorsHasher.hxx>
#define TCollection_DataMapNode MeshVS_DataMapNodeOfDataMapOfTwoColorsMapOfInteger
#define TCollection_DataMapNode_hxx <MeshVS_DataMapNodeOfDataMapOfTwoColorsMapOfInteger.hxx>
#define TCollection_DataMapIterator MeshVS_DataMapIteratorOfDataMapOfTwoColorsMapOfInteger
#define TCollection_DataMapIterator_hxx <MeshVS_DataMapIteratorOfDataMapOfTwoColorsMapOfInteger.hxx>
#define Handle_TCollection_DataMapNode Handle_MeshVS_DataMapNodeOfDataMapOfTwoColorsMapOfInteger
#define TCollection_DataMapNode_Type_() MeshVS_DataMapNodeOfDataMapOfTwoColorsMapOfInteger_Type_()
#define TCollection_DataMap MeshVS_DataMapOfTwoColorsMapOfInteger
#define TCollection_DataMap_hxx <MeshVS_DataMapOfTwoColorsMapOfInteger.hxx>
#include <TCollection_DataMap.gxx>

