// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <AdvApp2Var_SequenceNodeOfSequenceOfPatch.hxx>

#include <Standard_Type.hxx>

#include <AdvApp2Var_Patch.hxx>
#include <AdvApp2Var_SequenceOfPatch.hxx>

 


IMPLEMENT_STANDARD_TYPE(AdvApp2Var_SequenceNodeOfSequenceOfPatch)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_SeqNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(AdvApp2Var_SequenceNodeOfSequenceOfPatch)


IMPLEMENT_DOWNCAST(AdvApp2Var_SequenceNodeOfSequenceOfPatch,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(AdvApp2Var_SequenceNodeOfSequenceOfPatch)


#define SeqItem AdvApp2Var_Patch
#define SeqItem_hxx <AdvApp2Var_Patch.hxx>
#define TCollection_SequenceNode AdvApp2Var_SequenceNodeOfSequenceOfPatch
#define TCollection_SequenceNode_hxx <AdvApp2Var_SequenceNodeOfSequenceOfPatch.hxx>
#define Handle_TCollection_SequenceNode Handle_AdvApp2Var_SequenceNodeOfSequenceOfPatch
#define TCollection_SequenceNode_Type_() AdvApp2Var_SequenceNodeOfSequenceOfPatch_Type_()
#define TCollection_Sequence AdvApp2Var_SequenceOfPatch
#define TCollection_Sequence_hxx <AdvApp2Var_SequenceOfPatch.hxx>
#include <TCollection_SequenceNode.gxx>

