// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <BRepPrim_OneAxis.hxx>

#ifndef _Standard_DomainError_HeaderFile
#include <Standard_DomainError.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _TopoDS_Shell_HeaderFile
#include <TopoDS_Shell.hxx>
#endif
#ifndef _TopoDS_Face_HeaderFile
#include <TopoDS_Face.hxx>
#endif
#ifndef _TopoDS_Wire_HeaderFile
#include <TopoDS_Wire.hxx>
#endif
#ifndef _TopoDS_Edge_HeaderFile
#include <TopoDS_Edge.hxx>
#endif
#ifndef _TopoDS_Vertex_HeaderFile
#include <TopoDS_Vertex.hxx>
#endif
#ifndef _BRepPrim_Builder_HeaderFile
#include <BRepPrim_Builder.hxx>
#endif
#ifndef _gp_Ax2_HeaderFile
#include <gp_Ax2.hxx>
#endif
#ifndef _gp_Pnt2d_HeaderFile
#include <gp_Pnt2d.hxx>
#endif
 

#define TheShell TopoDS_Shell
#define TheShell_hxx <TopoDS_Shell.hxx>
#define TheFace TopoDS_Face
#define TheFace_hxx <TopoDS_Face.hxx>
#define TheWire TopoDS_Wire
#define TheWire_hxx <TopoDS_Wire.hxx>
#define TheEdge TopoDS_Edge
#define TheEdge_hxx <TopoDS_Edge.hxx>
#define TheVertex TopoDS_Vertex
#define TheVertex_hxx <TopoDS_Vertex.hxx>
#define TheBuilder BRepPrim_Builder
#define TheBuilder_hxx <BRepPrim_Builder.hxx>
#define Primitives_OneAxis BRepPrim_OneAxis
#define Primitives_OneAxis_hxx <BRepPrim_OneAxis.hxx>
#include <Primitives_OneAxis.gxx>

