// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <HLRBRep_Array1OfEData.hxx>

#include <Standard_RangeError.hxx>
#include <Standard_DimensionMismatch.hxx>
#include <Standard_OutOfRange.hxx>
#include <Standard_OutOfMemory.hxx>
#include <HLRBRep_EdgeData.hxx>
 

#define Array1Item HLRBRep_EdgeData
#define Array1Item_hxx <HLRBRep_EdgeData.hxx>
#define TCollection_Array1 HLRBRep_Array1OfEData
#define TCollection_Array1_hxx <HLRBRep_Array1OfEData.hxx>
#include <TCollection_Array1.gxx>

