// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <TColStd_DataMapNodeOfDataMapOfIntegerTransient.hxx>

#include <Standard_Type.hxx>

#include <Standard_Transient.hxx>
#include <TColStd_MapIntegerHasher.hxx>
#include <TColStd_DataMapOfIntegerTransient.hxx>
#include <TColStd_DataMapIteratorOfDataMapOfIntegerTransient.hxx>

 


IMPLEMENT_STANDARD_TYPE(TColStd_DataMapNodeOfDataMapOfIntegerTransient)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_MapNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(TColStd_DataMapNodeOfDataMapOfIntegerTransient)


IMPLEMENT_DOWNCAST(TColStd_DataMapNodeOfDataMapOfIntegerTransient,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(TColStd_DataMapNodeOfDataMapOfIntegerTransient)


#define TheKey Standard_Integer
#define TheKey_hxx <Standard_Integer.hxx>
#define TheItem Handle(Standard_Transient)
#define TheItem_hxx <Standard_Transient.hxx>
#define Hasher TColStd_MapIntegerHasher
#define Hasher_hxx <TColStd_MapIntegerHasher.hxx>
#define TCollection_DataMapNode TColStd_DataMapNodeOfDataMapOfIntegerTransient
#define TCollection_DataMapNode_hxx <TColStd_DataMapNodeOfDataMapOfIntegerTransient.hxx>
#define TCollection_DataMapIterator TColStd_DataMapIteratorOfDataMapOfIntegerTransient
#define TCollection_DataMapIterator_hxx <TColStd_DataMapIteratorOfDataMapOfIntegerTransient.hxx>
#define Handle_TCollection_DataMapNode Handle_TColStd_DataMapNodeOfDataMapOfIntegerTransient
#define TCollection_DataMapNode_Type_() TColStd_DataMapNodeOfDataMapOfIntegerTransient_Type_()
#define TCollection_DataMap TColStd_DataMapOfIntegerTransient
#define TCollection_DataMap_hxx <TColStd_DataMapOfIntegerTransient.hxx>
#include <TCollection_DataMapNode.gxx>

