// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <TopOpeBRepBuild_IndexedDataMapOfShapeVertexInfo.hxx>

#include <Standard_DomainError.hxx>
#include <Standard_OutOfRange.hxx>
#include <Standard_NoSuchObject.hxx>
#include <TopoDS_Shape.hxx>
#include <TopOpeBRepBuild_VertexInfo.hxx>
#include <TopTools_ShapeMapHasher.hxx>
#include <TopOpeBRepBuild_IndexedDataMapNodeOfIndexedDataMapOfShapeVertexInfo.hxx>
 

#define TheKey TopoDS_Shape
#define TheKey_hxx <TopoDS_Shape.hxx>
#define TheItem TopOpeBRepBuild_VertexInfo
#define TheItem_hxx <TopOpeBRepBuild_VertexInfo.hxx>
#define Hasher TopTools_ShapeMapHasher
#define Hasher_hxx <TopTools_ShapeMapHasher.hxx>
#define TCollection_IndexedDataMapNode TopOpeBRepBuild_IndexedDataMapNodeOfIndexedDataMapOfShapeVertexInfo
#define TCollection_IndexedDataMapNode_hxx <TopOpeBRepBuild_IndexedDataMapNodeOfIndexedDataMapOfShapeVertexInfo.hxx>
#define Handle_TCollection_IndexedDataMapNode Handle_TopOpeBRepBuild_IndexedDataMapNodeOfIndexedDataMapOfShapeVertexInfo
#define TCollection_IndexedDataMapNode_Type_() TopOpeBRepBuild_IndexedDataMapNodeOfIndexedDataMapOfShapeVertexInfo_Type_()
#define TCollection_IndexedDataMap TopOpeBRepBuild_IndexedDataMapOfShapeVertexInfo
#define TCollection_IndexedDataMap_hxx <TopOpeBRepBuild_IndexedDataMapOfShapeVertexInfo.hxx>
#include <TCollection_IndexedDataMap.gxx>

