// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <GeomFill_HArray1OfSectionLaw.hxx>

#include <Standard_Type.hxx>

#include <Standard_RangeError.hxx>
#include <Standard_DimensionMismatch.hxx>
#include <Standard_OutOfRange.hxx>
#include <Standard_OutOfMemory.hxx>
#include <GeomFill_SectionLaw.hxx>
#include <GeomFill_Array1OfSectionLaw.hxx>

 


IMPLEMENT_STANDARD_TYPE(GeomFill_HArray1OfSectionLaw)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(GeomFill_HArray1OfSectionLaw)


IMPLEMENT_DOWNCAST(GeomFill_HArray1OfSectionLaw,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(GeomFill_HArray1OfSectionLaw)


#define ItemHArray1 Handle(GeomFill_SectionLaw)
#define ItemHArray1_hxx <GeomFill_SectionLaw.hxx>
#define TheArray1 GeomFill_Array1OfSectionLaw
#define TheArray1_hxx <GeomFill_Array1OfSectionLaw.hxx>
#define TCollection_HArray1 GeomFill_HArray1OfSectionLaw
#define TCollection_HArray1_hxx <GeomFill_HArray1OfSectionLaw.hxx>
#define Handle_TCollection_HArray1 Handle_GeomFill_HArray1OfSectionLaw
#define TCollection_HArray1_Type_() GeomFill_HArray1OfSectionLaw_Type_()
#include <TCollection_HArray1.gxx>

