// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <BOPTools_ListNodeOfListOfCommonBlock.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _BOPTools_CommonBlock_HeaderFile
#include <BOPTools_CommonBlock.hxx>
#endif
#ifndef _BOPTools_ListOfCommonBlock_HeaderFile
#include <BOPTools_ListOfCommonBlock.hxx>
#endif
#ifndef _BOPTools_ListIteratorOfListOfCommonBlock_HeaderFile
#include <BOPTools_ListIteratorOfListOfCommonBlock.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(BOPTools_ListNodeOfListOfCommonBlock)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_MapNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(BOPTools_ListNodeOfListOfCommonBlock)


IMPLEMENT_DOWNCAST(BOPTools_ListNodeOfListOfCommonBlock,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(BOPTools_ListNodeOfListOfCommonBlock)


#define Item BOPTools_CommonBlock
#define Item_hxx <BOPTools_CommonBlock.hxx>
#define TCollection_ListNode BOPTools_ListNodeOfListOfCommonBlock
#define TCollection_ListNode_hxx <BOPTools_ListNodeOfListOfCommonBlock.hxx>
#define TCollection_ListIterator BOPTools_ListIteratorOfListOfCommonBlock
#define TCollection_ListIterator_hxx <BOPTools_ListIteratorOfListOfCommonBlock.hxx>
#define Handle_TCollection_ListNode Handle_BOPTools_ListNodeOfListOfCommonBlock
#define TCollection_ListNode_Type_() BOPTools_ListNodeOfListOfCommonBlock_Type_()
#define TCollection_List BOPTools_ListOfCommonBlock
#define TCollection_List_hxx <BOPTools_ListOfCommonBlock.hxx>
#include <TCollection_ListNode.gxx>

