// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <StepRepr_SequenceOfMaterialPropertyRepresentation.hxx>

#include <Standard_NoSuchObject.hxx>
#include <Standard_OutOfRange.hxx>
#include <StepRepr_MaterialPropertyRepresentation.hxx>
#include <StepRepr_SequenceNodeOfSequenceOfMaterialPropertyRepresentation.hxx>
 

#define SeqItem Handle(StepRepr_MaterialPropertyRepresentation)
#define SeqItem_hxx <StepRepr_MaterialPropertyRepresentation.hxx>
#define TCollection_SequenceNode StepRepr_SequenceNodeOfSequenceOfMaterialPropertyRepresentation
#define TCollection_SequenceNode_hxx <StepRepr_SequenceNodeOfSequenceOfMaterialPropertyRepresentation.hxx>
#define Handle_TCollection_SequenceNode Handle_StepRepr_SequenceNodeOfSequenceOfMaterialPropertyRepresentation
#define TCollection_SequenceNode_Type_() StepRepr_SequenceNodeOfSequenceOfMaterialPropertyRepresentation_Type_()
#define TCollection_Sequence StepRepr_SequenceOfMaterialPropertyRepresentation
#define TCollection_Sequence_hxx <StepRepr_SequenceOfMaterialPropertyRepresentation.hxx>
#include <TCollection_Sequence.gxx>

