#ifndef _StdSchema_HeaderFile
#include <StdSchema.hxx>
#endif
#ifndef _Storage_StreamUnknownTypeError_HeaderFile
#include <Storage_StreamUnknownTypeError.hxx>
#endif
#ifndef _TColStd_SequenceOfAsciiString_HeaderFile
#include <TColStd_SequenceOfAsciiString.hxx>
#endif
#ifndef _StdSchema_PDataXtd_Position_HeaderFile
#include <StdSchema_PDataXtd_Position.hxx>
#endif
#ifndef _StdSchema_PDataXtd_Point_HeaderFile
#include <StdSchema_PDataXtd_Point.hxx>
#endif
#ifndef _StdSchema_PDataXtd_Axis_HeaderFile
#include <StdSchema_PDataXtd_Axis.hxx>
#endif
#ifndef _StdSchema_PDataXtd_Plane_HeaderFile
#include <StdSchema_PDataXtd_Plane.hxx>
#endif
#ifndef _StdSchema_PDataXtd_Geometry_HeaderFile
#include <StdSchema_PDataXtd_Geometry.hxx>
#endif
#ifndef _StdSchema_PDataXtd_Constraint_HeaderFile
#include <StdSchema_PDataXtd_Constraint.hxx>
#endif
#ifndef _StdSchema_PDataXtd_Placement_HeaderFile
#include <StdSchema_PDataXtd_Placement.hxx>
#endif
#ifndef _StdSchema_PDataXtd_PatternStd_HeaderFile
#include <StdSchema_PDataXtd_PatternStd.hxx>
#endif
#ifndef _StdSchema_PDataXtd_Shape_HeaderFile
#include <StdSchema_PDataXtd_Shape.hxx>
#endif
#ifndef _StdSchema_PNaming_Name_HeaderFile
#include <StdSchema_PNaming_Name.hxx>
#endif
#ifndef _StdSchema_PNaming_Name_1_HeaderFile
#include <StdSchema_PNaming_Name_1.hxx>
#endif
#ifndef _StdSchema_PNaming_Name_2_HeaderFile
#include <StdSchema_PNaming_Name_2.hxx>
#endif
#ifndef _StdSchema_PNaming_NamedShape_HeaderFile
#include <StdSchema_PNaming_NamedShape.hxx>
#endif
#ifndef _StdSchema_PNaming_Naming_HeaderFile
#include <StdSchema_PNaming_Naming.hxx>
#endif
#ifndef _StdSchema_PNaming_Naming_1_HeaderFile
#include <StdSchema_PNaming_Naming_1.hxx>
#endif
#ifndef _StdSchema_PNaming_Naming_2_HeaderFile
#include <StdSchema_PNaming_Naming_2.hxx>
#endif
#ifndef _StdSchema_PNaming_HArray1OfNamedShape_HeaderFile
#include <StdSchema_PNaming_HArray1OfNamedShape.hxx>
#endif
#ifndef _StdSchema_PPrsStd_AISPresentation_HeaderFile
#include <StdSchema_PPrsStd_AISPresentation.hxx>
#endif
#ifndef _StdSchema_PPrsStd_AISPresentation_1_HeaderFile
#include <StdSchema_PPrsStd_AISPresentation_1.hxx>
#endif
#ifndef _StdSchema_PDF_Attribute_HeaderFile
#include <StdSchema_PDF_Attribute.hxx>
#endif
#ifndef _StdSchema_Standard_Persistent_HeaderFile
#include <StdSchema_Standard_Persistent.hxx>
#endif
#ifndef _StdSchema_PDataStd_Real_HeaderFile
#include <StdSchema_PDataStd_Real.hxx>
#endif
#ifndef _StdSchema_PDF_HAttributeArray1_HeaderFile
#include <StdSchema_PDF_HAttributeArray1.hxx>
#endif
#ifndef _StdSchema_PDataStd_Integer_HeaderFile
#include <StdSchema_PDataStd_Integer.hxx>
#endif
#ifndef _StdSchema_PCollection_HAsciiString_HeaderFile
#include <StdSchema_PCollection_HAsciiString.hxx>
#endif
#ifndef _StdSchema_PTopoDS_HArray1OfShape1_HeaderFile
#include <StdSchema_PTopoDS_HArray1OfShape1.hxx>
#endif
#ifndef _StdSchema_PColStd_HArray1OfInteger_HeaderFile
#include <StdSchema_PColStd_HArray1OfInteger.hxx>
#endif
#ifndef _StdSchema_PCollection_HExtendedString_HeaderFile
#include <StdSchema_PCollection_HExtendedString.hxx>
#endif
#ifndef _StdSchema_PTopoDS_TShape1_HeaderFile
#include <StdSchema_PTopoDS_TShape1.hxx>
#endif
#ifndef _StdSchema_PTopLoc_Datum3D_HeaderFile
#include <StdSchema_PTopLoc_Datum3D.hxx>
#endif
#ifndef _StdSchema_PTopLoc_ItemLocation_HeaderFile
#include <StdSchema_PTopLoc_ItemLocation.hxx>
#endif

// avoid warnings on 'extern "C"' functions returning C++ classes
#ifdef _MSC_VER
#pragma warning(disable:4190)
#endif

IMPLEMENT_STANDARD_HANDLE(StdSchema,Storage_Schema)
IMPLEMENT_STANDARD_RTTIEXT(StdSchema,Storage_Schema)

Storage_BEGIN_ADD_TYPES(StdSchema)
Storage_ADD_TYPES(StdSchema,PDataXtd_Position,StdSchema_PDataXtd_Position)
Storage_ADD_TYPES(StdSchema,PDataXtd_Point,StdSchema_PDataXtd_Point)
Storage_ADD_TYPES(StdSchema,PDataXtd_Axis,StdSchema_PDataXtd_Axis)
Storage_ADD_TYPES(StdSchema,PDataXtd_Plane,StdSchema_PDataXtd_Plane)
Storage_ADD_TYPES(StdSchema,PDataXtd_Geometry,StdSchema_PDataXtd_Geometry)
Storage_ADD_TYPES(StdSchema,PDataXtd_Constraint,StdSchema_PDataXtd_Constraint)
Storage_ADD_TYPES(StdSchema,PDataXtd_Placement,StdSchema_PDataXtd_Placement)
Storage_ADD_TYPES(StdSchema,PDataXtd_PatternStd,StdSchema_PDataXtd_PatternStd)
Storage_ADD_TYPES(StdSchema,PDataXtd_Shape,StdSchema_PDataXtd_Shape)
Storage_ADD_TYPES(StdSchema,PNaming_Name,StdSchema_PNaming_Name)
Storage_ADD_TYPES(StdSchema,PNaming_Name_1,StdSchema_PNaming_Name_1)
Storage_ADD_TYPES(StdSchema,PNaming_Name_2,StdSchema_PNaming_Name_2)
Storage_ADD_TYPES(StdSchema,PNaming_NamedShape,StdSchema_PNaming_NamedShape)
Storage_ADD_TYPES(StdSchema,PNaming_Naming,StdSchema_PNaming_Naming)
Storage_ADD_TYPES(StdSchema,PNaming_Naming_1,StdSchema_PNaming_Naming_1)
Storage_ADD_TYPES(StdSchema,PNaming_Naming_2,StdSchema_PNaming_Naming_2)
Storage_ADD_TYPES(StdSchema,PNaming_HArray1OfNamedShape,StdSchema_PNaming_HArray1OfNamedShape)
Storage_ADD_TYPES(StdSchema,PPrsStd_AISPresentation,StdSchema_PPrsStd_AISPresentation)
Storage_ADD_TYPES(StdSchema,PPrsStd_AISPresentation_1,StdSchema_PPrsStd_AISPresentation_1)
Storage_ADD_TYPES(StdSchema,PDF_Attribute,StdSchema_PDF_Attribute)
Storage_ADD_TYPES(StdSchema,Standard_Persistent,StdSchema_Standard_Persistent)
Storage_ADD_TYPES(StdSchema,PDataStd_Real,StdSchema_PDataStd_Real)
Storage_ADD_TYPES(StdSchema,PDF_HAttributeArray1,StdSchema_PDF_HAttributeArray1)
Storage_ADD_TYPES(StdSchema,PDataStd_Integer,StdSchema_PDataStd_Integer)
Storage_ADD_TYPES(StdSchema,PCollection_HAsciiString,StdSchema_PCollection_HAsciiString)
Storage_ADD_TYPES(StdSchema,PTopoDS_HArray1OfShape1,StdSchema_PTopoDS_HArray1OfShape1)
Storage_ADD_TYPES(StdSchema,PColStd_HArray1OfInteger,StdSchema_PColStd_HArray1OfInteger)
Storage_ADD_TYPES(StdSchema,PCollection_HExtendedString,StdSchema_PCollection_HExtendedString)
Storage_ADD_TYPES(StdSchema,PTopoDS_TShape1,StdSchema_PTopoDS_TShape1)
Storage_ADD_TYPES(StdSchema,PTopLoc_Datum3D,StdSchema_PTopLoc_Datum3D)
Storage_ADD_TYPES(StdSchema,PTopLoc_ItemLocation,StdSchema_PTopLoc_ItemLocation)
Storage_END_ADD_TYPES(StdSchema)

Storage_BEGIN_READ_SELECTION(StdSchema)
Storage_READ_SELECTION(StdSchema,PDataXtd_Position,StdSchema_PDataXtd_Position)
Storage_READ_SELECTION(StdSchema,PDataXtd_Point,StdSchema_PDataXtd_Point)
Storage_READ_SELECTION(StdSchema,PDataXtd_Axis,StdSchema_PDataXtd_Axis)
Storage_READ_SELECTION(StdSchema,PDataXtd_Plane,StdSchema_PDataXtd_Plane)
Storage_READ_SELECTION(StdSchema,PDataXtd_Geometry,StdSchema_PDataXtd_Geometry)
Storage_READ_SELECTION(StdSchema,PDataXtd_Constraint,StdSchema_PDataXtd_Constraint)
Storage_READ_SELECTION(StdSchema,PDataXtd_Placement,StdSchema_PDataXtd_Placement)
Storage_READ_SELECTION(StdSchema,PDataXtd_PatternStd,StdSchema_PDataXtd_PatternStd)
Storage_READ_SELECTION(StdSchema,PDataXtd_Shape,StdSchema_PDataXtd_Shape)
Storage_READ_SELECTION(StdSchema,PNaming_Name,StdSchema_PNaming_Name)
Storage_READ_SELECTION(StdSchema,PNaming_Name_1,StdSchema_PNaming_Name_1)
Storage_READ_SELECTION(StdSchema,PNaming_Name_2,StdSchema_PNaming_Name_2)
Storage_READ_SELECTION(StdSchema,PNaming_NamedShape,StdSchema_PNaming_NamedShape)
Storage_READ_SELECTION(StdSchema,PNaming_Naming,StdSchema_PNaming_Naming)
Storage_READ_SELECTION(StdSchema,PNaming_Naming_1,StdSchema_PNaming_Naming_1)
Storage_READ_SELECTION(StdSchema,PNaming_Naming_2,StdSchema_PNaming_Naming_2)
Storage_READ_SELECTION(StdSchema,PNaming_HArray1OfNamedShape,StdSchema_PNaming_HArray1OfNamedShape)
Storage_READ_SELECTION(StdSchema,PPrsStd_AISPresentation,StdSchema_PPrsStd_AISPresentation)
Storage_READ_SELECTION(StdSchema,PPrsStd_AISPresentation_1,StdSchema_PPrsStd_AISPresentation_1)
Storage_READ_SELECTION(StdSchema,PDataStd_Real,StdSchema_PDataStd_Real)
Storage_READ_SELECTION(StdSchema,PDF_HAttributeArray1,StdSchema_PDF_HAttributeArray1)
Storage_READ_SELECTION(StdSchema,PDataStd_Integer,StdSchema_PDataStd_Integer)
Storage_READ_SELECTION(StdSchema,PCollection_HAsciiString,StdSchema_PCollection_HAsciiString)
Storage_READ_SELECTION(StdSchema,PTopoDS_HArray1OfShape1,StdSchema_PTopoDS_HArray1OfShape1)
Storage_READ_SELECTION(StdSchema,PColStd_HArray1OfInteger,StdSchema_PColStd_HArray1OfInteger)
Storage_READ_SELECTION(StdSchema,PCollection_HExtendedString,StdSchema_PCollection_HExtendedString)
Storage_READ_SELECTION(StdSchema,PTopLoc_Datum3D,StdSchema_PTopLoc_Datum3D)
Storage_READ_SELECTION(StdSchema,PTopLoc_ItemLocation,StdSchema_PTopLoc_ItemLocation)
Storage_END_READ_SELECTION(StdSchema)

Storage_BEGIN_SCHEMA_TYPES(StdSchema)
Storage_SCHEMA_TYPES(PDataXtd_Position)
Storage_SCHEMA_TYPES(PDataXtd_Point)
Storage_SCHEMA_TYPES(PDataXtd_Axis)
Storage_SCHEMA_TYPES(PDataXtd_Plane)
Storage_SCHEMA_TYPES(PDataXtd_Geometry)
Storage_SCHEMA_TYPES(PDataXtd_Constraint)
Storage_SCHEMA_TYPES(PDataXtd_Placement)
Storage_SCHEMA_TYPES(PDataXtd_PatternStd)
Storage_SCHEMA_TYPES(PDataXtd_Shape)
Storage_SCHEMA_TYPES(PNaming_Name)
Storage_SCHEMA_TYPES(PNaming_Name_1)
Storage_SCHEMA_TYPES(PNaming_Name_2)
Storage_SCHEMA_TYPES(PNaming_NamedShape)
Storage_SCHEMA_TYPES(PNaming_Naming)
Storage_SCHEMA_TYPES(PNaming_Naming_1)
Storage_SCHEMA_TYPES(PNaming_Naming_2)
Storage_SCHEMA_TYPES(PNaming_HArray1OfNamedShape)
Storage_SCHEMA_TYPES(PPrsStd_AISPresentation)
Storage_SCHEMA_TYPES(PPrsStd_AISPresentation_1)
Storage_SCHEMA_TYPES(PDF_Attribute)
Storage_SCHEMA_TYPES(Standard_Persistent)
Storage_SCHEMA_TYPES(PDataStd_Real)
Storage_SCHEMA_TYPES(PDF_HAttributeArray1)
Storage_SCHEMA_TYPES(PDataStd_Integer)
Storage_SCHEMA_TYPES(PCollection_HAsciiString)
Storage_SCHEMA_TYPES(PTopoDS_HArray1OfShape1)
Storage_SCHEMA_TYPES(PColStd_HArray1OfInteger)
Storage_SCHEMA_TYPES(PCollection_HExtendedString)
Storage_SCHEMA_TYPES(PTopoDS_TShape1)
Storage_SCHEMA_TYPES(PTopLoc_Datum3D)
Storage_SCHEMA_TYPES(PTopLoc_ItemLocation)
Storage_END_SCHEMA_TYPES(StdSchema)
