// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _BRepMesh_DataMapIteratorOfDataMapOfShapePairOfPolygon_HeaderFile
#define _BRepMesh_DataMapIteratorOfDataMapOfShapePairOfPolygon_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineAlloc_HeaderFile
#include <Standard_DefineAlloc.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

#ifndef _TCollection_BasicMapIterator_HeaderFile
#include <TCollection_BasicMapIterator.hxx>
#endif
#ifndef _Handle_BRepMesh_DataMapNodeOfDataMapOfShapePairOfPolygon_HeaderFile
#include <Handle_BRepMesh_DataMapNodeOfDataMapOfShapePairOfPolygon.hxx>
#endif
class Standard_NoSuchObject;
class TopoDS_Shape;
class BRepMesh_PairOfPolygon;
class TopTools_ShapeMapHasher;
class BRepMesh_DataMapOfShapePairOfPolygon;
class BRepMesh_DataMapNodeOfDataMapOfShapePairOfPolygon;



class BRepMesh_DataMapIteratorOfDataMapOfShapePairOfPolygon  : public TCollection_BasicMapIterator {
public:

  DEFINE_STANDARD_ALLOC

  
  Standard_EXPORT   BRepMesh_DataMapIteratorOfDataMapOfShapePairOfPolygon();
  
  Standard_EXPORT   BRepMesh_DataMapIteratorOfDataMapOfShapePairOfPolygon(const BRepMesh_DataMapOfShapePairOfPolygon& aMap);
  
  Standard_EXPORT     void Initialize(const BRepMesh_DataMapOfShapePairOfPolygon& aMap) ;
  
  Standard_EXPORT    const TopoDS_Shape& Key() const;
  
  Standard_EXPORT    const BRepMesh_PairOfPolygon& Value() const;





protected:





private:





};





// other Inline functions and methods (like "C++: function call" methods)


#endif
