// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <ChFiDS_Regularities.hxx>

#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _ChFiDS_ListIteratorOfRegularities_HeaderFile
#include <ChFiDS_ListIteratorOfRegularities.hxx>
#endif
#ifndef _ChFiDS_Regul_HeaderFile
#include <ChFiDS_Regul.hxx>
#endif
#ifndef _ChFiDS_ListNodeOfRegularities_HeaderFile
#include <ChFiDS_ListNodeOfRegularities.hxx>
#endif
 

#define Item ChFiDS_Regul
#define Item_hxx <ChFiDS_Regul.hxx>
#define TCollection_ListNode ChFiDS_ListNodeOfRegularities
#define TCollection_ListNode_hxx <ChFiDS_ListNodeOfRegularities.hxx>
#define TCollection_ListIterator ChFiDS_ListIteratorOfRegularities
#define TCollection_ListIterator_hxx <ChFiDS_ListIteratorOfRegularities.hxx>
#define Handle_TCollection_ListNode Handle_ChFiDS_ListNodeOfRegularities
#define TCollection_ListNode_Type_() ChFiDS_ListNodeOfRegularities_Type_()
#define TCollection_List ChFiDS_Regularities
#define TCollection_List_hxx <ChFiDS_Regularities.hxx>
#include <TCollection_List.gxx>

