// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <SelectMgr_DataMapNodeOfDataMapOfIntegerSensitive.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _SelectBasics_SensitiveEntity_HeaderFile
#include <SelectBasics_SensitiveEntity.hxx>
#endif
#ifndef _TColStd_MapIntegerHasher_HeaderFile
#include <TColStd_MapIntegerHasher.hxx>
#endif
#ifndef _SelectMgr_DataMapOfIntegerSensitive_HeaderFile
#include <SelectMgr_DataMapOfIntegerSensitive.hxx>
#endif
#ifndef _SelectMgr_DataMapIteratorOfDataMapOfIntegerSensitive_HeaderFile
#include <SelectMgr_DataMapIteratorOfDataMapOfIntegerSensitive.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(SelectMgr_DataMapNodeOfDataMapOfIntegerSensitive)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_MapNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(SelectMgr_DataMapNodeOfDataMapOfIntegerSensitive)


IMPLEMENT_DOWNCAST(SelectMgr_DataMapNodeOfDataMapOfIntegerSensitive,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(SelectMgr_DataMapNodeOfDataMapOfIntegerSensitive)


#define TheKey Standard_Integer
#define TheKey_hxx <Standard_Integer.hxx>
#define TheItem Handle_SelectBasics_SensitiveEntity
#define TheItem_hxx <SelectBasics_SensitiveEntity.hxx>
#define Hasher TColStd_MapIntegerHasher
#define Hasher_hxx <TColStd_MapIntegerHasher.hxx>
#define TCollection_DataMapNode SelectMgr_DataMapNodeOfDataMapOfIntegerSensitive
#define TCollection_DataMapNode_hxx <SelectMgr_DataMapNodeOfDataMapOfIntegerSensitive.hxx>
#define TCollection_DataMapIterator SelectMgr_DataMapIteratorOfDataMapOfIntegerSensitive
#define TCollection_DataMapIterator_hxx <SelectMgr_DataMapIteratorOfDataMapOfIntegerSensitive.hxx>
#define Handle_TCollection_DataMapNode Handle_SelectMgr_DataMapNodeOfDataMapOfIntegerSensitive
#define TCollection_DataMapNode_Type_() SelectMgr_DataMapNodeOfDataMapOfIntegerSensitive_Type_()
#define TCollection_DataMap SelectMgr_DataMapOfIntegerSensitive
#define TCollection_DataMap_hxx <SelectMgr_DataMapOfIntegerSensitive.hxx>
#include <TCollection_DataMapNode.gxx>

