// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _Contap_SequenceNodeOfTheSequenceOfPointOfContour_HeaderFile
#define _Contap_SequenceNodeOfTheSequenceOfPointOfContour_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_Contap_SequenceNodeOfTheSequenceOfPointOfContour_HeaderFile
#include <Handle_Contap_SequenceNodeOfTheSequenceOfPointOfContour.hxx>
#endif

#ifndef _Contap_ThePointOfContour_HeaderFile
#include <Contap_ThePointOfContour.hxx>
#endif
#ifndef _TCollection_SeqNode_HeaderFile
#include <TCollection_SeqNode.hxx>
#endif
#ifndef _TCollection_SeqNodePtr_HeaderFile
#include <TCollection_SeqNodePtr.hxx>
#endif
class Contap_ThePointOfContour;
class Contap_TheSequenceOfPointOfContour;



class Contap_SequenceNodeOfTheSequenceOfPointOfContour : public TCollection_SeqNode {

public:

  
      Contap_SequenceNodeOfTheSequenceOfPointOfContour(const Contap_ThePointOfContour& I,const TCollection_SeqNodePtr& n,const TCollection_SeqNodePtr& p);
  
        Contap_ThePointOfContour& Value() const;




  DEFINE_STANDARD_RTTI(Contap_SequenceNodeOfTheSequenceOfPointOfContour)

protected:




private: 


Contap_ThePointOfContour myValue;


};

#define SeqItem Contap_ThePointOfContour
#define SeqItem_hxx <Contap_ThePointOfContour.hxx>
#define TCollection_SequenceNode Contap_SequenceNodeOfTheSequenceOfPointOfContour
#define TCollection_SequenceNode_hxx <Contap_SequenceNodeOfTheSequenceOfPointOfContour.hxx>
#define Handle_TCollection_SequenceNode Handle_Contap_SequenceNodeOfTheSequenceOfPointOfContour
#define TCollection_SequenceNode_Type_() Contap_SequenceNodeOfTheSequenceOfPointOfContour_Type_()
#define TCollection_Sequence Contap_TheSequenceOfPointOfContour
#define TCollection_Sequence_hxx <Contap_TheSequenceOfPointOfContour.hxx>

#include <TCollection_SequenceNode.lxx>

#undef SeqItem
#undef SeqItem_hxx
#undef TCollection_SequenceNode
#undef TCollection_SequenceNode_hxx
#undef Handle_TCollection_SequenceNode
#undef TCollection_SequenceNode_Type_
#undef TCollection_Sequence
#undef TCollection_Sequence_hxx


// other Inline functions and methods (like "C++: function call" methods)


#endif
