// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _GCPnts_AbscissaType_HeaderFile
#define _GCPnts_AbscissaType_HeaderFile

#include <Standard_PrimitiveTypes.hxx>


enum GCPnts_AbscissaType
{
GCPnts_LengthParametrized,
GCPnts_Parametrized,
GCPnts_AbsComposite
};

#endif // _GCPnts_AbscissaType_HeaderFile
