// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _Handle_StepFEA_ParametricSurface3dElementCoordinateSystem_HeaderFile
#define _Handle_StepFEA_ParametricSurface3dElementCoordinateSystem_HeaderFile

#include <Standard.hxx>
#include <Standard_DefineHandle.hxx>
#include <Handle_StepFEA_FeaRepresentationItem.hxx>

class Standard_Transient;
class Handle(Standard_Type);
class Handle(StepFEA_FeaRepresentationItem);
class StepFEA_ParametricSurface3dElementCoordinateSystem;

DEFINE_STANDARD_HANDLE(StepFEA_ParametricSurface3dElementCoordinateSystem, StepFEA_FeaRepresentationItem)

#endif // _Handle_StepFEA_ParametricSurface3dElementCoordinateSystem_HeaderFile
