// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _Handle_Aspect_WindowError_HeaderFile
#define _Handle_Aspect_WindowError_HeaderFile

#include <Standard.hxx>
#include <Standard_DefineHandle.hxx>
#include <Handle_Standard_OutOfRange.hxx>

class Standard_Transient;
class Handle(Standard_Type);
class Handle(Standard_OutOfRange);
class Aspect_WindowError;

DEFINE_STANDARD_HANDLE(Aspect_WindowError, Standard_OutOfRange)

#endif // _Handle_Aspect_WindowError_HeaderFile
