// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _Handle_IGESSelect_SelectSingleViewFrom_HeaderFile
#define _Handle_IGESSelect_SelectSingleViewFrom_HeaderFile

#include <Standard.hxx>
#include <Standard_DefineHandle.hxx>
#include <Handle_IFSelect_SelectDeduct.hxx>

class Standard_Transient;
class Handle(Standard_Type);
class Handle(IFSelect_SelectDeduct);
class IGESSelect_SelectSingleViewFrom;

DEFINE_STANDARD_HANDLE(IGESSelect_SelectSingleViewFrom, IFSelect_SelectDeduct)

#endif // _Handle_IGESSelect_SelectSingleViewFrom_HeaderFile
