// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _Handle_HeaderSection_FileDescription_HeaderFile
#define _Handle_HeaderSection_FileDescription_HeaderFile

#include <Standard.hxx>
#include <Standard_DefineHandle.hxx>
#include <Handle_MMgt_TShared.hxx>

class Standard_Transient;
class Handle(Standard_Type);
class Handle(MMgt_TShared);
class HeaderSection_FileDescription;

DEFINE_STANDARD_HANDLE(HeaderSection_FileDescription, MMgt_TShared)

#endif // _Handle_HeaderSection_FileDescription_HeaderFile
