// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _Handle_StepBasic_DocumentFile_HeaderFile
#define _Handle_StepBasic_DocumentFile_HeaderFile

#include <Standard.hxx>
#include <Standard_DefineHandle.hxx>
#include <Handle_StepBasic_Document.hxx>

class Standard_Transient;
class Handle(Standard_Type);
class Handle(StepBasic_Document);
class StepBasic_DocumentFile;

DEFINE_STANDARD_HANDLE(StepBasic_DocumentFile, StepBasic_Document)

#endif // _Handle_StepBasic_DocumentFile_HeaderFile
