// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _Handle_NLPlate_HPG3Constraint_HeaderFile
#define _Handle_NLPlate_HPG3Constraint_HeaderFile

#include <Standard.hxx>
#include <Standard_DefineHandle.hxx>
#include <Handle_NLPlate_HPG2Constraint.hxx>

class Standard_Transient;
class Handle(Standard_Type);
class Handle(NLPlate_HPG2Constraint);
class NLPlate_HPG3Constraint;

DEFINE_STANDARD_HANDLE(NLPlate_HPG3Constraint, NLPlate_HPG2Constraint)

#endif // _Handle_NLPlate_HPG3Constraint_HeaderFile
