// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _Handle_StepDimTol_DatumTarget_HeaderFile
#define _Handle_StepDimTol_DatumTarget_HeaderFile

#include <Standard.hxx>
#include <Standard_DefineHandle.hxx>
#include <Handle_StepRepr_ShapeAspect.hxx>

class Standard_Transient;
class Handle(Standard_Type);
class Handle(StepRepr_ShapeAspect);
class StepDimTol_DatumTarget;

DEFINE_STANDARD_HANDLE(StepDimTol_DatumTarget, StepRepr_ShapeAspect)

#endif // _Handle_StepDimTol_DatumTarget_HeaderFile
