// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _Handle_HLRTopoBRep_ListNodeOfListOfVData_HeaderFile
#define _Handle_HLRTopoBRep_ListNodeOfListOfVData_HeaderFile

#include <Standard.hxx>
#include <Standard_DefineHandle.hxx>
#include <Handle_TCollection_MapNode.hxx>

class Standard_Transient;
class Handle(Standard_Type);
class Handle(TCollection_MapNode);
class HLRTopoBRep_ListNodeOfListOfVData;

DEFINE_STANDARD_HANDLE(HLRTopoBRep_ListNodeOfListOfVData, TCollection_MapNode)

#endif // _Handle_HLRTopoBRep_ListNodeOfListOfVData_HeaderFile
