// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _HLRBRep_ListIteratorOfListOfBPnt2D_HeaderFile
#define _HLRBRep_ListIteratorOfListOfBPnt2D_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineAlloc_HeaderFile
#include <Standard_DefineAlloc.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

#ifndef _Standard_Address_HeaderFile
#include <Standard_Address.hxx>
#endif
#ifndef _Handle_HLRBRep_ListNodeOfListOfBPnt2D_HeaderFile
#include <Handle_HLRBRep_ListNodeOfListOfBPnt2D.hxx>
#endif
#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
class Standard_NoMoreObject;
class Standard_NoSuchObject;
class HLRBRep_ListOfBPnt2D;
class HLRBRep_BiPnt2D;
class HLRBRep_ListNodeOfListOfBPnt2D;



class HLRBRep_ListIteratorOfListOfBPnt2D  {
public:

  DEFINE_STANDARD_ALLOC

  
  Standard_EXPORT   HLRBRep_ListIteratorOfListOfBPnt2D();
  
  Standard_EXPORT   HLRBRep_ListIteratorOfListOfBPnt2D(const HLRBRep_ListOfBPnt2D& L);
  
  Standard_EXPORT     void Initialize(const HLRBRep_ListOfBPnt2D& L) ;
  
        Standard_Boolean More() const;
  
  Standard_EXPORT     void Next() ;
  
  Standard_EXPORT     HLRBRep_BiPnt2D& Value() const;


friend class HLRBRep_ListOfBPnt2D;



protected:





private:



Standard_Address current;
Standard_Address previous;


};

#define Item HLRBRep_BiPnt2D
#define Item_hxx <HLRBRep_BiPnt2D.hxx>
#define TCollection_ListNode HLRBRep_ListNodeOfListOfBPnt2D
#define TCollection_ListNode_hxx <HLRBRep_ListNodeOfListOfBPnt2D.hxx>
#define TCollection_ListIterator HLRBRep_ListIteratorOfListOfBPnt2D
#define TCollection_ListIterator_hxx <HLRBRep_ListIteratorOfListOfBPnt2D.hxx>
#define Handle_TCollection_ListNode Handle_HLRBRep_ListNodeOfListOfBPnt2D
#define TCollection_ListNode_Type_() HLRBRep_ListNodeOfListOfBPnt2D_Type_()
#define TCollection_List HLRBRep_ListOfBPnt2D
#define TCollection_List_hxx <HLRBRep_ListOfBPnt2D.hxx>

#include <TCollection_ListIterator.lxx>

#undef Item
#undef Item_hxx
#undef TCollection_ListNode
#undef TCollection_ListNode_hxx
#undef TCollection_ListIterator
#undef TCollection_ListIterator_hxx
#undef Handle_TCollection_ListNode
#undef TCollection_ListNode_Type_
#undef TCollection_List
#undef TCollection_List_hxx


// other Inline functions and methods (like "C++: function call" methods)


#endif
