// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _IFSelect_SelectModelEntities_HeaderFile
#define _IFSelect_SelectModelEntities_HeaderFile

#include <Standard.hxx>
#include <Standard_DefineHandle.hxx>
#include <Handle_IFSelect_SelectModelEntities.hxx>

#include <IFSelect_SelectBase.hxx>
class Interface_EntityIterator;
class Interface_Graph;
class TCollection_AsciiString;


//! A SelectModelEntities gets all the Entities of an
//! InterfaceModel.
class IFSelect_SelectModelEntities : public IFSelect_SelectBase
{

public:

  
  //! Creates a SelectModelRoot
  Standard_EXPORT IFSelect_SelectModelEntities();
  
  //! Returns the list of selected entities : the Entities of the
  //! Model (note that this result assures naturally uniqueness)
  Standard_EXPORT   Interface_EntityIterator RootResult (const Interface_Graph& G)  const;
  
  //! The complete list of Entities (including shared ones) ...
  //! is exactly identical to RootResults in this case
  Standard_EXPORT virtual   Interface_EntityIterator CompleteResult (const Interface_Graph& G)  const;
  
  //! Returns a text defining the criterium : "Model Entities"
  Standard_EXPORT   TCollection_AsciiString Label()  const;




  DEFINE_STANDARD_RTTI(IFSelect_SelectModelEntities)

protected:




private: 




};







#endif // _IFSelect_SelectModelEntities_HeaderFile
