// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _IntAna_ListNodeOfListOfCurve_HeaderFile
#define _IntAna_ListNodeOfListOfCurve_HeaderFile

#include <Standard.hxx>
#include <Standard_DefineHandle.hxx>
#include <Handle_IntAna_ListNodeOfListOfCurve.hxx>

#include <IntAna_Curve.hxx>
#include <TCollection_MapNode.hxx>
#include <TCollection_MapNodePtr.hxx>
class IntAna_Curve;
class IntAna_ListOfCurve;
class IntAna_ListIteratorOfListOfCurve;



class IntAna_ListNodeOfListOfCurve : public TCollection_MapNode
{

public:

  
    IntAna_ListNodeOfListOfCurve(const IntAna_Curve& I, const TCollection_MapNodePtr& n);
  
      IntAna_Curve& Value()  const;




  DEFINE_STANDARD_RTTI(IntAna_ListNodeOfListOfCurve)

protected:




private: 


  IntAna_Curve myValue;


};

#define Item IntAna_Curve
#define Item_hxx <IntAna_Curve.hxx>
#define TCollection_ListNode IntAna_ListNodeOfListOfCurve
#define TCollection_ListNode_hxx <IntAna_ListNodeOfListOfCurve.hxx>
#define TCollection_ListIterator IntAna_ListIteratorOfListOfCurve
#define TCollection_ListIterator_hxx <IntAna_ListIteratorOfListOfCurve.hxx>
#define Handle_TCollection_ListNode Handle_IntAna_ListNodeOfListOfCurve
#define TCollection_ListNode_Type_() IntAna_ListNodeOfListOfCurve_Type_()
#define TCollection_List IntAna_ListOfCurve
#define TCollection_List_hxx <IntAna_ListOfCurve.hxx>

#include <TCollection_ListNode.lxx>

#undef Item
#undef Item_hxx
#undef TCollection_ListNode
#undef TCollection_ListNode_hxx
#undef TCollection_ListIterator
#undef TCollection_ListIterator_hxx
#undef Handle_TCollection_ListNode
#undef TCollection_ListNode_Type_
#undef TCollection_List
#undef TCollection_List_hxx




#endif // _IntAna_ListNodeOfListOfCurve_HeaderFile
