// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _IntTools_SequenceNodeOfSequenceOfRanges_HeaderFile
#define _IntTools_SequenceNodeOfSequenceOfRanges_HeaderFile

#include <Standard.hxx>
#include <Standard_DefineHandle.hxx>
#include <Handle_IntTools_SequenceNodeOfSequenceOfRanges.hxx>

#include <IntTools_Range.hxx>
#include <TCollection_SeqNode.hxx>
#include <TCollection_SeqNodePtr.hxx>
class IntTools_Range;
class IntTools_SequenceOfRanges;



class IntTools_SequenceNodeOfSequenceOfRanges : public TCollection_SeqNode
{

public:

  
    IntTools_SequenceNodeOfSequenceOfRanges(const IntTools_Range& I, const TCollection_SeqNodePtr& n, const TCollection_SeqNodePtr& p);
  
      IntTools_Range& Value()  const;




  DEFINE_STANDARD_RTTI(IntTools_SequenceNodeOfSequenceOfRanges)

protected:




private: 


  IntTools_Range myValue;


};

#define SeqItem IntTools_Range
#define SeqItem_hxx <IntTools_Range.hxx>
#define TCollection_SequenceNode IntTools_SequenceNodeOfSequenceOfRanges
#define TCollection_SequenceNode_hxx <IntTools_SequenceNodeOfSequenceOfRanges.hxx>
#define Handle_TCollection_SequenceNode Handle_IntTools_SequenceNodeOfSequenceOfRanges
#define TCollection_SequenceNode_Type_() IntTools_SequenceNodeOfSequenceOfRanges_Type_()
#define TCollection_Sequence IntTools_SequenceOfRanges
#define TCollection_Sequence_hxx <IntTools_SequenceOfRanges.hxx>

#include <TCollection_SequenceNode.lxx>

#undef SeqItem
#undef SeqItem_hxx
#undef TCollection_SequenceNode
#undef TCollection_SequenceNode_hxx
#undef Handle_TCollection_SequenceNode
#undef TCollection_SequenceNode_Type_
#undef TCollection_Sequence
#undef TCollection_Sequence_hxx




#endif // _IntTools_SequenceNodeOfSequenceOfRanges_HeaderFile
