// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _LocOpe_Generator_HeaderFile
#define _LocOpe_Generator_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineAlloc_HeaderFile
#include <Standard_DefineAlloc.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

#ifndef _TopoDS_Shape_HeaderFile
#include <TopoDS_Shape.hxx>
#endif
#ifndef _Handle_LocOpe_GeneratedShape_HeaderFile
#include <Handle_LocOpe_GeneratedShape.hxx>
#endif
#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
#ifndef _TopTools_DataMapOfShapeListOfShape_HeaderFile
#include <TopTools_DataMapOfShapeListOfShape.hxx>
#endif
class LocOpe_GeneratedShape;
class StdFail_NotDone;
class Standard_NullObject;
class Standard_NoSuchObject;
class TopoDS_Shape;
class TopTools_ListOfShape;
class TopoDS_Face;



class LocOpe_Generator  {
public:

  DEFINE_STANDARD_ALLOC

  //! Empty constructor. <br>
      LocOpe_Generator();
  //! Creates the algorithm on the shape <S>. <br>
      LocOpe_Generator(const TopoDS_Shape& S);
  //! Initializes the algorithm on the shape <S>. <br>
        void Init(const TopoDS_Shape& S) ;
  
  Standard_EXPORT     void Perform(const Handle(LocOpe_GeneratedShape)& G) ;
  
        Standard_Boolean IsDone() const;
  //! Returns the new shape <br>
       const TopoDS_Shape& ResultingShape() const;
  //! Returns the initial shape <br>
       const TopoDS_Shape& Shape() const;
  //! Returns  the  descendant  face  of <F>.    <F> may <br>
//!          belong to the original shape or to the "generated" <br>
//!          shape.  The returned    face may be   a null shape <br>
//!          (when <F> disappears). <br>
  Standard_EXPORT    const TopTools_ListOfShape& DescendantFace(const TopoDS_Face& F) ;





protected:





private:



TopoDS_Shape myShape;
Handle_LocOpe_GeneratedShape myGen;
Standard_Boolean myDone;
TopoDS_Shape myRes;
TopTools_DataMapOfShapeListOfShape myModShapes;


};


#include <LocOpe_Generator.lxx>



// other Inline functions and methods (like "C++: function call" methods)


#endif
