// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _MeshVS_MeshPtr_HeaderFile
#define _MeshVS_MeshPtr_HeaderFile

class MeshVS_Mesh;
typedef MeshVS_Mesh* MeshVS_MeshPtr;

#endif // _MeshVS_MeshPtr_HeaderFile
