// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _MeshVS_DataMapIteratorOfDataMapOfIntegerVector_HeaderFile
#define _MeshVS_DataMapIteratorOfDataMapOfIntegerVector_HeaderFile

#include <Standard.hxx>
#include <Standard_DefineAlloc.hxx>
#include <Standard_Macro.hxx>

#include <TCollection_BasicMapIterator.hxx>
#include <Standard_Integer.hxx>
#include <Handle_MeshVS_DataMapNodeOfDataMapOfIntegerVector.hxx>
class Standard_NoSuchObject;
class gp_Vec;
class TColStd_MapIntegerHasher;
class MeshVS_DataMapOfIntegerVector;
class MeshVS_DataMapNodeOfDataMapOfIntegerVector;



class MeshVS_DataMapIteratorOfDataMapOfIntegerVector  : public TCollection_BasicMapIterator
{
public:

  DEFINE_STANDARD_ALLOC

  
  Standard_EXPORT MeshVS_DataMapIteratorOfDataMapOfIntegerVector();
  
  Standard_EXPORT MeshVS_DataMapIteratorOfDataMapOfIntegerVector(const MeshVS_DataMapOfIntegerVector& aMap);
  
  Standard_EXPORT   void Initialize (const MeshVS_DataMapOfIntegerVector& aMap) ;
  
  Standard_EXPORT  const  Standard_Integer& Key()  const;
  
  Standard_EXPORT  const  gp_Vec& Value()  const;




protected:





private:





};







#endif // _MeshVS_DataMapIteratorOfDataMapOfIntegerVector_HeaderFile
