// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _MeshVS_DataMapNodeOfDataMapOfIntegerVector_HeaderFile
#define _MeshVS_DataMapNodeOfDataMapOfIntegerVector_HeaderFile

#include <Standard.hxx>
#include <Standard_DefineHandle.hxx>
#include <Handle_MeshVS_DataMapNodeOfDataMapOfIntegerVector.hxx>

#include <Standard_Integer.hxx>
#include <gp_Vec.hxx>
#include <TCollection_MapNode.hxx>
#include <TCollection_MapNodePtr.hxx>
class gp_Vec;
class TColStd_MapIntegerHasher;
class MeshVS_DataMapOfIntegerVector;
class MeshVS_DataMapIteratorOfDataMapOfIntegerVector;



class MeshVS_DataMapNodeOfDataMapOfIntegerVector : public TCollection_MapNode
{

public:

  
    MeshVS_DataMapNodeOfDataMapOfIntegerVector(const Standard_Integer& K, const gp_Vec& I, const TCollection_MapNodePtr& n);
  
      Standard_Integer& Key()  const;
  
      gp_Vec& Value()  const;




  DEFINE_STANDARD_RTTI(MeshVS_DataMapNodeOfDataMapOfIntegerVector)

protected:




private: 


  Standard_Integer myKey;
  gp_Vec myValue;


};

#define TheKey Standard_Integer
#define TheKey_hxx <Standard_Integer.hxx>
#define TheItem gp_Vec
#define TheItem_hxx <gp_Vec.hxx>
#define Hasher TColStd_MapIntegerHasher
#define Hasher_hxx <TColStd_MapIntegerHasher.hxx>
#define TCollection_DataMapNode MeshVS_DataMapNodeOfDataMapOfIntegerVector
#define TCollection_DataMapNode_hxx <MeshVS_DataMapNodeOfDataMapOfIntegerVector.hxx>
#define TCollection_DataMapIterator MeshVS_DataMapIteratorOfDataMapOfIntegerVector
#define TCollection_DataMapIterator_hxx <MeshVS_DataMapIteratorOfDataMapOfIntegerVector.hxx>
#define Handle_TCollection_DataMapNode Handle_MeshVS_DataMapNodeOfDataMapOfIntegerVector
#define TCollection_DataMapNode_Type_() MeshVS_DataMapNodeOfDataMapOfIntegerVector_Type_()
#define TCollection_DataMap MeshVS_DataMapOfIntegerVector
#define TCollection_DataMap_hxx <MeshVS_DataMapOfIntegerVector.hxx>

#include <TCollection_DataMapNode.lxx>

#undef TheKey
#undef TheKey_hxx
#undef TheItem
#undef TheItem_hxx
#undef Hasher
#undef Hasher_hxx
#undef TCollection_DataMapNode
#undef TCollection_DataMapNode_hxx
#undef TCollection_DataMapIterator
#undef TCollection_DataMapIterator_hxx
#undef Handle_TCollection_DataMapNode
#undef TCollection_DataMapNode_Type_
#undef TCollection_DataMap
#undef TCollection_DataMap_hxx




#endif // _MeshVS_DataMapNodeOfDataMapOfIntegerVector_HeaderFile
