// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _MoniTool_HSequenceOfElement_HeaderFile
#define _MoniTool_HSequenceOfElement_HeaderFile

#include <Standard.hxx>
#include <Standard_DefineHandle.hxx>
#include <Handle_MoniTool_HSequenceOfElement.hxx>

#include <MoniTool_SequenceOfElement.hxx>
#include <MMgt_TShared.hxx>
#include <Handle_MoniTool_Element.hxx>
#include <Standard_Boolean.hxx>
#include <Standard_Integer.hxx>
class Standard_NoSuchObject;
class Standard_OutOfRange;
class MoniTool_Element;
class MoniTool_SequenceOfElement;



class MoniTool_HSequenceOfElement : public MMgt_TShared
{

public:

  
    MoniTool_HSequenceOfElement();
  
      Standard_Boolean IsEmpty()  const;
  
      Standard_Integer Length()  const;
  
  Standard_EXPORT   void Clear() ;
  
  Standard_EXPORT   void Append (const Handle(MoniTool_Element)& anItem) ;
  
  Standard_EXPORT   void Append (const Handle(MoniTool_HSequenceOfElement)& aSequence) ;
  
  Standard_EXPORT   void Prepend (const Handle(MoniTool_Element)& anItem) ;
  
  Standard_EXPORT   void Prepend (const Handle(MoniTool_HSequenceOfElement)& aSequence) ;
  
  Standard_EXPORT   void Reverse() ;
  
  Standard_EXPORT   void InsertBefore (const Standard_Integer anIndex, const Handle(MoniTool_Element)& anItem) ;
  
  Standard_EXPORT   void InsertBefore (const Standard_Integer anIndex, const Handle(MoniTool_HSequenceOfElement)& aSequence) ;
  
  Standard_EXPORT   void InsertAfter (const Standard_Integer anIndex, const Handle(MoniTool_Element)& anItem) ;
  
  Standard_EXPORT   void InsertAfter (const Standard_Integer anIndex, const Handle(MoniTool_HSequenceOfElement)& aSequence) ;
  
  Standard_EXPORT   void Exchange (const Standard_Integer anIndex, const Standard_Integer anOtherIndex) ;
  
  Standard_EXPORT   Handle(MoniTool_HSequenceOfElement) Split (const Standard_Integer anIndex) ;
  
  Standard_EXPORT   void SetValue (const Standard_Integer anIndex, const Handle(MoniTool_Element)& anItem) ;
  
  Standard_EXPORT  const  Handle(MoniTool_Element)& Value (const Standard_Integer anIndex)  const;
  
  Standard_EXPORT   Handle(MoniTool_Element)& ChangeValue (const Standard_Integer anIndex) ;
  
  Standard_EXPORT   void Remove (const Standard_Integer anIndex) ;
  
  Standard_EXPORT   void Remove (const Standard_Integer fromIndex, const Standard_Integer toIndex) ;
  
     const  MoniTool_SequenceOfElement& Sequence()  const;
  
      MoniTool_SequenceOfElement& ChangeSequence() ;




  DEFINE_STANDARD_RTTI(MoniTool_HSequenceOfElement)

protected:




private: 


  MoniTool_SequenceOfElement mySequence;


};

#define Item Handle(MoniTool_Element)
#define Item_hxx <MoniTool_Element.hxx>
#define TheSequence MoniTool_SequenceOfElement
#define TheSequence_hxx <MoniTool_SequenceOfElement.hxx>
#define TCollection_HSequence MoniTool_HSequenceOfElement
#define TCollection_HSequence_hxx <MoniTool_HSequenceOfElement.hxx>
#define Handle_TCollection_HSequence Handle_MoniTool_HSequenceOfElement
#define TCollection_HSequence_Type_() MoniTool_HSequenceOfElement_Type_()

#include <TCollection_HSequence.lxx>

#undef Item
#undef Item_hxx
#undef TheSequence
#undef TheSequence_hxx
#undef TCollection_HSequence
#undef TCollection_HSequence_hxx
#undef Handle_TCollection_HSequence
#undef TCollection_HSequence_Type_




#endif // _MoniTool_HSequenceOfElement_HeaderFile
