// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _PColgp_VArrayNodeOfFieldOfHArray2OfVec_HeaderFile
#define _PColgp_VArrayNodeOfFieldOfHArray2OfVec_HeaderFile

#include <Standard_Macro.hxx>
#include <Standard_DefineHandle.hxx>
#include <Standard.hxx>
#include <Handle_PColgp_VArrayNodeOfFieldOfHArray2OfVec.hxx>

#include <Standard_Address.hxx>
#include <gp_Vec.hxx>
#include <PStandard_ArrayNode.hxx>
class gp_Vec;
class PColgp_FieldOfHArray2OfVec;
class PColgp_VArrayTNodeOfFieldOfHArray2OfVec;


class PColgp_VArrayNodeOfFieldOfHArray2OfVec : public PStandard_ArrayNode
{

public:

  
  Standard_EXPORT PColgp_VArrayNodeOfFieldOfHArray2OfVec();
  
  Standard_EXPORT PColgp_VArrayNodeOfFieldOfHArray2OfVec(const gp_Vec& aValue);
  
  Standard_EXPORT   void SetValue (const gp_Vec& aValue) ;
  
  Standard_EXPORT   Standard_Address Value()  const;

PColgp_VArrayNodeOfFieldOfHArray2OfVec(const Storage_stCONSTclCOM& a) : PStandard_ArrayNode(a)
{
  
}
    const gp_Vec& _CSFDB_GetPColgp_VArrayNodeOfFieldOfHArray2OfVecmyValue() const { return myValue; }



  DEFINE_STANDARD_RTTI(PColgp_VArrayNodeOfFieldOfHArray2OfVec)

protected:




private: 


  gp_Vec myValue;


};







#endif // _PColgp_VArrayNodeOfFieldOfHArray2OfVec_HeaderFile
