// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _ProjLib_SequenceNodeOfSequenceOfHSequenceOfPnt_HeaderFile
#define _ProjLib_SequenceNodeOfSequenceOfHSequenceOfPnt_HeaderFile

#include <Standard.hxx>
#include <Standard_DefineHandle.hxx>
#include <Handle_ProjLib_SequenceNodeOfSequenceOfHSequenceOfPnt.hxx>

#include <Handle_TColgp_HSequenceOfPnt.hxx>
#include <TCollection_SeqNode.hxx>
#include <TCollection_SeqNodePtr.hxx>
class TColgp_HSequenceOfPnt;
class ProjLib_SequenceOfHSequenceOfPnt;



class ProjLib_SequenceNodeOfSequenceOfHSequenceOfPnt : public TCollection_SeqNode
{

public:

  
    ProjLib_SequenceNodeOfSequenceOfHSequenceOfPnt(const Handle(TColgp_HSequenceOfPnt)& I, const TCollection_SeqNodePtr& n, const TCollection_SeqNodePtr& p);
  
      Handle(TColgp_HSequenceOfPnt)& Value()  const;




  DEFINE_STANDARD_RTTI(ProjLib_SequenceNodeOfSequenceOfHSequenceOfPnt)

protected:




private: 


  Handle(TColgp_HSequenceOfPnt) myValue;


};

#define SeqItem Handle(TColgp_HSequenceOfPnt)
#define SeqItem_hxx <TColgp_HSequenceOfPnt.hxx>
#define TCollection_SequenceNode ProjLib_SequenceNodeOfSequenceOfHSequenceOfPnt
#define TCollection_SequenceNode_hxx <ProjLib_SequenceNodeOfSequenceOfHSequenceOfPnt.hxx>
#define Handle_TCollection_SequenceNode Handle_ProjLib_SequenceNodeOfSequenceOfHSequenceOfPnt
#define TCollection_SequenceNode_Type_() ProjLib_SequenceNodeOfSequenceOfHSequenceOfPnt_Type_()
#define TCollection_Sequence ProjLib_SequenceOfHSequenceOfPnt
#define TCollection_Sequence_hxx <ProjLib_SequenceOfHSequenceOfPnt.hxx>

#include <TCollection_SequenceNode.lxx>

#undef SeqItem
#undef SeqItem_hxx
#undef TCollection_SequenceNode
#undef TCollection_SequenceNode_hxx
#undef Handle_TCollection_SequenceNode
#undef TCollection_SequenceNode_Type_
#undef TCollection_Sequence
#undef TCollection_Sequence_hxx




#endif // _ProjLib_SequenceNodeOfSequenceOfHSequenceOfPnt_HeaderFile
