// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _PTopoDS_Face_HeaderFile
#define _PTopoDS_Face_HeaderFile

#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Handle_PTopoDS_Face_HeaderFile
#include <Handle_PTopoDS_Face.hxx>
#endif

#ifndef _PTopoDS_HShape_HeaderFile
#include <PTopoDS_HShape.hxx>
#endif


class PTopoDS_Face : public PTopoDS_HShape {

public:

  
  Standard_EXPORT   PTopoDS_Face();

PTopoDS_Face(const Storage_stCONSTclCOM& a) : PTopoDS_HShape(a)
{
  
}



  DEFINE_STANDARD_RTTI(PTopoDS_Face)

protected:




private: 




};





// other Inline functions and methods (like "C++: function call" methods)


#endif
