// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _Quantity_TypeOfColor_HeaderFile
#define _Quantity_TypeOfColor_HeaderFile

#include <Standard_PrimitiveTypes.hxx>

//! Identifies color definition systems
//! -   Quantity_TOC_RGB: with this system a
//! color is defined by its quantities of red, green and blue (R-G-B values).
//! -   Quantity_TOC_HLS: with this system a
//! color is defined by its hue angle and its
//! lightness and saturation values (H-L-S values).
//! A Quantity_Color object may define a color
//! from three values R-G-B or H-L-S according
//! to a given color definition system.
enum Quantity_TypeOfColor
{
Quantity_TOC_RGB,
Quantity_TOC_HLS
};

#endif // _Quantity_TypeOfColor_HeaderFile
