// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _SelectMgr_StateOfSelection_HeaderFile
#define _SelectMgr_StateOfSelection_HeaderFile

#include <Standard_PrimitiveTypes.hxx>

//! different state of a Selection in a ViewerSelector...
enum SelectMgr_StateOfSelection
{
SelectMgr_SOS_Activated,
SelectMgr_SOS_Deactivated,
SelectMgr_SOS_Sleeping,
SelectMgr_SOS_Any,
SelectMgr_SOS_Unknown
};

#endif // _SelectMgr_StateOfSelection_HeaderFile
