// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _ShapeExtend_DataMapOfShapeListOfMsg_HeaderFile
#define _ShapeExtend_DataMapOfShapeListOfMsg_HeaderFile

#include <Standard.hxx>
#include <Standard_DefineAlloc.hxx>
#include <Standard_Macro.hxx>

#include <TCollection_BasicMap.hxx>
#include <Handle_ShapeExtend_DataMapNodeOfDataMapOfShapeListOfMsg.hxx>
#include <Standard_Integer.hxx>
#include <Standard_Boolean.hxx>
#include <Standard_Address.hxx>
class Standard_DomainError;
class Standard_NoSuchObject;
class TopoDS_Shape;
class Message_ListOfMsg;
class TopTools_ShapeMapHasher;
class ShapeExtend_DataMapNodeOfDataMapOfShapeListOfMsg;
class ShapeExtend_DataMapIteratorOfDataMapOfShapeListOfMsg;



class ShapeExtend_DataMapOfShapeListOfMsg  : public TCollection_BasicMap
{
public:

  DEFINE_STANDARD_ALLOC

  
  Standard_EXPORT ShapeExtend_DataMapOfShapeListOfMsg(const Standard_Integer NbBuckets = 1);
  
  Standard_EXPORT   ShapeExtend_DataMapOfShapeListOfMsg& Assign (const ShapeExtend_DataMapOfShapeListOfMsg& Other) ;
  ShapeExtend_DataMapOfShapeListOfMsg& operator = (const ShapeExtend_DataMapOfShapeListOfMsg& Other) 
{
  return Assign(Other);
}
  
  Standard_EXPORT   void ReSize (const Standard_Integer NbBuckets) ;
  
  Standard_EXPORT   void Clear() ;
~ShapeExtend_DataMapOfShapeListOfMsg()
{
  Clear();
}
  
  Standard_EXPORT   Standard_Boolean Bind (const TopoDS_Shape& K, const Message_ListOfMsg& I) ;
  
  Standard_EXPORT   Standard_Boolean IsBound (const TopoDS_Shape& K)  const;
  
  Standard_EXPORT   Standard_Boolean UnBind (const TopoDS_Shape& K) ;
  
  Standard_EXPORT  const  Message_ListOfMsg& Find (const TopoDS_Shape& K)  const;
 const  Message_ListOfMsg& operator() (const TopoDS_Shape& K)  const
{
  return Find(K);
}
  
  Standard_EXPORT   Message_ListOfMsg& ChangeFind (const TopoDS_Shape& K) ;
  Message_ListOfMsg& operator() (const TopoDS_Shape& K) 
{
  return ChangeFind(K);
}
  
  Standard_EXPORT   Standard_Address Find1 (const TopoDS_Shape& K)  const;
  
  Standard_EXPORT   Standard_Address ChangeFind1 (const TopoDS_Shape& K) ;




protected:





private:

  
  Standard_EXPORT ShapeExtend_DataMapOfShapeListOfMsg(const ShapeExtend_DataMapOfShapeListOfMsg& Other);




};







#endif // _ShapeExtend_DataMapOfShapeListOfMsg_HeaderFile
