// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _StepElement_HSequenceOfCurveElementSectionDefinition_HeaderFile
#define _StepElement_HSequenceOfCurveElementSectionDefinition_HeaderFile

#include <Standard.hxx>
#include <Standard_DefineHandle.hxx>
#include <Handle_StepElement_HSequenceOfCurveElementSectionDefinition.hxx>

#include <StepElement_SequenceOfCurveElementSectionDefinition.hxx>
#include <MMgt_TShared.hxx>
#include <Handle_StepElement_CurveElementSectionDefinition.hxx>
#include <Standard_Boolean.hxx>
#include <Standard_Integer.hxx>
class Standard_NoSuchObject;
class Standard_OutOfRange;
class StepElement_CurveElementSectionDefinition;
class StepElement_SequenceOfCurveElementSectionDefinition;



class StepElement_HSequenceOfCurveElementSectionDefinition : public MMgt_TShared
{

public:

  
    StepElement_HSequenceOfCurveElementSectionDefinition();
  
      Standard_Boolean IsEmpty()  const;
  
      Standard_Integer Length()  const;
  
  Standard_EXPORT   void Clear() ;
  
  Standard_EXPORT   void Append (const Handle(StepElement_CurveElementSectionDefinition)& anItem) ;
  
  Standard_EXPORT   void Append (const Handle(StepElement_HSequenceOfCurveElementSectionDefinition)& aSequence) ;
  
  Standard_EXPORT   void Prepend (const Handle(StepElement_CurveElementSectionDefinition)& anItem) ;
  
  Standard_EXPORT   void Prepend (const Handle(StepElement_HSequenceOfCurveElementSectionDefinition)& aSequence) ;
  
  Standard_EXPORT   void Reverse() ;
  
  Standard_EXPORT   void InsertBefore (const Standard_Integer anIndex, const Handle(StepElement_CurveElementSectionDefinition)& anItem) ;
  
  Standard_EXPORT   void InsertBefore (const Standard_Integer anIndex, const Handle(StepElement_HSequenceOfCurveElementSectionDefinition)& aSequence) ;
  
  Standard_EXPORT   void InsertAfter (const Standard_Integer anIndex, const Handle(StepElement_CurveElementSectionDefinition)& anItem) ;
  
  Standard_EXPORT   void InsertAfter (const Standard_Integer anIndex, const Handle(StepElement_HSequenceOfCurveElementSectionDefinition)& aSequence) ;
  
  Standard_EXPORT   void Exchange (const Standard_Integer anIndex, const Standard_Integer anOtherIndex) ;
  
  Standard_EXPORT   Handle(StepElement_HSequenceOfCurveElementSectionDefinition) Split (const Standard_Integer anIndex) ;
  
  Standard_EXPORT   void SetValue (const Standard_Integer anIndex, const Handle(StepElement_CurveElementSectionDefinition)& anItem) ;
  
  Standard_EXPORT  const  Handle(StepElement_CurveElementSectionDefinition)& Value (const Standard_Integer anIndex)  const;
  
  Standard_EXPORT   Handle(StepElement_CurveElementSectionDefinition)& ChangeValue (const Standard_Integer anIndex) ;
  
  Standard_EXPORT   void Remove (const Standard_Integer anIndex) ;
  
  Standard_EXPORT   void Remove (const Standard_Integer fromIndex, const Standard_Integer toIndex) ;
  
     const  StepElement_SequenceOfCurveElementSectionDefinition& Sequence()  const;
  
      StepElement_SequenceOfCurveElementSectionDefinition& ChangeSequence() ;




  DEFINE_STANDARD_RTTI(StepElement_HSequenceOfCurveElementSectionDefinition)

protected:




private: 


  StepElement_SequenceOfCurveElementSectionDefinition mySequence;


};

#define Item Handle(StepElement_CurveElementSectionDefinition)
#define Item_hxx <StepElement_CurveElementSectionDefinition.hxx>
#define TheSequence StepElement_SequenceOfCurveElementSectionDefinition
#define TheSequence_hxx <StepElement_SequenceOfCurveElementSectionDefinition.hxx>
#define TCollection_HSequence StepElement_HSequenceOfCurveElementSectionDefinition
#define TCollection_HSequence_hxx <StepElement_HSequenceOfCurveElementSectionDefinition.hxx>
#define Handle_TCollection_HSequence Handle_StepElement_HSequenceOfCurveElementSectionDefinition
#define TCollection_HSequence_Type_() StepElement_HSequenceOfCurveElementSectionDefinition_Type_()

#include <TCollection_HSequence.lxx>

#undef Item
#undef Item_hxx
#undef TheSequence
#undef TheSequence_hxx
#undef TCollection_HSequence
#undef TCollection_HSequence_hxx
#undef Handle_TCollection_HSequence
#undef TCollection_HSequence_Type_




#endif // _StepElement_HSequenceOfCurveElementSectionDefinition_HeaderFile
