// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _StepElement_HArray1OfHSequenceOfCurveElementPurposeMember_HeaderFile
#define _StepElement_HArray1OfHSequenceOfCurveElementPurposeMember_HeaderFile

#include <Standard.hxx>
#include <Standard_DefineHandle.hxx>
#include <Handle_StepElement_HArray1OfHSequenceOfCurveElementPurposeMember.hxx>

#include <StepElement_Array1OfHSequenceOfCurveElementPurposeMember.hxx>
#include <MMgt_TShared.hxx>
#include <Handle_StepElement_HSequenceOfCurveElementPurposeMember.hxx>
#include <Standard_Integer.hxx>
class Standard_RangeError;
class Standard_DimensionMismatch;
class Standard_OutOfRange;
class Standard_OutOfMemory;
class StepElement_HSequenceOfCurveElementPurposeMember;
class StepElement_Array1OfHSequenceOfCurveElementPurposeMember;



class StepElement_HArray1OfHSequenceOfCurveElementPurposeMember : public MMgt_TShared
{

public:

  
    StepElement_HArray1OfHSequenceOfCurveElementPurposeMember(const Standard_Integer Low, const Standard_Integer Up);
  
    StepElement_HArray1OfHSequenceOfCurveElementPurposeMember(const Standard_Integer Low, const Standard_Integer Up, const Handle(StepElement_HSequenceOfCurveElementPurposeMember)& V);
  
      void Init (const Handle(StepElement_HSequenceOfCurveElementPurposeMember)& V) ;
  
      Standard_Integer Length()  const;
  
      Standard_Integer Lower()  const;
  
      Standard_Integer Upper()  const;
  
      void SetValue (const Standard_Integer Index, const Handle(StepElement_HSequenceOfCurveElementPurposeMember)& Value) ;
  
     const  Handle(StepElement_HSequenceOfCurveElementPurposeMember)& Value (const Standard_Integer Index)  const;
  
      Handle(StepElement_HSequenceOfCurveElementPurposeMember)& ChangeValue (const Standard_Integer Index) ;
  
     const  StepElement_Array1OfHSequenceOfCurveElementPurposeMember& Array1()  const;
  
      StepElement_Array1OfHSequenceOfCurveElementPurposeMember& ChangeArray1() ;




  DEFINE_STANDARD_RTTI(StepElement_HArray1OfHSequenceOfCurveElementPurposeMember)

protected:




private: 


  StepElement_Array1OfHSequenceOfCurveElementPurposeMember myArray;


};

#define ItemHArray1 Handle(StepElement_HSequenceOfCurveElementPurposeMember)
#define ItemHArray1_hxx <StepElement_HSequenceOfCurveElementPurposeMember.hxx>
#define TheArray1 StepElement_Array1OfHSequenceOfCurveElementPurposeMember
#define TheArray1_hxx <StepElement_Array1OfHSequenceOfCurveElementPurposeMember.hxx>
#define TCollection_HArray1 StepElement_HArray1OfHSequenceOfCurveElementPurposeMember
#define TCollection_HArray1_hxx <StepElement_HArray1OfHSequenceOfCurveElementPurposeMember.hxx>
#define Handle_TCollection_HArray1 Handle_StepElement_HArray1OfHSequenceOfCurveElementPurposeMember
#define TCollection_HArray1_Type_() StepElement_HArray1OfHSequenceOfCurveElementPurposeMember_Type_()

#include <TCollection_HArray1.lxx>

#undef ItemHArray1
#undef ItemHArray1_hxx
#undef TheArray1
#undef TheArray1_hxx
#undef TCollection_HArray1
#undef TCollection_HArray1_hxx
#undef Handle_TCollection_HArray1
#undef TCollection_HArray1_Type_




#endif // _StepElement_HArray1OfHSequenceOfCurveElementPurposeMember_HeaderFile
