// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _StepBasic_GroupRelationship_HeaderFile
#define _StepBasic_GroupRelationship_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_StepBasic_GroupRelationship_HeaderFile
#include <Handle_StepBasic_GroupRelationship.hxx>
#endif

#ifndef _Handle_TCollection_HAsciiString_HeaderFile
#include <Handle_TCollection_HAsciiString.hxx>
#endif
#ifndef _Handle_StepBasic_Group_HeaderFile
#include <Handle_StepBasic_Group.hxx>
#endif
#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
#ifndef _MMgt_TShared_HeaderFile
#include <MMgt_TShared.hxx>
#endif
class TCollection_HAsciiString;
class StepBasic_Group;


//! Representation of STEP entity GroupRelationship <br>
class StepBasic_GroupRelationship : public MMgt_TShared {

public:

  //! Empty constructor <br>
  Standard_EXPORT   StepBasic_GroupRelationship();
  //! Initialize all fields (own and inherited) <br>
  Standard_EXPORT     void Init(const Handle(TCollection_HAsciiString)& aName,const Standard_Boolean hasDescription,const Handle(TCollection_HAsciiString)& aDescription,const Handle(StepBasic_Group)& aRelatingGroup,const Handle(StepBasic_Group)& aRelatedGroup) ;
  //! Returns field Name <br>
  Standard_EXPORT     Handle_TCollection_HAsciiString Name() const;
  //! Set field Name <br>
  Standard_EXPORT     void SetName(const Handle(TCollection_HAsciiString)& Name) ;
  //! Returns field Description <br>
  Standard_EXPORT     Handle_TCollection_HAsciiString Description() const;
  //! Set field Description <br>
  Standard_EXPORT     void SetDescription(const Handle(TCollection_HAsciiString)& Description) ;
  //! Returns True if optional field Description is defined <br>
  Standard_EXPORT     Standard_Boolean HasDescription() const;
  //! Returns field RelatingGroup <br>
  Standard_EXPORT     Handle_StepBasic_Group RelatingGroup() const;
  //! Set field RelatingGroup <br>
  Standard_EXPORT     void SetRelatingGroup(const Handle(StepBasic_Group)& RelatingGroup) ;
  //! Returns field RelatedGroup <br>
  Standard_EXPORT     Handle_StepBasic_Group RelatedGroup() const;
  //! Set field RelatedGroup <br>
  Standard_EXPORT     void SetRelatedGroup(const Handle(StepBasic_Group)& RelatedGroup) ;




  DEFINE_STANDARD_RTTI(StepBasic_GroupRelationship)

protected:




private: 


Handle_TCollection_HAsciiString theName;
Handle_TCollection_HAsciiString theDescription;
Handle_StepBasic_Group theRelatingGroup;
Handle_StepBasic_Group theRelatedGroup;
Standard_Boolean defDescription;


};





// other Inline functions and methods (like "C++: function call" methods)


#endif
