// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _StepVisual_PointStyle_HeaderFile
#define _StepVisual_PointStyle_HeaderFile

#include <Standard.hxx>
#include <Standard_DefineHandle.hxx>
#include <Handle_StepVisual_PointStyle.hxx>

#include <Handle_TCollection_HAsciiString.hxx>
#include <StepVisual_MarkerSelect.hxx>
#include <StepBasic_SizeSelect.hxx>
#include <Handle_StepVisual_Colour.hxx>
#include <MMgt_TShared.hxx>
class TCollection_HAsciiString;
class StepVisual_Colour;
class StepVisual_MarkerSelect;
class StepBasic_SizeSelect;



class StepVisual_PointStyle : public MMgt_TShared
{

public:

  
  //! Returns a PointStyle
  Standard_EXPORT StepVisual_PointStyle();
  
  Standard_EXPORT virtual   void Init (const Handle(TCollection_HAsciiString)& aName, const StepVisual_MarkerSelect& aMarker, const StepBasic_SizeSelect& aMarkerSize, const Handle(StepVisual_Colour)& aMarkerColour) ;
  
  Standard_EXPORT   void SetName (const Handle(TCollection_HAsciiString)& aName) ;
  
  Standard_EXPORT   Handle(TCollection_HAsciiString) Name()  const;
  
  Standard_EXPORT   void SetMarker (const StepVisual_MarkerSelect& aMarker) ;
  
  Standard_EXPORT   StepVisual_MarkerSelect Marker()  const;
  
  Standard_EXPORT   void SetMarkerSize (const StepBasic_SizeSelect& aMarkerSize) ;
  
  Standard_EXPORT   StepBasic_SizeSelect MarkerSize()  const;
  
  Standard_EXPORT   void SetMarkerColour (const Handle(StepVisual_Colour)& aMarkerColour) ;
  
  Standard_EXPORT   Handle(StepVisual_Colour) MarkerColour()  const;




  DEFINE_STANDARD_RTTI(StepVisual_PointStyle)

protected:




private: 


  Handle(TCollection_HAsciiString) name;
  StepVisual_MarkerSelect marker;
  StepBasic_SizeSelect markerSize;
  Handle(StepVisual_Colour) markerColour;


};







#endif // _StepVisual_PointStyle_HeaderFile
