// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _TColStd_MapOfInteger_HeaderFile
#define _TColStd_MapOfInteger_HeaderFile

#include <Standard.hxx>
#include <Standard_DefineAlloc.hxx>
#include <Standard_Macro.hxx>

#include <TCollection_BasicMap.hxx>
#include <Standard_Integer.hxx>
#include <Handle_TColStd_StdMapNodeOfMapOfInteger.hxx>
#include <Standard_Boolean.hxx>
class TColStd_MapIntegerHasher;
class TColStd_StdMapNodeOfMapOfInteger;
class TColStd_MapIteratorOfMapOfInteger;



class TColStd_MapOfInteger  : public TCollection_BasicMap
{
public:

  DEFINE_STANDARD_ALLOC

  
  Standard_EXPORT TColStd_MapOfInteger(const Standard_Integer NbBuckets = 1);
  
  Standard_EXPORT TColStd_MapOfInteger(const TColStd_MapOfInteger& Other);
  
  Standard_EXPORT   TColStd_MapOfInteger& Assign (const TColStd_MapOfInteger& Other) ;
  TColStd_MapOfInteger& operator = (const TColStd_MapOfInteger& Other) 
{
  return Assign(Other);
}
  
  Standard_EXPORT   void ReSize (const Standard_Integer NbBuckets) ;
  
  Standard_EXPORT   void Clear() ;
~TColStd_MapOfInteger()
{
  Clear();
}
  
  Standard_EXPORT   Standard_Boolean Add (const Standard_Integer& aKey) ;
  
  Standard_EXPORT   Standard_Boolean Contains (const Standard_Integer& aKey)  const;
  
  Standard_EXPORT   Standard_Boolean Remove (const Standard_Integer& aKey) ;




protected:





private:





};







#endif // _TColStd_MapOfInteger_HeaderFile
