// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _TopExp_StackOfIterator_HeaderFile
#define _TopExp_StackOfIterator_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineAlloc_HeaderFile
#include <Standard_DefineAlloc.hxx>
#endif
#ifndef _Standard_Macro_HeaderFile
#include <Standard_Macro.hxx>
#endif

#ifndef _Standard_Address_HeaderFile
#include <Standard_Address.hxx>
#endif
#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
#ifndef _Handle_TopExp_StackNodeOfStackOfIterator_HeaderFile
#include <Handle_TopExp_StackNodeOfStackOfIterator.hxx>
#endif
#ifndef _Standard_Boolean_HeaderFile
#include <Standard_Boolean.hxx>
#endif
class Standard_NoSuchObject;
class TopExp_StackIteratorOfStackOfIterator;
class TopoDS_Iterator;
class TopExp_StackNodeOfStackOfIterator;



class TopExp_StackOfIterator  {
public:

  DEFINE_STANDARD_ALLOC

  
  Standard_EXPORT   TopExp_StackOfIterator();
  
  Standard_EXPORT    const TopExp_StackOfIterator& Assign(const TopExp_StackOfIterator& Other) ;
   const TopExp_StackOfIterator& operator =(const TopExp_StackOfIterator& Other) 
{
  return Assign(Other);
}
  
        Standard_Boolean IsEmpty() const;
  
        Standard_Integer Depth() const;
  
  Standard_EXPORT    const TopoDS_Iterator& Top() const;
  
  Standard_EXPORT     void Push(const TopoDS_Iterator& I) ;
  
  Standard_EXPORT     void Pop() ;
  
  Standard_EXPORT     void Clear() ;
~TopExp_StackOfIterator()
{
  Clear();
}
  
  Standard_EXPORT     TopoDS_Iterator& ChangeTop() ;


friend class TopExp_StackIteratorOfStackOfIterator;



protected:





private:

  
  Standard_EXPORT   TopExp_StackOfIterator(const TopExp_StackOfIterator& Other);


Standard_Address myTop;
Standard_Integer myDepth;


};

#define Item TopoDS_Iterator
#define Item_hxx <TopoDS_Iterator.hxx>
#define TCollection_StackNode TopExp_StackNodeOfStackOfIterator
#define TCollection_StackNode_hxx <TopExp_StackNodeOfStackOfIterator.hxx>
#define TCollection_StackIterator TopExp_StackIteratorOfStackOfIterator
#define TCollection_StackIterator_hxx <TopExp_StackIteratorOfStackOfIterator.hxx>
#define Handle_TCollection_StackNode Handle_TopExp_StackNodeOfStackOfIterator
#define TCollection_StackNode_Type_() TopExp_StackNodeOfStackOfIterator_Type_()
#define TCollection_Stack TopExp_StackOfIterator
#define TCollection_Stack_hxx <TopExp_StackOfIterator.hxx>

#include <TCollection_Stack.lxx>

#undef Item
#undef Item_hxx
#undef TCollection_StackNode
#undef TCollection_StackNode_hxx
#undef TCollection_StackIterator
#undef TCollection_StackIterator_hxx
#undef Handle_TCollection_StackNode
#undef TCollection_StackNode_Type_
#undef TCollection_Stack
#undef TCollection_Stack_hxx


// other Inline functions and methods (like "C++: function call" methods)


#endif
