// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _TopOpeBRepDS_PointExplorer_HeaderFile
#define _TopOpeBRepDS_PointExplorer_HeaderFile

#include <Standard.hxx>
#include <Standard_DefineAlloc.hxx>
#include <Standard_Macro.hxx>

#include <Standard_Integer.hxx>
#include <Standard_Address.hxx>
#include <Standard_Boolean.hxx>
#include <TopOpeBRepDS_Point.hxx>
class TopOpeBRepDS_DataStructure;
class TopOpeBRepDS_Point;



class TopOpeBRepDS_PointExplorer 
{
public:

  DEFINE_STANDARD_ALLOC

  
  Standard_EXPORT TopOpeBRepDS_PointExplorer();
  
  Standard_EXPORT TopOpeBRepDS_PointExplorer(const TopOpeBRepDS_DataStructure& DS, const Standard_Boolean FindOnlyKeep = Standard_True);
  
  Standard_EXPORT   void Init (const TopOpeBRepDS_DataStructure& DS, const Standard_Boolean FindOnlyKeep = Standard_True) ;
  
  Standard_EXPORT   Standard_Boolean More()  const;
  
  Standard_EXPORT   void Next() ;
  
  Standard_EXPORT  const  TopOpeBRepDS_Point& Point()  const;
  
  Standard_EXPORT   Standard_Boolean IsPoint (const Standard_Integer I)  const;
  
  Standard_EXPORT   Standard_Boolean IsPointKeep (const Standard_Integer I)  const;
  
  Standard_EXPORT  const  TopOpeBRepDS_Point& Point (const Standard_Integer I)  const;
  
  Standard_EXPORT   Standard_Integer NbPoint() ;
  
  Standard_EXPORT   Standard_Integer Index()  const;




protected:





private:

  
  Standard_EXPORT   void Find() ;


  Standard_Integer myIndex;
  Standard_Integer myMax;
  Standard_Address myDS;
  Standard_Boolean myFound;
  TopOpeBRepDS_Point myEmpty;
  Standard_Boolean myFindKeep;


};







#endif // _TopOpeBRepDS_PointExplorer_HeaderFile
