// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _TopoDSToStep_MakeFaceError_HeaderFile
#define _TopoDSToStep_MakeFaceError_HeaderFile

#include <Standard_PrimitiveTypes.hxx>


enum TopoDSToStep_MakeFaceError
{
TopoDSToStep_FaceDone,
TopoDSToStep_InfiniteFace,
TopoDSToStep_NonManifoldFace,
TopoDSToStep_NoWireMapped,
TopoDSToStep_FaceOther
};

#endif // _TopoDSToStep_MakeFaceError_HeaderFile
