// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _Vrml_AsciiTextJustification_HeaderFile
#define _Vrml_AsciiTextJustification_HeaderFile

#include <Standard_PrimitiveTypes.hxx>


enum Vrml_AsciiTextJustification
{
Vrml_LEFT,
Vrml_CENTER,
Vrml_RIGHT
};

#endif // _Vrml_AsciiTextJustification_HeaderFile
