// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <PlotMgt_HListOfMFTFonts.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _Standard_RangeError_HeaderFile
#include <Standard_RangeError.hxx>
#endif
#ifndef _Standard_DimensionMismatch_HeaderFile
#include <Standard_DimensionMismatch.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _Standard_OutOfMemory_HeaderFile
#include <Standard_OutOfMemory.hxx>
#endif
#ifndef _MFT_FontManager_HeaderFile
#include <MFT_FontManager.hxx>
#endif
#ifndef _PlotMgt_ListOfMFTFonts_HeaderFile
#include <PlotMgt_ListOfMFTFonts.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(PlotMgt_HListOfMFTFonts)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(PlotMgt_HListOfMFTFonts)


IMPLEMENT_DOWNCAST(PlotMgt_HListOfMFTFonts,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(PlotMgt_HListOfMFTFonts)


#define ItemHArray1 Handle_MFT_FontManager
#define ItemHArray1_hxx <MFT_FontManager.hxx>
#define TheArray1 PlotMgt_ListOfMFTFonts
#define TheArray1_hxx <PlotMgt_ListOfMFTFonts.hxx>
#define TCollection_HArray1 PlotMgt_HListOfMFTFonts
#define TCollection_HArray1_hxx <PlotMgt_HListOfMFTFonts.hxx>
#define Handle_TCollection_HArray1 Handle_PlotMgt_HListOfMFTFonts
#define TCollection_HArray1_Type_() PlotMgt_HListOfMFTFonts_Type_()
#include <TCollection_HArray1.gxx>

