// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _TopTools_HArray1OfListOfShape_HeaderFile
#define _TopTools_HArray1OfListOfShape_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_TopTools_HArray1OfListOfShape_HeaderFile
#include <Handle_TopTools_HArray1OfListOfShape.hxx>
#endif

#ifndef _TopTools_Array1OfListOfShape_HeaderFile
#include <TopTools_Array1OfListOfShape.hxx>
#endif
#ifndef _MMgt_TShared_HeaderFile
#include <MMgt_TShared.hxx>
#endif
#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
class Standard_RangeError;
class Standard_DimensionMismatch;
class Standard_OutOfRange;
class Standard_OutOfMemory;
class TopTools_ListOfShape;
class TopTools_Array1OfListOfShape;



class TopTools_HArray1OfListOfShape : public MMgt_TShared {

public:

  
  Standard_EXPORT   TopTools_HArray1OfListOfShape(const Standard_Integer Low,const Standard_Integer Up);
  
  Standard_EXPORT   TopTools_HArray1OfListOfShape(const Standard_Integer Low,const Standard_Integer Up,const TopTools_ListOfShape& V);
  
  Standard_EXPORT     void Init(const TopTools_ListOfShape& V) ;
  
        Standard_Integer Length() const;
  
        Standard_Integer Lower() const;
  
        Standard_Integer Upper() const;
  
        void SetValue(const Standard_Integer Index,const TopTools_ListOfShape& Value) ;
  
       const TopTools_ListOfShape& Value(const Standard_Integer Index) const;
  
        TopTools_ListOfShape& ChangeValue(const Standard_Integer Index) ;
  
       const TopTools_Array1OfListOfShape& Array1() const;
  
        TopTools_Array1OfListOfShape& ChangeArray1() ;




  DEFINE_STANDARD_RTTI(TopTools_HArray1OfListOfShape)

protected:




private: 


TopTools_Array1OfListOfShape myArray;


};

#define ItemHArray1 TopTools_ListOfShape
#define ItemHArray1_hxx <TopTools_ListOfShape.hxx>
#define TheArray1 TopTools_Array1OfListOfShape
#define TheArray1_hxx <TopTools_Array1OfListOfShape.hxx>
#define TCollection_HArray1 TopTools_HArray1OfListOfShape
#define TCollection_HArray1_hxx <TopTools_HArray1OfListOfShape.hxx>
#define Handle_TCollection_HArray1 Handle_TopTools_HArray1OfListOfShape
#define TCollection_HArray1_Type_() TopTools_HArray1OfListOfShape_Type_()

#include <TCollection_HArray1.lxx>

#undef ItemHArray1
#undef ItemHArray1_hxx
#undef TheArray1
#undef TheArray1_hxx
#undef TCollection_HArray1
#undef TCollection_HArray1_hxx
#undef Handle_TCollection_HArray1
#undef TCollection_HArray1_Type_


// other Inline functions and methods (like "C++: function call" methods)


#endif
