// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <IntTools_ListNodeOfListOfBox.hxx>

#include <Standard_Type.hxx>

#include <Bnd_Box.hxx>
#include <IntTools_ListOfBox.hxx>
#include <IntTools_ListIteratorOfListOfBox.hxx>

 


IMPLEMENT_STANDARD_TYPE(IntTools_ListNodeOfListOfBox)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_MapNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(IntTools_ListNodeOfListOfBox)


IMPLEMENT_DOWNCAST(IntTools_ListNodeOfListOfBox,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(IntTools_ListNodeOfListOfBox)


#define Item Bnd_Box
#define Item_hxx <Bnd_Box.hxx>
#define TCollection_ListNode IntTools_ListNodeOfListOfBox
#define TCollection_ListNode_hxx <IntTools_ListNodeOfListOfBox.hxx>
#define TCollection_ListIterator IntTools_ListIteratorOfListOfBox
#define TCollection_ListIterator_hxx <IntTools_ListIteratorOfListOfBox.hxx>
#define Handle_TCollection_ListNode Handle_IntTools_ListNodeOfListOfBox
#define TCollection_ListNode_Type_() IntTools_ListNodeOfListOfBox_Type_()
#define TCollection_List IntTools_ListOfBox
#define TCollection_List_hxx <IntTools_ListOfBox.hxx>
#include <TCollection_ListNode.gxx>

