// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <IntTools_ListIteratorOfListOfSurfaceRangeSample.hxx>

#include <Standard_NoMoreObject.hxx>
#include <Standard_NoSuchObject.hxx>
#include <IntTools_ListOfSurfaceRangeSample.hxx>
#include <IntTools_SurfaceRangeSample.hxx>
#include <IntTools_ListNodeOfListOfSurfaceRangeSample.hxx>
 

#define Item IntTools_SurfaceRangeSample
#define Item_hxx <IntTools_SurfaceRangeSample.hxx>
#define TCollection_ListNode IntTools_ListNodeOfListOfSurfaceRangeSample
#define TCollection_ListNode_hxx <IntTools_ListNodeOfListOfSurfaceRangeSample.hxx>
#define TCollection_ListIterator IntTools_ListIteratorOfListOfSurfaceRangeSample
#define TCollection_ListIterator_hxx <IntTools_ListIteratorOfListOfSurfaceRangeSample.hxx>
#define Handle_TCollection_ListNode Handle_IntTools_ListNodeOfListOfSurfaceRangeSample
#define TCollection_ListNode_Type_() IntTools_ListNodeOfListOfSurfaceRangeSample_Type_()
#define TCollection_List IntTools_ListOfSurfaceRangeSample
#define TCollection_List_hxx <IntTools_ListOfSurfaceRangeSample.hxx>
#include <TCollection_ListIterator.gxx>

