// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _DrawFairCurve_Batten_HeaderFile
#define _DrawFairCurve_Batten_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_DrawFairCurve_Batten_HeaderFile
#include <Handle_DrawFairCurve_Batten.hxx>
#endif

#ifndef _Standard_Address_HeaderFile
#include <Standard_Address.hxx>
#endif
#ifndef _DrawTrSurf_BSplineCurve2d_HeaderFile
#include <DrawTrSurf_BSplineCurve2d.hxx>
#endif
#ifndef _Standard_Integer_HeaderFile
#include <Standard_Integer.hxx>
#endif
#ifndef _Standard_Real_HeaderFile
#include <Standard_Real.hxx>
#endif
#ifndef _Standard_OStream_HeaderFile
#include <Standard_OStream.hxx>
#endif
class gp_Pnt2d;


//! Interactive Draw object of type "Batten" <br>
class DrawFairCurve_Batten : public DrawTrSurf_BSplineCurve2d {

public:

  
  Standard_EXPORT   DrawFairCurve_Batten(const Standard_Address TheBatten);
  
  Standard_EXPORT     void Compute() ;
  
  Standard_EXPORT     void SetPoint(const Standard_Integer Side,const gp_Pnt2d& Point) ;
  
  Standard_EXPORT     void SetAngle(const Standard_Integer Side,const Standard_Real Angle) ;
  
  Standard_EXPORT     void SetSliding(const Standard_Real Length) ;
  
  Standard_EXPORT     void SetHeight(const Standard_Real Heigth) ;
  
  Standard_EXPORT     void SetSlope(const Standard_Real Slope) ;
  
  Standard_EXPORT     Standard_Real GetAngle(const Standard_Integer Side) const;
  
  Standard_EXPORT     Standard_Real GetSliding() const;
  
  Standard_EXPORT     void FreeSliding() ;
  
  Standard_EXPORT     void FreeAngle(const Standard_Integer Side) ;
  //! For variable dump. <br>
  Standard_EXPORT   virtual  void Dump(Standard_OStream& S) const;




  DEFINE_STANDARD_RTTI(DrawFairCurve_Batten)

protected:


Standard_Address MyBatten;


private: 




};





// other Inline functions and methods (like "C++: function call" methods)


#endif
