// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <PColgp_VArrayTNodeOfFieldOfHArray2OfXY.hxx>

#include <gp_XY.hxx>
#include <PColgp_FieldOfHArray2OfXY.hxx>
#include <PColgp_VArrayNodeOfFieldOfHArray2OfXY.hxx>
 

#define Item gp_XY
#define Item_hxx <gp_XY.hxx>
#define DBC_VArrayNode PColgp_VArrayNodeOfFieldOfHArray2OfXY
#define DBC_VArrayNode_hxx <PColgp_VArrayNodeOfFieldOfHArray2OfXY.hxx>
#define DBC_VArrayTNode PColgp_VArrayTNodeOfFieldOfHArray2OfXY
#define DBC_VArrayTNode_hxx <PColgp_VArrayTNodeOfFieldOfHArray2OfXY.hxx>
#define Handle_DBC_VArrayNode Handle_PColgp_VArrayNodeOfFieldOfHArray2OfXY
#define DBC_VArrayNode_Type_() PColgp_VArrayNodeOfFieldOfHArray2OfXY_Type_()
#define DBC_VArray PColgp_FieldOfHArray2OfXY
#define DBC_VArray_hxx <PColgp_FieldOfHArray2OfXY.hxx>
#include <DBC_VArrayTNode.gxx>

