#ifndef _ShapeSchema_HeaderFile
#include <ShapeSchema.hxx>
#endif
#ifndef _Storage_StreamUnknownTypeError_HeaderFile
#include <Storage_StreamUnknownTypeError.hxx>
#endif
#ifndef _TColStd_SequenceOfAsciiString_HeaderFile
#include <TColStd_SequenceOfAsciiString.hxx>
#endif
#ifndef _ShapeSchema_ObjMgt_ExternShareable_HeaderFile
#include <ShapeSchema_ObjMgt_ExternShareable.hxx>
#endif
#ifndef _ShapeSchema_ObjMgt_ExternRef_HeaderFile
#include <ShapeSchema_ObjMgt_ExternRef.hxx>
#endif
#ifndef _ShapeSchema_ObjMgt_PSeqOfExtRef_HeaderFile
#include <ShapeSchema_ObjMgt_PSeqOfExtRef.hxx>
#endif
#ifndef _ShapeSchema_ObjMgt_SeqNodeOfPSeqOfExtRef_HeaderFile
#include <ShapeSchema_ObjMgt_SeqNodeOfPSeqOfExtRef.hxx>
#endif
#ifndef _ShapeSchema_PTopLoc_Datum3D_HeaderFile
#include <ShapeSchema_PTopLoc_Datum3D.hxx>
#endif
#ifndef _ShapeSchema_PTopLoc_ItemLocation_HeaderFile
#include <ShapeSchema_PTopLoc_ItemLocation.hxx>
#endif
#ifndef _ShapeSchema_PColgp_HArray1OfCirc2d_HeaderFile
#include <ShapeSchema_PColgp_HArray1OfCirc2d.hxx>
#endif
#ifndef _ShapeSchema_PColgp_HArray1OfDir2d_HeaderFile
#include <ShapeSchema_PColgp_HArray1OfDir2d.hxx>
#endif
#ifndef _ShapeSchema_PColgp_HArray1OfLin2d_HeaderFile
#include <ShapeSchema_PColgp_HArray1OfLin2d.hxx>
#endif
#ifndef _ShapeSchema_PColgp_HArray1OfPnt2d_HeaderFile
#include <ShapeSchema_PColgp_HArray1OfPnt2d.hxx>
#endif
#ifndef _ShapeSchema_PColgp_HArray1OfVec2d_HeaderFile
#include <ShapeSchema_PColgp_HArray1OfVec2d.hxx>
#endif
#ifndef _ShapeSchema_PColgp_HArray1OfXY_HeaderFile
#include <ShapeSchema_PColgp_HArray1OfXY.hxx>
#endif
#ifndef _ShapeSchema_PColgp_HArray1OfDir_HeaderFile
#include <ShapeSchema_PColgp_HArray1OfDir.hxx>
#endif
#ifndef _ShapeSchema_PColgp_HArray1OfPnt_HeaderFile
#include <ShapeSchema_PColgp_HArray1OfPnt.hxx>
#endif
#ifndef _ShapeSchema_PColgp_HArray1OfVec_HeaderFile
#include <ShapeSchema_PColgp_HArray1OfVec.hxx>
#endif
#ifndef _ShapeSchema_PColgp_HArray1OfXYZ_HeaderFile
#include <ShapeSchema_PColgp_HArray1OfXYZ.hxx>
#endif
#ifndef _ShapeSchema_PColgp_HArray2OfCirc2d_HeaderFile
#include <ShapeSchema_PColgp_HArray2OfCirc2d.hxx>
#endif
#ifndef _ShapeSchema_PColgp_HArray2OfDir2d_HeaderFile
#include <ShapeSchema_PColgp_HArray2OfDir2d.hxx>
#endif
#ifndef _ShapeSchema_PColgp_HArray2OfLin2d_HeaderFile
#include <ShapeSchema_PColgp_HArray2OfLin2d.hxx>
#endif
#ifndef _ShapeSchema_PColgp_HArray2OfPnt2d_HeaderFile
#include <ShapeSchema_PColgp_HArray2OfPnt2d.hxx>
#endif
#ifndef _ShapeSchema_PColgp_HArray2OfVec2d_HeaderFile
#include <ShapeSchema_PColgp_HArray2OfVec2d.hxx>
#endif
#ifndef _ShapeSchema_PColgp_HArray2OfXY_HeaderFile
#include <ShapeSchema_PColgp_HArray2OfXY.hxx>
#endif
#ifndef _ShapeSchema_PColgp_HArray2OfDir_HeaderFile
#include <ShapeSchema_PColgp_HArray2OfDir.hxx>
#endif
#ifndef _ShapeSchema_PColgp_HArray2OfPnt_HeaderFile
#include <ShapeSchema_PColgp_HArray2OfPnt.hxx>
#endif
#ifndef _ShapeSchema_PColgp_HArray2OfVec_HeaderFile
#include <ShapeSchema_PColgp_HArray2OfVec.hxx>
#endif
#ifndef _ShapeSchema_PColgp_HArray2OfXYZ_HeaderFile
#include <ShapeSchema_PColgp_HArray2OfXYZ.hxx>
#endif
#ifndef _ShapeSchema_PColgp_HSequenceOfDir_HeaderFile
#include <ShapeSchema_PColgp_HSequenceOfDir.hxx>
#endif
#ifndef _ShapeSchema_PColgp_SeqNodeOfHSequenceOfDir_HeaderFile
#include <ShapeSchema_PColgp_SeqNodeOfHSequenceOfDir.hxx>
#endif
#ifndef _ShapeSchema_PColgp_HSequenceOfPnt_HeaderFile
#include <ShapeSchema_PColgp_HSequenceOfPnt.hxx>
#endif
#ifndef _ShapeSchema_PColgp_SeqNodeOfHSequenceOfPnt_HeaderFile
#include <ShapeSchema_PColgp_SeqNodeOfHSequenceOfPnt.hxx>
#endif
#ifndef _ShapeSchema_PColgp_HSequenceOfVec_HeaderFile
#include <ShapeSchema_PColgp_HSequenceOfVec.hxx>
#endif
#ifndef _ShapeSchema_PColgp_SeqNodeOfHSequenceOfVec_HeaderFile
#include <ShapeSchema_PColgp_SeqNodeOfHSequenceOfVec.hxx>
#endif
#ifndef _ShapeSchema_PColgp_HSequenceOfXYZ_HeaderFile
#include <ShapeSchema_PColgp_HSequenceOfXYZ.hxx>
#endif
#ifndef _ShapeSchema_PColgp_SeqNodeOfHSequenceOfXYZ_HeaderFile
#include <ShapeSchema_PColgp_SeqNodeOfHSequenceOfXYZ.hxx>
#endif
#ifndef _ShapeSchema_PGeom2d_Transformation_HeaderFile
#include <ShapeSchema_PGeom2d_Transformation.hxx>
#endif
#ifndef _ShapeSchema_PGeom2d_Geometry_HeaderFile
#include <ShapeSchema_PGeom2d_Geometry.hxx>
#endif
#ifndef _ShapeSchema_PGeom2d_Point_HeaderFile
#include <ShapeSchema_PGeom2d_Point.hxx>
#endif
#ifndef _ShapeSchema_PGeom2d_CartesianPoint_HeaderFile
#include <ShapeSchema_PGeom2d_CartesianPoint.hxx>
#endif
#ifndef _ShapeSchema_PGeom2d_Vector_HeaderFile
#include <ShapeSchema_PGeom2d_Vector.hxx>
#endif
#ifndef _ShapeSchema_PGeom2d_Direction_HeaderFile
#include <ShapeSchema_PGeom2d_Direction.hxx>
#endif
#ifndef _ShapeSchema_PGeom2d_VectorWithMagnitude_HeaderFile
#include <ShapeSchema_PGeom2d_VectorWithMagnitude.hxx>
#endif
#ifndef _ShapeSchema_PGeom2d_AxisPlacement_HeaderFile
#include <ShapeSchema_PGeom2d_AxisPlacement.hxx>
#endif
#ifndef _ShapeSchema_PGeom2d_Curve_HeaderFile
#include <ShapeSchema_PGeom2d_Curve.hxx>
#endif
#ifndef _ShapeSchema_PGeom2d_Line_HeaderFile
#include <ShapeSchema_PGeom2d_Line.hxx>
#endif
#ifndef _ShapeSchema_PGeom2d_Conic_HeaderFile
#include <ShapeSchema_PGeom2d_Conic.hxx>
#endif
#ifndef _ShapeSchema_PGeom2d_Circle_HeaderFile
#include <ShapeSchema_PGeom2d_Circle.hxx>
#endif
#ifndef _ShapeSchema_PGeom2d_Ellipse_HeaderFile
#include <ShapeSchema_PGeom2d_Ellipse.hxx>
#endif
#ifndef _ShapeSchema_PGeom2d_Hyperbola_HeaderFile
#include <ShapeSchema_PGeom2d_Hyperbola.hxx>
#endif
#ifndef _ShapeSchema_PGeom2d_Parabola_HeaderFile
#include <ShapeSchema_PGeom2d_Parabola.hxx>
#endif
#ifndef _ShapeSchema_PGeom2d_BoundedCurve_HeaderFile
#include <ShapeSchema_PGeom2d_BoundedCurve.hxx>
#endif
#ifndef _ShapeSchema_PGeom2d_BezierCurve_HeaderFile
#include <ShapeSchema_PGeom2d_BezierCurve.hxx>
#endif
#ifndef _ShapeSchema_PGeom2d_BSplineCurve_HeaderFile
#include <ShapeSchema_PGeom2d_BSplineCurve.hxx>
#endif
#ifndef _ShapeSchema_PGeom2d_TrimmedCurve_HeaderFile
#include <ShapeSchema_PGeom2d_TrimmedCurve.hxx>
#endif
#ifndef _ShapeSchema_PGeom2d_OffsetCurve_HeaderFile
#include <ShapeSchema_PGeom2d_OffsetCurve.hxx>
#endif
#ifndef _ShapeSchema_PGeom_Transformation_HeaderFile
#include <ShapeSchema_PGeom_Transformation.hxx>
#endif
#ifndef _ShapeSchema_PGeom_Geometry_HeaderFile
#include <ShapeSchema_PGeom_Geometry.hxx>
#endif
#ifndef _ShapeSchema_PGeom_Point_HeaderFile
#include <ShapeSchema_PGeom_Point.hxx>
#endif
#ifndef _ShapeSchema_PGeom_CartesianPoint_HeaderFile
#include <ShapeSchema_PGeom_CartesianPoint.hxx>
#endif
#ifndef _ShapeSchema_PGeom_Vector_HeaderFile
#include <ShapeSchema_PGeom_Vector.hxx>
#endif
#ifndef _ShapeSchema_PGeom_Direction_HeaderFile
#include <ShapeSchema_PGeom_Direction.hxx>
#endif
#ifndef _ShapeSchema_PGeom_VectorWithMagnitude_HeaderFile
#include <ShapeSchema_PGeom_VectorWithMagnitude.hxx>
#endif
#ifndef _ShapeSchema_PGeom_AxisPlacement_HeaderFile
#include <ShapeSchema_PGeom_AxisPlacement.hxx>
#endif
#ifndef _ShapeSchema_PGeom_Axis1Placement_HeaderFile
#include <ShapeSchema_PGeom_Axis1Placement.hxx>
#endif
#ifndef _ShapeSchema_PGeom_Axis2Placement_HeaderFile
#include <ShapeSchema_PGeom_Axis2Placement.hxx>
#endif
#ifndef _ShapeSchema_PGeom_Curve_HeaderFile
#include <ShapeSchema_PGeom_Curve.hxx>
#endif
#ifndef _ShapeSchema_PGeom_Line_HeaderFile
#include <ShapeSchema_PGeom_Line.hxx>
#endif
#ifndef _ShapeSchema_PGeom_Conic_HeaderFile
#include <ShapeSchema_PGeom_Conic.hxx>
#endif
#ifndef _ShapeSchema_PGeom_Circle_HeaderFile
#include <ShapeSchema_PGeom_Circle.hxx>
#endif
#ifndef _ShapeSchema_PGeom_Ellipse_HeaderFile
#include <ShapeSchema_PGeom_Ellipse.hxx>
#endif
#ifndef _ShapeSchema_PGeom_Hyperbola_HeaderFile
#include <ShapeSchema_PGeom_Hyperbola.hxx>
#endif
#ifndef _ShapeSchema_PGeom_Parabola_HeaderFile
#include <ShapeSchema_PGeom_Parabola.hxx>
#endif
#ifndef _ShapeSchema_PGeom_BoundedCurve_HeaderFile
#include <ShapeSchema_PGeom_BoundedCurve.hxx>
#endif
#ifndef _ShapeSchema_PGeom_BezierCurve_HeaderFile
#include <ShapeSchema_PGeom_BezierCurve.hxx>
#endif
#ifndef _ShapeSchema_PGeom_BSplineCurve_HeaderFile
#include <ShapeSchema_PGeom_BSplineCurve.hxx>
#endif
#ifndef _ShapeSchema_PGeom_TrimmedCurve_HeaderFile
#include <ShapeSchema_PGeom_TrimmedCurve.hxx>
#endif
#ifndef _ShapeSchema_PGeom_OffsetCurve_HeaderFile
#include <ShapeSchema_PGeom_OffsetCurve.hxx>
#endif
#ifndef _ShapeSchema_PGeom_Surface_HeaderFile
#include <ShapeSchema_PGeom_Surface.hxx>
#endif
#ifndef _ShapeSchema_PGeom_ElementarySurface_HeaderFile
#include <ShapeSchema_PGeom_ElementarySurface.hxx>
#endif
#ifndef _ShapeSchema_PGeom_Plane_HeaderFile
#include <ShapeSchema_PGeom_Plane.hxx>
#endif
#ifndef _ShapeSchema_PGeom_ConicalSurface_HeaderFile
#include <ShapeSchema_PGeom_ConicalSurface.hxx>
#endif
#ifndef _ShapeSchema_PGeom_CylindricalSurface_HeaderFile
#include <ShapeSchema_PGeom_CylindricalSurface.hxx>
#endif
#ifndef _ShapeSchema_PGeom_SphericalSurface_HeaderFile
#include <ShapeSchema_PGeom_SphericalSurface.hxx>
#endif
#ifndef _ShapeSchema_PGeom_ToroidalSurface_HeaderFile
#include <ShapeSchema_PGeom_ToroidalSurface.hxx>
#endif
#ifndef _ShapeSchema_PGeom_SweptSurface_HeaderFile
#include <ShapeSchema_PGeom_SweptSurface.hxx>
#endif
#ifndef _ShapeSchema_PGeom_SurfaceOfLinearExtrusion_HeaderFile
#include <ShapeSchema_PGeom_SurfaceOfLinearExtrusion.hxx>
#endif
#ifndef _ShapeSchema_PGeom_SurfaceOfRevolution_HeaderFile
#include <ShapeSchema_PGeom_SurfaceOfRevolution.hxx>
#endif
#ifndef _ShapeSchema_PGeom_BoundedSurface_HeaderFile
#include <ShapeSchema_PGeom_BoundedSurface.hxx>
#endif
#ifndef _ShapeSchema_PGeom_BezierSurface_HeaderFile
#include <ShapeSchema_PGeom_BezierSurface.hxx>
#endif
#ifndef _ShapeSchema_PGeom_BSplineSurface_HeaderFile
#include <ShapeSchema_PGeom_BSplineSurface.hxx>
#endif
#ifndef _ShapeSchema_PGeom_RectangularTrimmedSurface_HeaderFile
#include <ShapeSchema_PGeom_RectangularTrimmedSurface.hxx>
#endif
#ifndef _ShapeSchema_PGeom_OffsetSurface_HeaderFile
#include <ShapeSchema_PGeom_OffsetSurface.hxx>
#endif
#ifndef _ShapeSchema_PPoly_Triangulation_HeaderFile
#include <ShapeSchema_PPoly_Triangulation.hxx>
#endif
#ifndef _ShapeSchema_PPoly_Polygon3D_HeaderFile
#include <ShapeSchema_PPoly_Polygon3D.hxx>
#endif
#ifndef _ShapeSchema_PPoly_Polygon2D_HeaderFile
#include <ShapeSchema_PPoly_Polygon2D.hxx>
#endif
#ifndef _ShapeSchema_PPoly_PolygonOnTriangulation_HeaderFile
#include <ShapeSchema_PPoly_PolygonOnTriangulation.hxx>
#endif
#ifndef _ShapeSchema_PPoly_HArray1OfTriangle_HeaderFile
#include <ShapeSchema_PPoly_HArray1OfTriangle.hxx>
#endif
#ifndef _ShapeSchema_PTopoDS_HShape_HeaderFile
#include <ShapeSchema_PTopoDS_HShape.hxx>
#endif
#ifndef _ShapeSchema_PTopoDS_TShape_HeaderFile
#include <ShapeSchema_PTopoDS_TShape.hxx>
#endif
#ifndef _ShapeSchema_PTopoDS_TVertex_HeaderFile
#include <ShapeSchema_PTopoDS_TVertex.hxx>
#endif
#ifndef _ShapeSchema_PTopoDS_Vertex_HeaderFile
#include <ShapeSchema_PTopoDS_Vertex.hxx>
#endif
#ifndef _ShapeSchema_PTopoDS_TEdge_HeaderFile
#include <ShapeSchema_PTopoDS_TEdge.hxx>
#endif
#ifndef _ShapeSchema_PTopoDS_Edge_HeaderFile
#include <ShapeSchema_PTopoDS_Edge.hxx>
#endif
#ifndef _ShapeSchema_PTopoDS_TWire_HeaderFile
#include <ShapeSchema_PTopoDS_TWire.hxx>
#endif
#ifndef _ShapeSchema_PTopoDS_Wire_HeaderFile
#include <ShapeSchema_PTopoDS_Wire.hxx>
#endif
#ifndef _ShapeSchema_PTopoDS_TFace_HeaderFile
#include <ShapeSchema_PTopoDS_TFace.hxx>
#endif
#ifndef _ShapeSchema_PTopoDS_Face_HeaderFile
#include <ShapeSchema_PTopoDS_Face.hxx>
#endif
#ifndef _ShapeSchema_PTopoDS_TShell_HeaderFile
#include <ShapeSchema_PTopoDS_TShell.hxx>
#endif
#ifndef _ShapeSchema_PTopoDS_Shell_HeaderFile
#include <ShapeSchema_PTopoDS_Shell.hxx>
#endif
#ifndef _ShapeSchema_PTopoDS_TSolid_HeaderFile
#include <ShapeSchema_PTopoDS_TSolid.hxx>
#endif
#ifndef _ShapeSchema_PTopoDS_Solid_HeaderFile
#include <ShapeSchema_PTopoDS_Solid.hxx>
#endif
#ifndef _ShapeSchema_PTopoDS_TCompSolid_HeaderFile
#include <ShapeSchema_PTopoDS_TCompSolid.hxx>
#endif
#ifndef _ShapeSchema_PTopoDS_CompSolid_HeaderFile
#include <ShapeSchema_PTopoDS_CompSolid.hxx>
#endif
#ifndef _ShapeSchema_PTopoDS_TCompound_HeaderFile
#include <ShapeSchema_PTopoDS_TCompound.hxx>
#endif
#ifndef _ShapeSchema_PTopoDS_Compound_HeaderFile
#include <ShapeSchema_PTopoDS_Compound.hxx>
#endif
#ifndef _ShapeSchema_PTopoDS_HArray1OfHShape_HeaderFile
#include <ShapeSchema_PTopoDS_HArray1OfHShape.hxx>
#endif
#ifndef _ShapeSchema_PTopoDS_TShape1_HeaderFile
#include <ShapeSchema_PTopoDS_TShape1.hxx>
#endif
#ifndef _ShapeSchema_PTopoDS_TVertex1_HeaderFile
#include <ShapeSchema_PTopoDS_TVertex1.hxx>
#endif
#ifndef _ShapeSchema_PTopoDS_TEdge1_HeaderFile
#include <ShapeSchema_PTopoDS_TEdge1.hxx>
#endif
#ifndef _ShapeSchema_PTopoDS_TWire1_HeaderFile
#include <ShapeSchema_PTopoDS_TWire1.hxx>
#endif
#ifndef _ShapeSchema_PTopoDS_TFace1_HeaderFile
#include <ShapeSchema_PTopoDS_TFace1.hxx>
#endif
#ifndef _ShapeSchema_PTopoDS_TShell1_HeaderFile
#include <ShapeSchema_PTopoDS_TShell1.hxx>
#endif
#ifndef _ShapeSchema_PTopoDS_TSolid1_HeaderFile
#include <ShapeSchema_PTopoDS_TSolid1.hxx>
#endif
#ifndef _ShapeSchema_PTopoDS_TCompSolid1_HeaderFile
#include <ShapeSchema_PTopoDS_TCompSolid1.hxx>
#endif
#ifndef _ShapeSchema_PTopoDS_TCompound1_HeaderFile
#include <ShapeSchema_PTopoDS_TCompound1.hxx>
#endif
#ifndef _ShapeSchema_PTopoDS_HArray1OfShape1_HeaderFile
#include <ShapeSchema_PTopoDS_HArray1OfShape1.hxx>
#endif
#ifndef _ShapeSchema_PBRep_CurveRepresentation_HeaderFile
#include <ShapeSchema_PBRep_CurveRepresentation.hxx>
#endif
#ifndef _ShapeSchema_PBRep_GCurve_HeaderFile
#include <ShapeSchema_PBRep_GCurve.hxx>
#endif
#ifndef _ShapeSchema_PBRep_Curve3D_HeaderFile
#include <ShapeSchema_PBRep_Curve3D.hxx>
#endif
#ifndef _ShapeSchema_PBRep_CurveOnSurface_HeaderFile
#include <ShapeSchema_PBRep_CurveOnSurface.hxx>
#endif
#ifndef _ShapeSchema_PBRep_CurveOnClosedSurface_HeaderFile
#include <ShapeSchema_PBRep_CurveOnClosedSurface.hxx>
#endif
#ifndef _ShapeSchema_PBRep_Polygon3D_HeaderFile
#include <ShapeSchema_PBRep_Polygon3D.hxx>
#endif
#ifndef _ShapeSchema_PBRep_PolygonOnTriangulation_HeaderFile
#include <ShapeSchema_PBRep_PolygonOnTriangulation.hxx>
#endif
#ifndef _ShapeSchema_PBRep_PolygonOnClosedTriangulation_HeaderFile
#include <ShapeSchema_PBRep_PolygonOnClosedTriangulation.hxx>
#endif
#ifndef _ShapeSchema_PBRep_PolygonOnSurface_HeaderFile
#include <ShapeSchema_PBRep_PolygonOnSurface.hxx>
#endif
#ifndef _ShapeSchema_PBRep_PolygonOnClosedSurface_HeaderFile
#include <ShapeSchema_PBRep_PolygonOnClosedSurface.hxx>
#endif
#ifndef _ShapeSchema_PBRep_CurveOn2Surfaces_HeaderFile
#include <ShapeSchema_PBRep_CurveOn2Surfaces.hxx>
#endif
#ifndef _ShapeSchema_PBRep_PointRepresentation_HeaderFile
#include <ShapeSchema_PBRep_PointRepresentation.hxx>
#endif
#ifndef _ShapeSchema_PBRep_PointOnCurve_HeaderFile
#include <ShapeSchema_PBRep_PointOnCurve.hxx>
#endif
#ifndef _ShapeSchema_PBRep_PointsOnSurface_HeaderFile
#include <ShapeSchema_PBRep_PointsOnSurface.hxx>
#endif
#ifndef _ShapeSchema_PBRep_PointOnCurveOnSurface_HeaderFile
#include <ShapeSchema_PBRep_PointOnCurveOnSurface.hxx>
#endif
#ifndef _ShapeSchema_PBRep_PointOnSurface_HeaderFile
#include <ShapeSchema_PBRep_PointOnSurface.hxx>
#endif
#ifndef _ShapeSchema_PBRep_TFace_HeaderFile
#include <ShapeSchema_PBRep_TFace.hxx>
#endif
#ifndef _ShapeSchema_PBRep_TEdge_HeaderFile
#include <ShapeSchema_PBRep_TEdge.hxx>
#endif
#ifndef _ShapeSchema_PBRep_TVertex_HeaderFile
#include <ShapeSchema_PBRep_TVertex.hxx>
#endif
#ifndef _ShapeSchema_PBRep_TFace1_HeaderFile
#include <ShapeSchema_PBRep_TFace1.hxx>
#endif
#ifndef _ShapeSchema_PBRep_TEdge1_HeaderFile
#include <ShapeSchema_PBRep_TEdge1.hxx>
#endif
#ifndef _ShapeSchema_PBRep_TVertex1_HeaderFile
#include <ShapeSchema_PBRep_TVertex1.hxx>
#endif
#ifndef _ShapeSchema_PCDMShape_Document_HeaderFile
#include <ShapeSchema_PCDMShape_Document.hxx>
#endif
#ifndef _ShapeSchema_Standard_Persistent_HeaderFile
#include <ShapeSchema_Standard_Persistent.hxx>
#endif
#ifndef _ShapeSchema_PCollection_HAsciiString_HeaderFile
#include <ShapeSchema_PCollection_HAsciiString.hxx>
#endif
#ifndef _ShapeSchema_PMMgt_PManaged_HeaderFile
#include <ShapeSchema_PMMgt_PManaged.hxx>
#endif
#ifndef _ShapeSchema_PColStd_HArray1OfReal_HeaderFile
#include <ShapeSchema_PColStd_HArray1OfReal.hxx>
#endif
#ifndef _ShapeSchema_PColStd_HArray1OfInteger_HeaderFile
#include <ShapeSchema_PColStd_HArray1OfInteger.hxx>
#endif
#ifndef _ShapeSchema_PColStd_HArray2OfReal_HeaderFile
#include <ShapeSchema_PColStd_HArray2OfReal.hxx>
#endif
#ifndef _ShapeSchema_PCDM_Document_HeaderFile
#include <ShapeSchema_PCDM_Document.hxx>
#endif
#ifndef _ShapeSchema_PCollection_HExtendedString_HeaderFile
#include <ShapeSchema_PCollection_HExtendedString.hxx>
#endif

// avoid warnings on 'extern "C"' functions returning C++ classes
#ifdef _MSC_VER
#pragma warning(disable:4190)
#endif

IMPLEMENT_STANDARD_HANDLE(ShapeSchema,Storage_Schema)
IMPLEMENT_STANDARD_RTTIEXT(ShapeSchema,Storage_Schema)

Storage_BEGIN_ADD_TYPES(ShapeSchema)
Storage_ADD_TYPES(ShapeSchema,ObjMgt_ExternShareable,ShapeSchema_ObjMgt_ExternShareable)
Storage_ADD_TYPES(ShapeSchema,ObjMgt_ExternRef,ShapeSchema_ObjMgt_ExternRef)
Storage_ADD_TYPES(ShapeSchema,ObjMgt_PSeqOfExtRef,ShapeSchema_ObjMgt_PSeqOfExtRef)
Storage_ADD_TYPES(ShapeSchema,ObjMgt_SeqNodeOfPSeqOfExtRef,ShapeSchema_ObjMgt_SeqNodeOfPSeqOfExtRef)
Storage_ADD_TYPES(ShapeSchema,PTopLoc_Datum3D,ShapeSchema_PTopLoc_Datum3D)
Storage_ADD_TYPES(ShapeSchema,PTopLoc_ItemLocation,ShapeSchema_PTopLoc_ItemLocation)
Storage_ADD_TYPES(ShapeSchema,PColgp_HArray1OfCirc2d,ShapeSchema_PColgp_HArray1OfCirc2d)
Storage_ADD_TYPES(ShapeSchema,PColgp_HArray1OfDir2d,ShapeSchema_PColgp_HArray1OfDir2d)
Storage_ADD_TYPES(ShapeSchema,PColgp_HArray1OfLin2d,ShapeSchema_PColgp_HArray1OfLin2d)
Storage_ADD_TYPES(ShapeSchema,PColgp_HArray1OfPnt2d,ShapeSchema_PColgp_HArray1OfPnt2d)
Storage_ADD_TYPES(ShapeSchema,PColgp_HArray1OfVec2d,ShapeSchema_PColgp_HArray1OfVec2d)
Storage_ADD_TYPES(ShapeSchema,PColgp_HArray1OfXY,ShapeSchema_PColgp_HArray1OfXY)
Storage_ADD_TYPES(ShapeSchema,PColgp_HArray1OfDir,ShapeSchema_PColgp_HArray1OfDir)
Storage_ADD_TYPES(ShapeSchema,PColgp_HArray1OfPnt,ShapeSchema_PColgp_HArray1OfPnt)
Storage_ADD_TYPES(ShapeSchema,PColgp_HArray1OfVec,ShapeSchema_PColgp_HArray1OfVec)
Storage_ADD_TYPES(ShapeSchema,PColgp_HArray1OfXYZ,ShapeSchema_PColgp_HArray1OfXYZ)
Storage_ADD_TYPES(ShapeSchema,PColgp_HArray2OfCirc2d,ShapeSchema_PColgp_HArray2OfCirc2d)
Storage_ADD_TYPES(ShapeSchema,PColgp_HArray2OfDir2d,ShapeSchema_PColgp_HArray2OfDir2d)
Storage_ADD_TYPES(ShapeSchema,PColgp_HArray2OfLin2d,ShapeSchema_PColgp_HArray2OfLin2d)
Storage_ADD_TYPES(ShapeSchema,PColgp_HArray2OfPnt2d,ShapeSchema_PColgp_HArray2OfPnt2d)
Storage_ADD_TYPES(ShapeSchema,PColgp_HArray2OfVec2d,ShapeSchema_PColgp_HArray2OfVec2d)
Storage_ADD_TYPES(ShapeSchema,PColgp_HArray2OfXY,ShapeSchema_PColgp_HArray2OfXY)
Storage_ADD_TYPES(ShapeSchema,PColgp_HArray2OfDir,ShapeSchema_PColgp_HArray2OfDir)
Storage_ADD_TYPES(ShapeSchema,PColgp_HArray2OfPnt,ShapeSchema_PColgp_HArray2OfPnt)
Storage_ADD_TYPES(ShapeSchema,PColgp_HArray2OfVec,ShapeSchema_PColgp_HArray2OfVec)
Storage_ADD_TYPES(ShapeSchema,PColgp_HArray2OfXYZ,ShapeSchema_PColgp_HArray2OfXYZ)
Storage_ADD_TYPES(ShapeSchema,PColgp_HSequenceOfDir,ShapeSchema_PColgp_HSequenceOfDir)
Storage_ADD_TYPES(ShapeSchema,PColgp_SeqNodeOfHSequenceOfDir,ShapeSchema_PColgp_SeqNodeOfHSequenceOfDir)
Storage_ADD_TYPES(ShapeSchema,PColgp_HSequenceOfPnt,ShapeSchema_PColgp_HSequenceOfPnt)
Storage_ADD_TYPES(ShapeSchema,PColgp_SeqNodeOfHSequenceOfPnt,ShapeSchema_PColgp_SeqNodeOfHSequenceOfPnt)
Storage_ADD_TYPES(ShapeSchema,PColgp_HSequenceOfVec,ShapeSchema_PColgp_HSequenceOfVec)
Storage_ADD_TYPES(ShapeSchema,PColgp_SeqNodeOfHSequenceOfVec,ShapeSchema_PColgp_SeqNodeOfHSequenceOfVec)
Storage_ADD_TYPES(ShapeSchema,PColgp_HSequenceOfXYZ,ShapeSchema_PColgp_HSequenceOfXYZ)
Storage_ADD_TYPES(ShapeSchema,PColgp_SeqNodeOfHSequenceOfXYZ,ShapeSchema_PColgp_SeqNodeOfHSequenceOfXYZ)
Storage_ADD_TYPES(ShapeSchema,PGeom2d_Transformation,ShapeSchema_PGeom2d_Transformation)
Storage_ADD_TYPES(ShapeSchema,PGeom2d_Geometry,ShapeSchema_PGeom2d_Geometry)
Storage_ADD_TYPES(ShapeSchema,PGeom2d_Point,ShapeSchema_PGeom2d_Point)
Storage_ADD_TYPES(ShapeSchema,PGeom2d_CartesianPoint,ShapeSchema_PGeom2d_CartesianPoint)
Storage_ADD_TYPES(ShapeSchema,PGeom2d_Vector,ShapeSchema_PGeom2d_Vector)
Storage_ADD_TYPES(ShapeSchema,PGeom2d_Direction,ShapeSchema_PGeom2d_Direction)
Storage_ADD_TYPES(ShapeSchema,PGeom2d_VectorWithMagnitude,ShapeSchema_PGeom2d_VectorWithMagnitude)
Storage_ADD_TYPES(ShapeSchema,PGeom2d_AxisPlacement,ShapeSchema_PGeom2d_AxisPlacement)
Storage_ADD_TYPES(ShapeSchema,PGeom2d_Curve,ShapeSchema_PGeom2d_Curve)
Storage_ADD_TYPES(ShapeSchema,PGeom2d_Line,ShapeSchema_PGeom2d_Line)
Storage_ADD_TYPES(ShapeSchema,PGeom2d_Conic,ShapeSchema_PGeom2d_Conic)
Storage_ADD_TYPES(ShapeSchema,PGeom2d_Circle,ShapeSchema_PGeom2d_Circle)
Storage_ADD_TYPES(ShapeSchema,PGeom2d_Ellipse,ShapeSchema_PGeom2d_Ellipse)
Storage_ADD_TYPES(ShapeSchema,PGeom2d_Hyperbola,ShapeSchema_PGeom2d_Hyperbola)
Storage_ADD_TYPES(ShapeSchema,PGeom2d_Parabola,ShapeSchema_PGeom2d_Parabola)
Storage_ADD_TYPES(ShapeSchema,PGeom2d_BoundedCurve,ShapeSchema_PGeom2d_BoundedCurve)
Storage_ADD_TYPES(ShapeSchema,PGeom2d_BezierCurve,ShapeSchema_PGeom2d_BezierCurve)
Storage_ADD_TYPES(ShapeSchema,PGeom2d_BSplineCurve,ShapeSchema_PGeom2d_BSplineCurve)
Storage_ADD_TYPES(ShapeSchema,PGeom2d_TrimmedCurve,ShapeSchema_PGeom2d_TrimmedCurve)
Storage_ADD_TYPES(ShapeSchema,PGeom2d_OffsetCurve,ShapeSchema_PGeom2d_OffsetCurve)
Storage_ADD_TYPES(ShapeSchema,PGeom_Transformation,ShapeSchema_PGeom_Transformation)
Storage_ADD_TYPES(ShapeSchema,PGeom_Geometry,ShapeSchema_PGeom_Geometry)
Storage_ADD_TYPES(ShapeSchema,PGeom_Point,ShapeSchema_PGeom_Point)
Storage_ADD_TYPES(ShapeSchema,PGeom_CartesianPoint,ShapeSchema_PGeom_CartesianPoint)
Storage_ADD_TYPES(ShapeSchema,PGeom_Vector,ShapeSchema_PGeom_Vector)
Storage_ADD_TYPES(ShapeSchema,PGeom_Direction,ShapeSchema_PGeom_Direction)
Storage_ADD_TYPES(ShapeSchema,PGeom_VectorWithMagnitude,ShapeSchema_PGeom_VectorWithMagnitude)
Storage_ADD_TYPES(ShapeSchema,PGeom_AxisPlacement,ShapeSchema_PGeom_AxisPlacement)
Storage_ADD_TYPES(ShapeSchema,PGeom_Axis1Placement,ShapeSchema_PGeom_Axis1Placement)
Storage_ADD_TYPES(ShapeSchema,PGeom_Axis2Placement,ShapeSchema_PGeom_Axis2Placement)
Storage_ADD_TYPES(ShapeSchema,PGeom_Curve,ShapeSchema_PGeom_Curve)
Storage_ADD_TYPES(ShapeSchema,PGeom_Line,ShapeSchema_PGeom_Line)
Storage_ADD_TYPES(ShapeSchema,PGeom_Conic,ShapeSchema_PGeom_Conic)
Storage_ADD_TYPES(ShapeSchema,PGeom_Circle,ShapeSchema_PGeom_Circle)
Storage_ADD_TYPES(ShapeSchema,PGeom_Ellipse,ShapeSchema_PGeom_Ellipse)
Storage_ADD_TYPES(ShapeSchema,PGeom_Hyperbola,ShapeSchema_PGeom_Hyperbola)
Storage_ADD_TYPES(ShapeSchema,PGeom_Parabola,ShapeSchema_PGeom_Parabola)
Storage_ADD_TYPES(ShapeSchema,PGeom_BoundedCurve,ShapeSchema_PGeom_BoundedCurve)
Storage_ADD_TYPES(ShapeSchema,PGeom_BezierCurve,ShapeSchema_PGeom_BezierCurve)
Storage_ADD_TYPES(ShapeSchema,PGeom_BSplineCurve,ShapeSchema_PGeom_BSplineCurve)
Storage_ADD_TYPES(ShapeSchema,PGeom_TrimmedCurve,ShapeSchema_PGeom_TrimmedCurve)
Storage_ADD_TYPES(ShapeSchema,PGeom_OffsetCurve,ShapeSchema_PGeom_OffsetCurve)
Storage_ADD_TYPES(ShapeSchema,PGeom_Surface,ShapeSchema_PGeom_Surface)
Storage_ADD_TYPES(ShapeSchema,PGeom_ElementarySurface,ShapeSchema_PGeom_ElementarySurface)
Storage_ADD_TYPES(ShapeSchema,PGeom_Plane,ShapeSchema_PGeom_Plane)
Storage_ADD_TYPES(ShapeSchema,PGeom_ConicalSurface,ShapeSchema_PGeom_ConicalSurface)
Storage_ADD_TYPES(ShapeSchema,PGeom_CylindricalSurface,ShapeSchema_PGeom_CylindricalSurface)
Storage_ADD_TYPES(ShapeSchema,PGeom_SphericalSurface,ShapeSchema_PGeom_SphericalSurface)
Storage_ADD_TYPES(ShapeSchema,PGeom_ToroidalSurface,ShapeSchema_PGeom_ToroidalSurface)
Storage_ADD_TYPES(ShapeSchema,PGeom_SweptSurface,ShapeSchema_PGeom_SweptSurface)
Storage_ADD_TYPES(ShapeSchema,PGeom_SurfaceOfLinearExtrusion,ShapeSchema_PGeom_SurfaceOfLinearExtrusion)
Storage_ADD_TYPES(ShapeSchema,PGeom_SurfaceOfRevolution,ShapeSchema_PGeom_SurfaceOfRevolution)
Storage_ADD_TYPES(ShapeSchema,PGeom_BoundedSurface,ShapeSchema_PGeom_BoundedSurface)
Storage_ADD_TYPES(ShapeSchema,PGeom_BezierSurface,ShapeSchema_PGeom_BezierSurface)
Storage_ADD_TYPES(ShapeSchema,PGeom_BSplineSurface,ShapeSchema_PGeom_BSplineSurface)
Storage_ADD_TYPES(ShapeSchema,PGeom_RectangularTrimmedSurface,ShapeSchema_PGeom_RectangularTrimmedSurface)
Storage_ADD_TYPES(ShapeSchema,PGeom_OffsetSurface,ShapeSchema_PGeom_OffsetSurface)
Storage_ADD_TYPES(ShapeSchema,PPoly_Triangulation,ShapeSchema_PPoly_Triangulation)
Storage_ADD_TYPES(ShapeSchema,PPoly_Polygon3D,ShapeSchema_PPoly_Polygon3D)
Storage_ADD_TYPES(ShapeSchema,PPoly_Polygon2D,ShapeSchema_PPoly_Polygon2D)
Storage_ADD_TYPES(ShapeSchema,PPoly_PolygonOnTriangulation,ShapeSchema_PPoly_PolygonOnTriangulation)
Storage_ADD_TYPES(ShapeSchema,PPoly_HArray1OfTriangle,ShapeSchema_PPoly_HArray1OfTriangle)
Storage_ADD_TYPES(ShapeSchema,PTopoDS_HShape,ShapeSchema_PTopoDS_HShape)
Storage_ADD_TYPES(ShapeSchema,PTopoDS_TShape,ShapeSchema_PTopoDS_TShape)
Storage_ADD_TYPES(ShapeSchema,PTopoDS_TVertex,ShapeSchema_PTopoDS_TVertex)
Storage_ADD_TYPES(ShapeSchema,PTopoDS_Vertex,ShapeSchema_PTopoDS_Vertex)
Storage_ADD_TYPES(ShapeSchema,PTopoDS_TEdge,ShapeSchema_PTopoDS_TEdge)
Storage_ADD_TYPES(ShapeSchema,PTopoDS_Edge,ShapeSchema_PTopoDS_Edge)
Storage_ADD_TYPES(ShapeSchema,PTopoDS_TWire,ShapeSchema_PTopoDS_TWire)
Storage_ADD_TYPES(ShapeSchema,PTopoDS_Wire,ShapeSchema_PTopoDS_Wire)
Storage_ADD_TYPES(ShapeSchema,PTopoDS_TFace,ShapeSchema_PTopoDS_TFace)
Storage_ADD_TYPES(ShapeSchema,PTopoDS_Face,ShapeSchema_PTopoDS_Face)
Storage_ADD_TYPES(ShapeSchema,PTopoDS_TShell,ShapeSchema_PTopoDS_TShell)
Storage_ADD_TYPES(ShapeSchema,PTopoDS_Shell,ShapeSchema_PTopoDS_Shell)
Storage_ADD_TYPES(ShapeSchema,PTopoDS_TSolid,ShapeSchema_PTopoDS_TSolid)
Storage_ADD_TYPES(ShapeSchema,PTopoDS_Solid,ShapeSchema_PTopoDS_Solid)
Storage_ADD_TYPES(ShapeSchema,PTopoDS_TCompSolid,ShapeSchema_PTopoDS_TCompSolid)
Storage_ADD_TYPES(ShapeSchema,PTopoDS_CompSolid,ShapeSchema_PTopoDS_CompSolid)
Storage_ADD_TYPES(ShapeSchema,PTopoDS_TCompound,ShapeSchema_PTopoDS_TCompound)
Storage_ADD_TYPES(ShapeSchema,PTopoDS_Compound,ShapeSchema_PTopoDS_Compound)
Storage_ADD_TYPES(ShapeSchema,PTopoDS_HArray1OfHShape,ShapeSchema_PTopoDS_HArray1OfHShape)
Storage_ADD_TYPES(ShapeSchema,PTopoDS_TShape1,ShapeSchema_PTopoDS_TShape1)
Storage_ADD_TYPES(ShapeSchema,PTopoDS_TVertex1,ShapeSchema_PTopoDS_TVertex1)
Storage_ADD_TYPES(ShapeSchema,PTopoDS_TEdge1,ShapeSchema_PTopoDS_TEdge1)
Storage_ADD_TYPES(ShapeSchema,PTopoDS_TWire1,ShapeSchema_PTopoDS_TWire1)
Storage_ADD_TYPES(ShapeSchema,PTopoDS_TFace1,ShapeSchema_PTopoDS_TFace1)
Storage_ADD_TYPES(ShapeSchema,PTopoDS_TShell1,ShapeSchema_PTopoDS_TShell1)
Storage_ADD_TYPES(ShapeSchema,PTopoDS_TSolid1,ShapeSchema_PTopoDS_TSolid1)
Storage_ADD_TYPES(ShapeSchema,PTopoDS_TCompSolid1,ShapeSchema_PTopoDS_TCompSolid1)
Storage_ADD_TYPES(ShapeSchema,PTopoDS_TCompound1,ShapeSchema_PTopoDS_TCompound1)
Storage_ADD_TYPES(ShapeSchema,PTopoDS_HArray1OfShape1,ShapeSchema_PTopoDS_HArray1OfShape1)
Storage_ADD_TYPES(ShapeSchema,PBRep_CurveRepresentation,ShapeSchema_PBRep_CurveRepresentation)
Storage_ADD_TYPES(ShapeSchema,PBRep_GCurve,ShapeSchema_PBRep_GCurve)
Storage_ADD_TYPES(ShapeSchema,PBRep_Curve3D,ShapeSchema_PBRep_Curve3D)
Storage_ADD_TYPES(ShapeSchema,PBRep_CurveOnSurface,ShapeSchema_PBRep_CurveOnSurface)
Storage_ADD_TYPES(ShapeSchema,PBRep_CurveOnClosedSurface,ShapeSchema_PBRep_CurveOnClosedSurface)
Storage_ADD_TYPES(ShapeSchema,PBRep_Polygon3D,ShapeSchema_PBRep_Polygon3D)
Storage_ADD_TYPES(ShapeSchema,PBRep_PolygonOnTriangulation,ShapeSchema_PBRep_PolygonOnTriangulation)
Storage_ADD_TYPES(ShapeSchema,PBRep_PolygonOnClosedTriangulation,ShapeSchema_PBRep_PolygonOnClosedTriangulation)
Storage_ADD_TYPES(ShapeSchema,PBRep_PolygonOnSurface,ShapeSchema_PBRep_PolygonOnSurface)
Storage_ADD_TYPES(ShapeSchema,PBRep_PolygonOnClosedSurface,ShapeSchema_PBRep_PolygonOnClosedSurface)
Storage_ADD_TYPES(ShapeSchema,PBRep_CurveOn2Surfaces,ShapeSchema_PBRep_CurveOn2Surfaces)
Storage_ADD_TYPES(ShapeSchema,PBRep_PointRepresentation,ShapeSchema_PBRep_PointRepresentation)
Storage_ADD_TYPES(ShapeSchema,PBRep_PointOnCurve,ShapeSchema_PBRep_PointOnCurve)
Storage_ADD_TYPES(ShapeSchema,PBRep_PointsOnSurface,ShapeSchema_PBRep_PointsOnSurface)
Storage_ADD_TYPES(ShapeSchema,PBRep_PointOnCurveOnSurface,ShapeSchema_PBRep_PointOnCurveOnSurface)
Storage_ADD_TYPES(ShapeSchema,PBRep_PointOnSurface,ShapeSchema_PBRep_PointOnSurface)
Storage_ADD_TYPES(ShapeSchema,PBRep_TFace,ShapeSchema_PBRep_TFace)
Storage_ADD_TYPES(ShapeSchema,PBRep_TEdge,ShapeSchema_PBRep_TEdge)
Storage_ADD_TYPES(ShapeSchema,PBRep_TVertex,ShapeSchema_PBRep_TVertex)
Storage_ADD_TYPES(ShapeSchema,PBRep_TFace1,ShapeSchema_PBRep_TFace1)
Storage_ADD_TYPES(ShapeSchema,PBRep_TEdge1,ShapeSchema_PBRep_TEdge1)
Storage_ADD_TYPES(ShapeSchema,PBRep_TVertex1,ShapeSchema_PBRep_TVertex1)
Storage_ADD_TYPES(ShapeSchema,PCDMShape_Document,ShapeSchema_PCDMShape_Document)
Storage_ADD_TYPES(ShapeSchema,Standard_Persistent,ShapeSchema_Standard_Persistent)
Storage_ADD_TYPES(ShapeSchema,PCollection_HAsciiString,ShapeSchema_PCollection_HAsciiString)
Storage_ADD_TYPES(ShapeSchema,PMMgt_PManaged,ShapeSchema_PMMgt_PManaged)
Storage_ADD_TYPES(ShapeSchema,PColStd_HArray1OfReal,ShapeSchema_PColStd_HArray1OfReal)
Storage_ADD_TYPES(ShapeSchema,PColStd_HArray1OfInteger,ShapeSchema_PColStd_HArray1OfInteger)
Storage_ADD_TYPES(ShapeSchema,PColStd_HArray2OfReal,ShapeSchema_PColStd_HArray2OfReal)
Storage_ADD_TYPES(ShapeSchema,PCDM_Document,ShapeSchema_PCDM_Document)
Storage_ADD_TYPES(ShapeSchema,PCollection_HExtendedString,ShapeSchema_PCollection_HExtendedString)
Storage_END_ADD_TYPES(ShapeSchema)

Storage_BEGIN_READ_SELECTION(ShapeSchema)
Storage_READ_SELECTION(ShapeSchema,ObjMgt_ExternRef,ShapeSchema_ObjMgt_ExternRef)
Storage_READ_SELECTION(ShapeSchema,ObjMgt_PSeqOfExtRef,ShapeSchema_ObjMgt_PSeqOfExtRef)
Storage_READ_SELECTION(ShapeSchema,ObjMgt_SeqNodeOfPSeqOfExtRef,ShapeSchema_ObjMgt_SeqNodeOfPSeqOfExtRef)
Storage_READ_SELECTION(ShapeSchema,PTopLoc_Datum3D,ShapeSchema_PTopLoc_Datum3D)
Storage_READ_SELECTION(ShapeSchema,PTopLoc_ItemLocation,ShapeSchema_PTopLoc_ItemLocation)
Storage_READ_SELECTION(ShapeSchema,PColgp_HArray1OfCirc2d,ShapeSchema_PColgp_HArray1OfCirc2d)
Storage_READ_SELECTION(ShapeSchema,PColgp_HArray1OfDir2d,ShapeSchema_PColgp_HArray1OfDir2d)
Storage_READ_SELECTION(ShapeSchema,PColgp_HArray1OfLin2d,ShapeSchema_PColgp_HArray1OfLin2d)
Storage_READ_SELECTION(ShapeSchema,PColgp_HArray1OfPnt2d,ShapeSchema_PColgp_HArray1OfPnt2d)
Storage_READ_SELECTION(ShapeSchema,PColgp_HArray1OfVec2d,ShapeSchema_PColgp_HArray1OfVec2d)
Storage_READ_SELECTION(ShapeSchema,PColgp_HArray1OfXY,ShapeSchema_PColgp_HArray1OfXY)
Storage_READ_SELECTION(ShapeSchema,PColgp_HArray1OfDir,ShapeSchema_PColgp_HArray1OfDir)
Storage_READ_SELECTION(ShapeSchema,PColgp_HArray1OfPnt,ShapeSchema_PColgp_HArray1OfPnt)
Storage_READ_SELECTION(ShapeSchema,PColgp_HArray1OfVec,ShapeSchema_PColgp_HArray1OfVec)
Storage_READ_SELECTION(ShapeSchema,PColgp_HArray1OfXYZ,ShapeSchema_PColgp_HArray1OfXYZ)
Storage_READ_SELECTION(ShapeSchema,PColgp_HArray2OfCirc2d,ShapeSchema_PColgp_HArray2OfCirc2d)
Storage_READ_SELECTION(ShapeSchema,PColgp_HArray2OfDir2d,ShapeSchema_PColgp_HArray2OfDir2d)
Storage_READ_SELECTION(ShapeSchema,PColgp_HArray2OfLin2d,ShapeSchema_PColgp_HArray2OfLin2d)
Storage_READ_SELECTION(ShapeSchema,PColgp_HArray2OfPnt2d,ShapeSchema_PColgp_HArray2OfPnt2d)
Storage_READ_SELECTION(ShapeSchema,PColgp_HArray2OfVec2d,ShapeSchema_PColgp_HArray2OfVec2d)
Storage_READ_SELECTION(ShapeSchema,PColgp_HArray2OfXY,ShapeSchema_PColgp_HArray2OfXY)
Storage_READ_SELECTION(ShapeSchema,PColgp_HArray2OfDir,ShapeSchema_PColgp_HArray2OfDir)
Storage_READ_SELECTION(ShapeSchema,PColgp_HArray2OfPnt,ShapeSchema_PColgp_HArray2OfPnt)
Storage_READ_SELECTION(ShapeSchema,PColgp_HArray2OfVec,ShapeSchema_PColgp_HArray2OfVec)
Storage_READ_SELECTION(ShapeSchema,PColgp_HArray2OfXYZ,ShapeSchema_PColgp_HArray2OfXYZ)
Storage_READ_SELECTION(ShapeSchema,PColgp_HSequenceOfDir,ShapeSchema_PColgp_HSequenceOfDir)
Storage_READ_SELECTION(ShapeSchema,PColgp_SeqNodeOfHSequenceOfDir,ShapeSchema_PColgp_SeqNodeOfHSequenceOfDir)
Storage_READ_SELECTION(ShapeSchema,PColgp_HSequenceOfPnt,ShapeSchema_PColgp_HSequenceOfPnt)
Storage_READ_SELECTION(ShapeSchema,PColgp_SeqNodeOfHSequenceOfPnt,ShapeSchema_PColgp_SeqNodeOfHSequenceOfPnt)
Storage_READ_SELECTION(ShapeSchema,PColgp_HSequenceOfVec,ShapeSchema_PColgp_HSequenceOfVec)
Storage_READ_SELECTION(ShapeSchema,PColgp_SeqNodeOfHSequenceOfVec,ShapeSchema_PColgp_SeqNodeOfHSequenceOfVec)
Storage_READ_SELECTION(ShapeSchema,PColgp_HSequenceOfXYZ,ShapeSchema_PColgp_HSequenceOfXYZ)
Storage_READ_SELECTION(ShapeSchema,PColgp_SeqNodeOfHSequenceOfXYZ,ShapeSchema_PColgp_SeqNodeOfHSequenceOfXYZ)
Storage_READ_SELECTION(ShapeSchema,PGeom2d_Transformation,ShapeSchema_PGeom2d_Transformation)
Storage_READ_SELECTION(ShapeSchema,PGeom2d_CartesianPoint,ShapeSchema_PGeom2d_CartesianPoint)
Storage_READ_SELECTION(ShapeSchema,PGeom2d_Direction,ShapeSchema_PGeom2d_Direction)
Storage_READ_SELECTION(ShapeSchema,PGeom2d_VectorWithMagnitude,ShapeSchema_PGeom2d_VectorWithMagnitude)
Storage_READ_SELECTION(ShapeSchema,PGeom2d_AxisPlacement,ShapeSchema_PGeom2d_AxisPlacement)
Storage_READ_SELECTION(ShapeSchema,PGeom2d_Line,ShapeSchema_PGeom2d_Line)
Storage_READ_SELECTION(ShapeSchema,PGeom2d_Circle,ShapeSchema_PGeom2d_Circle)
Storage_READ_SELECTION(ShapeSchema,PGeom2d_Ellipse,ShapeSchema_PGeom2d_Ellipse)
Storage_READ_SELECTION(ShapeSchema,PGeom2d_Hyperbola,ShapeSchema_PGeom2d_Hyperbola)
Storage_READ_SELECTION(ShapeSchema,PGeom2d_Parabola,ShapeSchema_PGeom2d_Parabola)
Storage_READ_SELECTION(ShapeSchema,PGeom2d_BezierCurve,ShapeSchema_PGeom2d_BezierCurve)
Storage_READ_SELECTION(ShapeSchema,PGeom2d_BSplineCurve,ShapeSchema_PGeom2d_BSplineCurve)
Storage_READ_SELECTION(ShapeSchema,PGeom2d_TrimmedCurve,ShapeSchema_PGeom2d_TrimmedCurve)
Storage_READ_SELECTION(ShapeSchema,PGeom2d_OffsetCurve,ShapeSchema_PGeom2d_OffsetCurve)
Storage_READ_SELECTION(ShapeSchema,PGeom_Transformation,ShapeSchema_PGeom_Transformation)
Storage_READ_SELECTION(ShapeSchema,PGeom_CartesianPoint,ShapeSchema_PGeom_CartesianPoint)
Storage_READ_SELECTION(ShapeSchema,PGeom_Direction,ShapeSchema_PGeom_Direction)
Storage_READ_SELECTION(ShapeSchema,PGeom_VectorWithMagnitude,ShapeSchema_PGeom_VectorWithMagnitude)
Storage_READ_SELECTION(ShapeSchema,PGeom_Axis1Placement,ShapeSchema_PGeom_Axis1Placement)
Storage_READ_SELECTION(ShapeSchema,PGeom_Axis2Placement,ShapeSchema_PGeom_Axis2Placement)
Storage_READ_SELECTION(ShapeSchema,PGeom_Line,ShapeSchema_PGeom_Line)
Storage_READ_SELECTION(ShapeSchema,PGeom_Circle,ShapeSchema_PGeom_Circle)
Storage_READ_SELECTION(ShapeSchema,PGeom_Ellipse,ShapeSchema_PGeom_Ellipse)
Storage_READ_SELECTION(ShapeSchema,PGeom_Hyperbola,ShapeSchema_PGeom_Hyperbola)
Storage_READ_SELECTION(ShapeSchema,PGeom_Parabola,ShapeSchema_PGeom_Parabola)
Storage_READ_SELECTION(ShapeSchema,PGeom_BezierCurve,ShapeSchema_PGeom_BezierCurve)
Storage_READ_SELECTION(ShapeSchema,PGeom_BSplineCurve,ShapeSchema_PGeom_BSplineCurve)
Storage_READ_SELECTION(ShapeSchema,PGeom_TrimmedCurve,ShapeSchema_PGeom_TrimmedCurve)
Storage_READ_SELECTION(ShapeSchema,PGeom_OffsetCurve,ShapeSchema_PGeom_OffsetCurve)
Storage_READ_SELECTION(ShapeSchema,PGeom_Plane,ShapeSchema_PGeom_Plane)
Storage_READ_SELECTION(ShapeSchema,PGeom_ConicalSurface,ShapeSchema_PGeom_ConicalSurface)
Storage_READ_SELECTION(ShapeSchema,PGeom_CylindricalSurface,ShapeSchema_PGeom_CylindricalSurface)
Storage_READ_SELECTION(ShapeSchema,PGeom_SphericalSurface,ShapeSchema_PGeom_SphericalSurface)
Storage_READ_SELECTION(ShapeSchema,PGeom_ToroidalSurface,ShapeSchema_PGeom_ToroidalSurface)
Storage_READ_SELECTION(ShapeSchema,PGeom_SurfaceOfLinearExtrusion,ShapeSchema_PGeom_SurfaceOfLinearExtrusion)
Storage_READ_SELECTION(ShapeSchema,PGeom_SurfaceOfRevolution,ShapeSchema_PGeom_SurfaceOfRevolution)
Storage_READ_SELECTION(ShapeSchema,PGeom_BezierSurface,ShapeSchema_PGeom_BezierSurface)
Storage_READ_SELECTION(ShapeSchema,PGeom_BSplineSurface,ShapeSchema_PGeom_BSplineSurface)
Storage_READ_SELECTION(ShapeSchema,PGeom_RectangularTrimmedSurface,ShapeSchema_PGeom_RectangularTrimmedSurface)
Storage_READ_SELECTION(ShapeSchema,PGeom_OffsetSurface,ShapeSchema_PGeom_OffsetSurface)
Storage_READ_SELECTION(ShapeSchema,PPoly_Triangulation,ShapeSchema_PPoly_Triangulation)
Storage_READ_SELECTION(ShapeSchema,PPoly_Polygon3D,ShapeSchema_PPoly_Polygon3D)
Storage_READ_SELECTION(ShapeSchema,PPoly_Polygon2D,ShapeSchema_PPoly_Polygon2D)
Storage_READ_SELECTION(ShapeSchema,PPoly_PolygonOnTriangulation,ShapeSchema_PPoly_PolygonOnTriangulation)
Storage_READ_SELECTION(ShapeSchema,PPoly_HArray1OfTriangle,ShapeSchema_PPoly_HArray1OfTriangle)
Storage_READ_SELECTION(ShapeSchema,PTopoDS_HShape,ShapeSchema_PTopoDS_HShape)
Storage_READ_SELECTION(ShapeSchema,PTopoDS_Vertex,ShapeSchema_PTopoDS_Vertex)
Storage_READ_SELECTION(ShapeSchema,PTopoDS_Edge,ShapeSchema_PTopoDS_Edge)
Storage_READ_SELECTION(ShapeSchema,PTopoDS_TWire,ShapeSchema_PTopoDS_TWire)
Storage_READ_SELECTION(ShapeSchema,PTopoDS_Wire,ShapeSchema_PTopoDS_Wire)
Storage_READ_SELECTION(ShapeSchema,PTopoDS_TFace,ShapeSchema_PTopoDS_TFace)
Storage_READ_SELECTION(ShapeSchema,PTopoDS_Face,ShapeSchema_PTopoDS_Face)
Storage_READ_SELECTION(ShapeSchema,PTopoDS_TShell,ShapeSchema_PTopoDS_TShell)
Storage_READ_SELECTION(ShapeSchema,PTopoDS_Shell,ShapeSchema_PTopoDS_Shell)
Storage_READ_SELECTION(ShapeSchema,PTopoDS_TSolid,ShapeSchema_PTopoDS_TSolid)
Storage_READ_SELECTION(ShapeSchema,PTopoDS_Solid,ShapeSchema_PTopoDS_Solid)
Storage_READ_SELECTION(ShapeSchema,PTopoDS_TCompSolid,ShapeSchema_PTopoDS_TCompSolid)
Storage_READ_SELECTION(ShapeSchema,PTopoDS_CompSolid,ShapeSchema_PTopoDS_CompSolid)
Storage_READ_SELECTION(ShapeSchema,PTopoDS_TCompound,ShapeSchema_PTopoDS_TCompound)
Storage_READ_SELECTION(ShapeSchema,PTopoDS_Compound,ShapeSchema_PTopoDS_Compound)
Storage_READ_SELECTION(ShapeSchema,PTopoDS_HArray1OfHShape,ShapeSchema_PTopoDS_HArray1OfHShape)
Storage_READ_SELECTION(ShapeSchema,PTopoDS_TWire1,ShapeSchema_PTopoDS_TWire1)
Storage_READ_SELECTION(ShapeSchema,PTopoDS_TFace1,ShapeSchema_PTopoDS_TFace1)
Storage_READ_SELECTION(ShapeSchema,PTopoDS_TShell1,ShapeSchema_PTopoDS_TShell1)
Storage_READ_SELECTION(ShapeSchema,PTopoDS_TSolid1,ShapeSchema_PTopoDS_TSolid1)
Storage_READ_SELECTION(ShapeSchema,PTopoDS_TCompSolid1,ShapeSchema_PTopoDS_TCompSolid1)
Storage_READ_SELECTION(ShapeSchema,PTopoDS_TCompound1,ShapeSchema_PTopoDS_TCompound1)
Storage_READ_SELECTION(ShapeSchema,PTopoDS_HArray1OfShape1,ShapeSchema_PTopoDS_HArray1OfShape1)
Storage_READ_SELECTION(ShapeSchema,PBRep_Curve3D,ShapeSchema_PBRep_Curve3D)
Storage_READ_SELECTION(ShapeSchema,PBRep_CurveOnSurface,ShapeSchema_PBRep_CurveOnSurface)
Storage_READ_SELECTION(ShapeSchema,PBRep_CurveOnClosedSurface,ShapeSchema_PBRep_CurveOnClosedSurface)
Storage_READ_SELECTION(ShapeSchema,PBRep_Polygon3D,ShapeSchema_PBRep_Polygon3D)
Storage_READ_SELECTION(ShapeSchema,PBRep_PolygonOnTriangulation,ShapeSchema_PBRep_PolygonOnTriangulation)
Storage_READ_SELECTION(ShapeSchema,PBRep_PolygonOnClosedTriangulation,ShapeSchema_PBRep_PolygonOnClosedTriangulation)
Storage_READ_SELECTION(ShapeSchema,PBRep_PolygonOnSurface,ShapeSchema_PBRep_PolygonOnSurface)
Storage_READ_SELECTION(ShapeSchema,PBRep_PolygonOnClosedSurface,ShapeSchema_PBRep_PolygonOnClosedSurface)
Storage_READ_SELECTION(ShapeSchema,PBRep_CurveOn2Surfaces,ShapeSchema_PBRep_CurveOn2Surfaces)
Storage_READ_SELECTION(ShapeSchema,PBRep_PointOnCurve,ShapeSchema_PBRep_PointOnCurve)
Storage_READ_SELECTION(ShapeSchema,PBRep_PointOnCurveOnSurface,ShapeSchema_PBRep_PointOnCurveOnSurface)
Storage_READ_SELECTION(ShapeSchema,PBRep_PointOnSurface,ShapeSchema_PBRep_PointOnSurface)
Storage_READ_SELECTION(ShapeSchema,PBRep_TFace,ShapeSchema_PBRep_TFace)
Storage_READ_SELECTION(ShapeSchema,PBRep_TEdge,ShapeSchema_PBRep_TEdge)
Storage_READ_SELECTION(ShapeSchema,PBRep_TVertex,ShapeSchema_PBRep_TVertex)
Storage_READ_SELECTION(ShapeSchema,PBRep_TFace1,ShapeSchema_PBRep_TFace1)
Storage_READ_SELECTION(ShapeSchema,PBRep_TEdge1,ShapeSchema_PBRep_TEdge1)
Storage_READ_SELECTION(ShapeSchema,PBRep_TVertex1,ShapeSchema_PBRep_TVertex1)
Storage_READ_SELECTION(ShapeSchema,PCDMShape_Document,ShapeSchema_PCDMShape_Document)
Storage_READ_SELECTION(ShapeSchema,PCollection_HAsciiString,ShapeSchema_PCollection_HAsciiString)
Storage_READ_SELECTION(ShapeSchema,PColStd_HArray1OfReal,ShapeSchema_PColStd_HArray1OfReal)
Storage_READ_SELECTION(ShapeSchema,PColStd_HArray1OfInteger,ShapeSchema_PColStd_HArray1OfInteger)
Storage_READ_SELECTION(ShapeSchema,PColStd_HArray2OfReal,ShapeSchema_PColStd_HArray2OfReal)
Storage_READ_SELECTION(ShapeSchema,PCollection_HExtendedString,ShapeSchema_PCollection_HExtendedString)
Storage_END_READ_SELECTION(ShapeSchema)

Storage_BEGIN_SCHEMA_TYPES(ShapeSchema)
Storage_SCHEMA_TYPES(ObjMgt_ExternShareable)
Storage_SCHEMA_TYPES(ObjMgt_ExternRef)
Storage_SCHEMA_TYPES(ObjMgt_PSeqOfExtRef)
Storage_SCHEMA_TYPES(ObjMgt_SeqNodeOfPSeqOfExtRef)
Storage_SCHEMA_TYPES(PTopLoc_Datum3D)
Storage_SCHEMA_TYPES(PTopLoc_ItemLocation)
Storage_SCHEMA_TYPES(PColgp_HArray1OfCirc2d)
Storage_SCHEMA_TYPES(PColgp_HArray1OfDir2d)
Storage_SCHEMA_TYPES(PColgp_HArray1OfLin2d)
Storage_SCHEMA_TYPES(PColgp_HArray1OfPnt2d)
Storage_SCHEMA_TYPES(PColgp_HArray1OfVec2d)
Storage_SCHEMA_TYPES(PColgp_HArray1OfXY)
Storage_SCHEMA_TYPES(PColgp_HArray1OfDir)
Storage_SCHEMA_TYPES(PColgp_HArray1OfPnt)
Storage_SCHEMA_TYPES(PColgp_HArray1OfVec)
Storage_SCHEMA_TYPES(PColgp_HArray1OfXYZ)
Storage_SCHEMA_TYPES(PColgp_HArray2OfCirc2d)
Storage_SCHEMA_TYPES(PColgp_HArray2OfDir2d)
Storage_SCHEMA_TYPES(PColgp_HArray2OfLin2d)
Storage_SCHEMA_TYPES(PColgp_HArray2OfPnt2d)
Storage_SCHEMA_TYPES(PColgp_HArray2OfVec2d)
Storage_SCHEMA_TYPES(PColgp_HArray2OfXY)
Storage_SCHEMA_TYPES(PColgp_HArray2OfDir)
Storage_SCHEMA_TYPES(PColgp_HArray2OfPnt)
Storage_SCHEMA_TYPES(PColgp_HArray2OfVec)
Storage_SCHEMA_TYPES(PColgp_HArray2OfXYZ)
Storage_SCHEMA_TYPES(PColgp_HSequenceOfDir)
Storage_SCHEMA_TYPES(PColgp_SeqNodeOfHSequenceOfDir)
Storage_SCHEMA_TYPES(PColgp_HSequenceOfPnt)
Storage_SCHEMA_TYPES(PColgp_SeqNodeOfHSequenceOfPnt)
Storage_SCHEMA_TYPES(PColgp_HSequenceOfVec)
Storage_SCHEMA_TYPES(PColgp_SeqNodeOfHSequenceOfVec)
Storage_SCHEMA_TYPES(PColgp_HSequenceOfXYZ)
Storage_SCHEMA_TYPES(PColgp_SeqNodeOfHSequenceOfXYZ)
Storage_SCHEMA_TYPES(PGeom2d_Transformation)
Storage_SCHEMA_TYPES(PGeom2d_Geometry)
Storage_SCHEMA_TYPES(PGeom2d_Point)
Storage_SCHEMA_TYPES(PGeom2d_CartesianPoint)
Storage_SCHEMA_TYPES(PGeom2d_Vector)
Storage_SCHEMA_TYPES(PGeom2d_Direction)
Storage_SCHEMA_TYPES(PGeom2d_VectorWithMagnitude)
Storage_SCHEMA_TYPES(PGeom2d_AxisPlacement)
Storage_SCHEMA_TYPES(PGeom2d_Curve)
Storage_SCHEMA_TYPES(PGeom2d_Line)
Storage_SCHEMA_TYPES(PGeom2d_Conic)
Storage_SCHEMA_TYPES(PGeom2d_Circle)
Storage_SCHEMA_TYPES(PGeom2d_Ellipse)
Storage_SCHEMA_TYPES(PGeom2d_Hyperbola)
Storage_SCHEMA_TYPES(PGeom2d_Parabola)
Storage_SCHEMA_TYPES(PGeom2d_BoundedCurve)
Storage_SCHEMA_TYPES(PGeom2d_BezierCurve)
Storage_SCHEMA_TYPES(PGeom2d_BSplineCurve)
Storage_SCHEMA_TYPES(PGeom2d_TrimmedCurve)
Storage_SCHEMA_TYPES(PGeom2d_OffsetCurve)
Storage_SCHEMA_TYPES(PGeom_Transformation)
Storage_SCHEMA_TYPES(PGeom_Geometry)
Storage_SCHEMA_TYPES(PGeom_Point)
Storage_SCHEMA_TYPES(PGeom_CartesianPoint)
Storage_SCHEMA_TYPES(PGeom_Vector)
Storage_SCHEMA_TYPES(PGeom_Direction)
Storage_SCHEMA_TYPES(PGeom_VectorWithMagnitude)
Storage_SCHEMA_TYPES(PGeom_AxisPlacement)
Storage_SCHEMA_TYPES(PGeom_Axis1Placement)
Storage_SCHEMA_TYPES(PGeom_Axis2Placement)
Storage_SCHEMA_TYPES(PGeom_Curve)
Storage_SCHEMA_TYPES(PGeom_Line)
Storage_SCHEMA_TYPES(PGeom_Conic)
Storage_SCHEMA_TYPES(PGeom_Circle)
Storage_SCHEMA_TYPES(PGeom_Ellipse)
Storage_SCHEMA_TYPES(PGeom_Hyperbola)
Storage_SCHEMA_TYPES(PGeom_Parabola)
Storage_SCHEMA_TYPES(PGeom_BoundedCurve)
Storage_SCHEMA_TYPES(PGeom_BezierCurve)
Storage_SCHEMA_TYPES(PGeom_BSplineCurve)
Storage_SCHEMA_TYPES(PGeom_TrimmedCurve)
Storage_SCHEMA_TYPES(PGeom_OffsetCurve)
Storage_SCHEMA_TYPES(PGeom_Surface)
Storage_SCHEMA_TYPES(PGeom_ElementarySurface)
Storage_SCHEMA_TYPES(PGeom_Plane)
Storage_SCHEMA_TYPES(PGeom_ConicalSurface)
Storage_SCHEMA_TYPES(PGeom_CylindricalSurface)
Storage_SCHEMA_TYPES(PGeom_SphericalSurface)
Storage_SCHEMA_TYPES(PGeom_ToroidalSurface)
Storage_SCHEMA_TYPES(PGeom_SweptSurface)
Storage_SCHEMA_TYPES(PGeom_SurfaceOfLinearExtrusion)
Storage_SCHEMA_TYPES(PGeom_SurfaceOfRevolution)
Storage_SCHEMA_TYPES(PGeom_BoundedSurface)
Storage_SCHEMA_TYPES(PGeom_BezierSurface)
Storage_SCHEMA_TYPES(PGeom_BSplineSurface)
Storage_SCHEMA_TYPES(PGeom_RectangularTrimmedSurface)
Storage_SCHEMA_TYPES(PGeom_OffsetSurface)
Storage_SCHEMA_TYPES(PPoly_Triangulation)
Storage_SCHEMA_TYPES(PPoly_Polygon3D)
Storage_SCHEMA_TYPES(PPoly_Polygon2D)
Storage_SCHEMA_TYPES(PPoly_PolygonOnTriangulation)
Storage_SCHEMA_TYPES(PPoly_HArray1OfTriangle)
Storage_SCHEMA_TYPES(PTopoDS_HShape)
Storage_SCHEMA_TYPES(PTopoDS_TShape)
Storage_SCHEMA_TYPES(PTopoDS_TVertex)
Storage_SCHEMA_TYPES(PTopoDS_Vertex)
Storage_SCHEMA_TYPES(PTopoDS_TEdge)
Storage_SCHEMA_TYPES(PTopoDS_Edge)
Storage_SCHEMA_TYPES(PTopoDS_TWire)
Storage_SCHEMA_TYPES(PTopoDS_Wire)
Storage_SCHEMA_TYPES(PTopoDS_TFace)
Storage_SCHEMA_TYPES(PTopoDS_Face)
Storage_SCHEMA_TYPES(PTopoDS_TShell)
Storage_SCHEMA_TYPES(PTopoDS_Shell)
Storage_SCHEMA_TYPES(PTopoDS_TSolid)
Storage_SCHEMA_TYPES(PTopoDS_Solid)
Storage_SCHEMA_TYPES(PTopoDS_TCompSolid)
Storage_SCHEMA_TYPES(PTopoDS_CompSolid)
Storage_SCHEMA_TYPES(PTopoDS_TCompound)
Storage_SCHEMA_TYPES(PTopoDS_Compound)
Storage_SCHEMA_TYPES(PTopoDS_HArray1OfHShape)
Storage_SCHEMA_TYPES(PTopoDS_TShape1)
Storage_SCHEMA_TYPES(PTopoDS_TVertex1)
Storage_SCHEMA_TYPES(PTopoDS_TEdge1)
Storage_SCHEMA_TYPES(PTopoDS_TWire1)
Storage_SCHEMA_TYPES(PTopoDS_TFace1)
Storage_SCHEMA_TYPES(PTopoDS_TShell1)
Storage_SCHEMA_TYPES(PTopoDS_TSolid1)
Storage_SCHEMA_TYPES(PTopoDS_TCompSolid1)
Storage_SCHEMA_TYPES(PTopoDS_TCompound1)
Storage_SCHEMA_TYPES(PTopoDS_HArray1OfShape1)
Storage_SCHEMA_TYPES(PBRep_CurveRepresentation)
Storage_SCHEMA_TYPES(PBRep_GCurve)
Storage_SCHEMA_TYPES(PBRep_Curve3D)
Storage_SCHEMA_TYPES(PBRep_CurveOnSurface)
Storage_SCHEMA_TYPES(PBRep_CurveOnClosedSurface)
Storage_SCHEMA_TYPES(PBRep_Polygon3D)
Storage_SCHEMA_TYPES(PBRep_PolygonOnTriangulation)
Storage_SCHEMA_TYPES(PBRep_PolygonOnClosedTriangulation)
Storage_SCHEMA_TYPES(PBRep_PolygonOnSurface)
Storage_SCHEMA_TYPES(PBRep_PolygonOnClosedSurface)
Storage_SCHEMA_TYPES(PBRep_CurveOn2Surfaces)
Storage_SCHEMA_TYPES(PBRep_PointRepresentation)
Storage_SCHEMA_TYPES(PBRep_PointOnCurve)
Storage_SCHEMA_TYPES(PBRep_PointsOnSurface)
Storage_SCHEMA_TYPES(PBRep_PointOnCurveOnSurface)
Storage_SCHEMA_TYPES(PBRep_PointOnSurface)
Storage_SCHEMA_TYPES(PBRep_TFace)
Storage_SCHEMA_TYPES(PBRep_TEdge)
Storage_SCHEMA_TYPES(PBRep_TVertex)
Storage_SCHEMA_TYPES(PBRep_TFace1)
Storage_SCHEMA_TYPES(PBRep_TEdge1)
Storage_SCHEMA_TYPES(PBRep_TVertex1)
Storage_SCHEMA_TYPES(PCDMShape_Document)
Storage_SCHEMA_TYPES(Standard_Persistent)
Storage_SCHEMA_TYPES(PCollection_HAsciiString)
Storage_SCHEMA_TYPES(PMMgt_PManaged)
Storage_SCHEMA_TYPES(PColStd_HArray1OfReal)
Storage_SCHEMA_TYPES(PColStd_HArray1OfInteger)
Storage_SCHEMA_TYPES(PColStd_HArray2OfReal)
Storage_SCHEMA_TYPES(PCDM_Document)
Storage_SCHEMA_TYPES(PCollection_HExtendedString)
Storage_END_SCHEMA_TYPES(ShapeSchema)
