// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <GraphDS_DataMapIteratorOfEntityRoleMap.hxx>

#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _Standard_Transient_HeaderFile
#include <Standard_Transient.hxx>
#endif
#ifndef _TColStd_MapTransientHasher_HeaderFile
#include <TColStd_MapTransientHasher.hxx>
#endif
#ifndef _GraphDS_EntityRoleMap_HeaderFile
#include <GraphDS_EntityRoleMap.hxx>
#endif
#ifndef _GraphDS_DataMapNodeOfEntityRoleMap_HeaderFile
#include <GraphDS_DataMapNodeOfEntityRoleMap.hxx>
#endif
 

#define TheKey Handle_Standard_Transient
#define TheKey_hxx <Standard_Transient.hxx>
#define TheItem GraphDS_EntityRole
#define TheItem_hxx <GraphDS_EntityRole.hxx>
#define Hasher TColStd_MapTransientHasher
#define Hasher_hxx <TColStd_MapTransientHasher.hxx>
#define TCollection_DataMapNode GraphDS_DataMapNodeOfEntityRoleMap
#define TCollection_DataMapNode_hxx <GraphDS_DataMapNodeOfEntityRoleMap.hxx>
#define TCollection_DataMapIterator GraphDS_DataMapIteratorOfEntityRoleMap
#define TCollection_DataMapIterator_hxx <GraphDS_DataMapIteratorOfEntityRoleMap.hxx>
#define Handle_TCollection_DataMapNode Handle_GraphDS_DataMapNodeOfEntityRoleMap
#define TCollection_DataMapNode_Type_() GraphDS_DataMapNodeOfEntityRoleMap_Type_()
#define TCollection_DataMap GraphDS_EntityRoleMap
#define TCollection_DataMap_hxx <GraphDS_EntityRoleMap.hxx>
#include <TCollection_DataMapIterator.gxx>

