// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _StepGeom_BoundaryCurve_HeaderFile
#define _StepGeom_BoundaryCurve_HeaderFile

#ifndef _Standard_HeaderFile
#include <Standard.hxx>
#endif
#ifndef _Standard_DefineHandle_HeaderFile
#include <Standard_DefineHandle.hxx>
#endif
#ifndef _Handle_StepGeom_BoundaryCurve_HeaderFile
#include <Handle_StepGeom_BoundaryCurve.hxx>
#endif

#ifndef _StepGeom_CompositeCurveOnSurface_HeaderFile
#include <StepGeom_CompositeCurveOnSurface.hxx>
#endif



class StepGeom_BoundaryCurve : public StepGeom_CompositeCurveOnSurface {

public:

  //! Returns a BoundaryCurve <br>
  Standard_EXPORT   StepGeom_BoundaryCurve();




  DEFINE_STANDARD_RTTI(StepGeom_BoundaryCurve)

protected:




private: 




};





// other Inline functions and methods (like "C++: function call" methods)


#endif
