// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <TColStd_MapOfInteger.hxx>

#ifndef _Standard_DomainError_HeaderFile
#include <Standard_DomainError.hxx>
#endif
#ifndef _TColStd_MapIntegerHasher_HeaderFile
#include <TColStd_MapIntegerHasher.hxx>
#endif
#ifndef _TColStd_StdMapNodeOfMapOfInteger_HeaderFile
#include <TColStd_StdMapNodeOfMapOfInteger.hxx>
#endif
#ifndef _TColStd_MapIteratorOfMapOfInteger_HeaderFile
#include <TColStd_MapIteratorOfMapOfInteger.hxx>
#endif
 

#define TheKey Standard_Integer
#define TheKey_hxx <Standard_Integer.hxx>
#define Hasher TColStd_MapIntegerHasher
#define Hasher_hxx <TColStd_MapIntegerHasher.hxx>
#define TCollection_StdMapNode TColStd_StdMapNodeOfMapOfInteger
#define TCollection_StdMapNode_hxx <TColStd_StdMapNodeOfMapOfInteger.hxx>
#define TCollection_MapIterator TColStd_MapIteratorOfMapOfInteger
#define TCollection_MapIterator_hxx <TColStd_MapIteratorOfMapOfInteger.hxx>
#define Handle_TCollection_StdMapNode Handle_TColStd_StdMapNodeOfMapOfInteger
#define TCollection_StdMapNode_Type_() TColStd_StdMapNodeOfMapOfInteger_Type_()
#define TCollection_Map TColStd_MapOfInteger
#define TCollection_Map_hxx <TColStd_MapOfInteger.hxx>
#include <TCollection_Map.gxx>

