
MESSAGE(STATUS "Processing ToolKit: ${TOOLKIT} (${TOOLKIT_MODULES})")
SET(TOOLKIT_SOURCE_FILES)
SET(TOOLKIT_HEADER_FILES)
SET(POSSIBLE_INSTALL_HEADERS)
IF(DEFINED TOOLKIT_INCLUDE_DIRECTORIES)
	INCLUDE_DIRECTORIES(${TOOLKIT_INCLUDE_DIRECTORIES})
ENDIF(DEFINED TOOLKIT_INCLUDE_DIRECTORIES)
FOREACH(MODULE ${TOOLKIT_MODULES})
	# add all .cxx/*.c files or each module
	FILE(GLOB source_files
		${${PROJECT_NAME}_SOURCE_DIR}/src/${MODULE}/*.cxx
		${${PROJECT_NAME}_SOURCE_DIR}/src/${MODULE}/*.c
		${${PROJECT_NAME}_SOURCE_DIR}/drv/${MODULE}/*.cxx
		${${PROJECT_NAME}_SOURCE_DIR}/drv/${MODULE}/*.c)
	FILE(GLOB header_files
		${${PROJECT_NAME}_SOURCE_DIR}/inc/Handle_${MODULE}*.hxx
		${${PROJECT_NAME}_SOURCE_DIR}/inc/${MODULE}*.hxx
		${${PROJECT_NAME}_SOURCE_DIR}/inc/Handle_${MODULE}*.h
		${${PROJECT_NAME}_SOURCE_DIR}/inc/${MODULE}*.h
		${${PROJECT_NAME}_SOURCE_DIR}/src/${MODULE}/*.hxx
		${${PROJECT_NAME}_SOURCE_DIR}/src/${MODULE}/*.lxx
		${${PROJECT_NAME}_SOURCE_DIR}/src/${MODULE}/*.gxx
		${${PROJECT_NAME}_SOURCE_DIR}/src/${MODULE}/*.h
		${${PROJECT_NAME}_SOURCE_DIR}/drv/${MODULE}/*.hxx
		${${PROJECT_NAME}_SOURCE_DIR}/drv/${MODULE}/*.ixx
		${${PROJECT_NAME}_SOURCE_DIR}/drv/${MODULE}/*.jxx
		${${PROJECT_NAME}_SOURCE_DIR}/drv/${MODULE}/*.h)
	#MESSAGE(STATUS "${source_files}")
	# Build a list of all header files, with the ultimate aim of
	# forming the public or install headers
	LIST(REMOVE_DUPLICATES header_files)
	FOREACH(module_header_file ${header_files})
		STRING(REGEX MATCH
			"/([a-zA-Z0-9_\\.]+.[hlgij][x]*)$" DUMMY_OUTPUT ${module_header_file} )
		LIST(APPEND POSSIBLE_INSTALL_HEADERS ${CMAKE_MATCH_1})
	ENDFOREACH(module_header_file ${header_files})

	FOREACH(module_source_file ${source_files})
		STRING(REGEX MATCH "${MODULE}/([a-zA-Z0-9_\\.]+.c[x]*)$" DUMMY_OUTPUT ${module_source_file} )
		STRING(REGEX REPLACE "([a-zA-Z0-9_\\.]+)c([x]*)$"
			"\\1h\\2" POSSIBLE_INSTALL_HEADER ${CMAKE_MATCH_1})
		LIST(APPEND POSSIBLE_INSTALL_HEADERS
			${POSSIBLE_INSTALL_HEADER})
	ENDFOREACH(module_source_file ${source_files})

	IF (WIN32)
		# For compilers under Windows a define must be set per file to correctly set the export macro
		SET_SOURCE_FILES_PROPERTIES(${source_files} PROPERTIES COMPILE_FLAGS "-D__${MODULE}_DLL")
	ENDIF(WIN32)

	# append these source files to the list of source files of the toolkit
	SET(TOOLKIT_SOURCE_FILES ${TOOLKIT_SOURCE_FILES} ${source_files}) 
	SET(TOOLKIT_HEADER_FILES ${TOOLKIT_HEADER_FILES} ${header_files}) 
	# required include paths
	INCLUDE_DIRECTORIES(${${PROJECT_NAME}_SOURCE_DIR}/src/${MODULE} ${${PROJECT_NAME}_SOURCE_DIR}/drv/${MODULE})
ENDFOREACH(MODULE ${TOOLKIT_MODULES})
ADD_LIBRARY(${TOOLKIT} ${${PROJECT_NAME}_LIBRARY_TYPE} ${TOOLKIT_SOURCE_FILES})
# TODO Add current toolkit header files into a source group?
# Add target specific locations of *.lxx and *.ixx files
SET_TARGET_PROPERTIES(${TOOLKIT} PROPERTIES
	SOVERSION ${${PROJECT_NAME}_ABI_SOVERSION}
	VERSION ${${PROJECT_NAME}_ABI_VERSION}
)

# Set dependencies for thit ToolKit
IF ( NOT "${TOOLKIT}" STREQUAL "TKernel" )
	LIST(REMOVE_DUPLICATES TOOLKIT_DEPENDS)
ENDIF ( NOT "${TOOLKIT}" STREQUAL "TKernel" )
TARGET_LINK_LIBRARIES(${TOOLKIT} ${TOOLKIT_DEPENDS} ${TOOLKIT_LIBS} ${WIN32_LIBS})

IF(TOOLKIT_DEPENDS)
	ADD_DEPENDENCIES(${TOOLKIT} ${TOOLKIT_DEPENDS})
ENDIF(TOOLKIT_DEPENDS)

###########
# INSTALL #
###########
LIST(REMOVE_DUPLICATES POSSIBLE_INSTALL_HEADERS)
FOREACH(POSSIBLE_INSTALL_HEADER ${POSSIBLE_INSTALL_HEADERS})
	# Test for existence in inc/
	IF(EXISTS ${${PROJECT_NAME}_SOURCE_DIR}/inc/${POSSIBLE_INSTALL_HEADER})
		LIST(APPEND INSTALL_HEADERS ${${PROJECT_NAME}_SOURCE_DIR}/inc/${POSSIBLE_INSTALL_HEADER})
	ENDIF(EXISTS ${${PROJECT_NAME}_SOURCE_DIR}/inc/${POSSIBLE_INSTALL_HEADER})
ENDFOREACH(POSSIBLE_INSTALL_HEADER ${POSSIBLE_INSTALL_HEADERS})
LIST(APPEND INSTALL_HEADERS ${${PROJECT_NAME}_BINARY_DIR}/inc/oce-config.h)
 
INSTALL(FILES ${INSTALL_HEADERS}
	DESTINATION ${${PROJECT_NAME}_INSTALL_INCLUDE_DIR} COMPONENT Development
)

IF(TOOLKIT_IS_PRIVATE)
	SET(TOOLKIT_INSTALL_LIB_DIR ${${PROJECT_NAME}_INSTALL_PACKAGE_LIB_DIR})
ELSE(TOOLKIT_IS_PRIVATE)
	SET(TOOLKIT_INSTALL_LIB_DIR ${${PROJECT_NAME}_INSTALL_LIB_DIR})
	SET_TARGET_PROPERTIES(${TOOLKIT} PROPERTIES INSTALL_RPATH "${${PROJECT_NAME}_INSTALL_LIB_DIR}")
ENDIF(TOOLKIT_IS_PRIVATE)

INSTALL(TARGETS ${TOOLKIT}
	RUNTIME DESTINATION ${TOOLKIT_INSTALL_LIB_DIR} COMPONENT RuntimeLibraries
	LIBRARY DESTINATION ${TOOLKIT_INSTALL_LIB_DIR} COMPONENT RuntimeLibraries
	ARCHIVE DESTINATION ${TOOLKIT_INSTALL_LIB_DIR} COMPONENT Development
)

