# being used toolkits

set(TKernel_DEPS "")
set(TKMath_DEPS "TKernel")
set(TKG2d_DEPS "TKernel;TKMath")
set(TKG3d_DEPS "TKMath;TKernel;TKG2d")
set(TKGeomBase_DEPS "TKernel;TKMath;TKG2d;TKG3d")
set(TKBRep_DEPS "TKMath;TKernel;TKG2d;TKG3d;TKGeomBase")
set(TKGeomAlgo_DEPS "TKernel;TKMath;TKG3d;TKG2d;TKGeomBase;TKBRep")
set(TKTopAlgo_DEPS "TKMath;TKernel;TKG2d;TKG3d;TKGeomBase;TKBRep;TKGeomAlgo")
set(TKPrim_DEPS "TKBRep;TKernel;TKMath;TKG2d;TKGeomBase;TKG3d;TKTopAlgo")
set(TKBO_DEPS "TKBRep;TKTopAlgo;TKMath;TKernel;TKG2d;TKG3d;TKGeomAlgo;TKGeomBase;TKPrim")
set(TKBool_DEPS "TKBRep;TKTopAlgo;TKMath;TKernel;TKPrim;TKG2d;TKG3d;TKShHealing;TKGeomBase;TKGeomAlgo;TKBO")
set(TKHLR_DEPS "TKBRep;TKernel;TKMath;TKGeomBase;TKG2d;TKG3d;TKGeomAlgo;TKTopAlgo")
set(TKFillet_DEPS "TKBRep;TKernel;TKMath;TKGeomBase;TKGeomAlgo;TKG2d;TKTopAlgo;TKG3d;TKBool;TKShHealing")
set(TKOffset_DEPS "TKFillet;TKBRep;TKTopAlgo;TKMath;TKernel;TKGeomBase;TKG2d;TKG3d;TKGeomAlgo;TKShHealing;TKBO;TKPrim;TKBool")
set(TKFeat_DEPS "TKBRep;TKTopAlgo;TKGeomAlgo;TKMath;TKernel;TKGeomBase;TKPrim;TKG2d;TKBO;TKG3d;TKBool")
set(TKMesh_DEPS "TKBRep;TKMath;TKernel;TKG2d;TKG3d;TKGeomBase;TKTopAlgo;TKGeomAlgo")
set(TKXMesh_DEPS "TKBRep;TKMath;TKernel;TKG2d;TKMesh")
set(TKShHealing_DEPS "TKBRep;TKernel;TKMath;TKG2d;TKTopAlgo;TKG3d;TKGeomBase;TKGeomAlgo")
set(TKService_DEPS "TKernel;TKMath;TKBRep;TKShHealing;TKGeomBase;TKGeomAlgo;TKG2d;TKG3d;TKTopAlgo")
set(TKV3d_DEPS "TKBRep;TKMath;TKernel;TKService;TKShHealing;TKTopAlgo;TKG2d;TKG3d;TKGeomBase;TKMesh;TKGeomAlgo;TKHLR")
set(TKOpenGl_DEPS "TKernel;TKService;TKMath;TKV3d")
set(TKMeshVS_DEPS "TKV3d;TKMath;TKService;TKernel;TKG3d;TKG2d")
set(TKNIS_DEPS "TKBRep;TKV3d;TKMath;TKernel;TKService;TKG2d;TKG3d;TKMesh")
set(TKVoxel_DEPS "TKBRep;TKernel;TKV3d;TKMath;TKService;TKGeomBase;TKG2d;TKTopAlgo;TKG3d;TKMesh")
set(TKIVtk_DEPS "TKernel;TKBRep;TKG2d;TKG3d;TKGeomAlgo;TKGeomBase;TKMath;TKMesh;TKService;TKTopAlgo;TKV3d")
set(PTKernel_DEPS "TKernel")
set(TKPShape_DEPS "TKMath;TKernel;TKG2d;TKG3d;PTKernel;TKBRep")
set(TKCDF_DEPS "TKernel")
set(TKLCAF_DEPS "TKCDF;TKernel")
set(TKCAF_DEPS "TKernel;TKGeomBase;TKBRep;TKTopAlgo;TKMath;TKService;TKG2d;TKG3d;TKCDF;TKLCAF;TKV3d;TKBO")
set(TKBinL_DEPS "TKCDF;TKernel;TKLCAF")
set(TKXmlL_DEPS "TKCDF;TKernel;TKMath;TKLCAF")
set(TKShapeSchema_DEPS "TKernel;TKG2d;PTKernel;TKMath;TKCDF;TKPShape")
set(TKPLCAF_DEPS "TKCDF;PTKernel;TKernel;TKLCAF")
set(TKBin_DEPS "TKBRep;TKMath;TKernel;TKG2d;TKG3d;TKCAF;TKCDF;TKLCAF;TKV3d;TKBinL")
set(TKXml_DEPS "TKCDF;TKernel;TKV3d;TKMath;TKBRep;TKG2d;TKGeomBase;TKG3d;TKLCAF;TKCAF;TKXmlL")
set(TKPCAF_DEPS "PTKernel;TKBRep;TKMath;TKernel;TKCDF;TKG2d;TKV3d;TKService;TKG3d;TKPShape;TKCAF;TKLCAF;TKPLCAF")
set(FWOSPlugin_DEPS "TKernel;TKCDF")
set(TKStdLSchema_DEPS "TKCDF;PTKernel;TKernel;TKShapeSchema;TKLCAF;TKPLCAF")
set(TKStdSchema_DEPS "TKCDF;PTKernel;TKPLCAF;TKernel;TKCAF;TKShapeSchema;TKLCAF;TKStdLSchema;TKG3d;TKPShape;TKMath;TKG2d;TKPCAF")
set(TKTObj_DEPS "TKCDF;TKernel;TKMath;TKLCAF")
set(TKBinTObj_DEPS "TKCDF;TKernel;TKTObj;TKMath;TKLCAF;TKBinL")
set(TKXmlTObj_DEPS "TKCDF;TKernel;TKTObj;TKMath;TKLCAF;TKXmlL")
set(TKXSBase_DEPS "TKBRep;TKernel;TKMath;TKG2d;TKG3d;TKTopAlgo;TKGeomBase;TKShHealing")
set(TKSTEPBase_DEPS "TKernel;TKXSBase;TKMath")
set(TKSTEPAttr_DEPS "TKernel;TKXSBase;TKSTEPBase")
set(TKSTEP209_DEPS "TKernel;TKXSBase;TKSTEPBase")
set(TKSTEP_DEPS "TKernel;TKSTEPAttr;TKSTEP209;TKSTEPBase;TKBRep;TKMath;TKG2d;TKShHealing;TKTopAlgo;TKG3d;TKGeomBase;TKGeomAlgo;TKXSBase")
set(TKIGES_DEPS "TKBRep;TKernel;TKMath;TKTopAlgo;TKShHealing;TKG2d;TKG3d;TKGeomBase;TKGeomAlgo;TKPrim;TKBool;TKXSBase")
set(TKXCAF_DEPS "TKBRep;TKernel;TKMath;TKService;TKG2d;TKTopAlgo;TKV3d;TKCDF;TKLCAF;TKG3d;TKCAF")
set(TKXCAFSchema_DEPS "TKPLCAF;TKernel;PTKernel;TKMath;TKPShape;TKCDF;TKShapeSchema;TKLCAF;TKPCAF;TKXCAF;TKStdLSchema;TKStdSchema")
set(TKXDEIGES_DEPS "TKBRep;TKernel;TKMath;TKXSBase;TKCDF;TKLCAF;TKG2d;TKXCAF;TKIGES")
set(TKXDESTEP_DEPS "TKBRep;TKSTEPAttr;TKernel;TKMath;TKXSBase;TKG2d;TKCAF;TKSTEPBase;TKCDF;TKLCAF;TKG3d;TKXCAF;TKSTEP")
set(TKSTL_DEPS "TKernel;TKMath;TKBRep;TKG2d;TKG3d;TKMesh;TKTopAlgo")
set(TKVRML_DEPS "TKBRep;TKTopAlgo;TKMath;TKGeomBase;TKernel;TKPrim;TKG2d;TKG3d;TKMesh;TKHLR;TKService;TKGeomAlgo;TKV3d")
set(TKXmlXCAF_DEPS "TKXmlL;TKBRep;TKCDF;TKMath;TKernel;TKG2d;TKGeomBase;TKCAF;TKG3d;TKLCAF;TKXCAF;TKXml")
set(TKBinXCAF_DEPS "TKBRep;TKXCAF;TKMath;TKernel;TKBinL;TKG2d;TKCAF;TKCDF;TKG3d;TKLCAF;TKBin")
set(TKDraw_DEPS "TKernel;TKG2d;TKGeomBase;TKG3d;TKMath;TKBRep;TKGeomAlgo;TKTopAlgo;TKMesh;TKService;TKHLR")
set(TKTopTest_DEPS "TKBRep;TKGeomAlgo;TKTopAlgo;TKernel;TKMath;TKBO;TKG2d;TKG3d;TKDraw;TKHLR;TKGeomBase;TKMesh;TKService;TKV3d;TKFillet;TKPrim;TKBool;TKOffset;TKFeat;TKShHealing")
set(TKViewerTest_DEPS "TKGeomBase;TKFillet;TKBRep;TKTopAlgo;TKHLR;TKernel;TKMath;TKNIS;TKService;TKShHealing;TKBool;TKPrim;TKGeomAlgo;TKG2d;TKTopTest;TKG3d;TKOffset;TKVoxel;TKMesh;TKV3d;TKDraw;TKOpenGl")
set(TKXSDRAW_DEPS "TKBRep;TKV3d;TKMath;TKNIS;TKernel;TKService;TKXSBase;TKMeshVS;TKG3d;TKViewerTest;TKG2d;TKSTEPBase;TKTopAlgo;TKGeomBase;TKGeomAlgo;TKMesh;TKDraw;TKSTEP;TKIGES;TKSTL;TKVRML")
set(TKDCAF_DEPS "TKGeomBase;TKBRep;TKGeomAlgo;TKernel;TKMath;TKG2d;TKG3d;TKDraw;TKCDF;TKV3d;TKNIS;TKService;TKLCAF;TKFillet;TKTopAlgo;TKPrim;TKBool;TKBO;TKCAF;TKViewerTest")
set(TKXDEDRAW_DEPS "TKCDF;TKBRep;TKXCAF;TKernel;TKIGES;TKV3d;TKMath;TKNIS;TKService;TKXSBase;TKG2d;TKCAF;TKDraw;TKTopAlgo;TKLCAF;TKG3d;TKSTEPBase;TKSTEP;TKMesh;TKXSDRAW;TKXDEIGES;TKXDESTEP;TKDCAF;TKViewerTest")
set(TKTObjDRAW_DEPS "TKernel;TKCDF;TKLCAF;TKTObj;TKMath;TKDraw;TKDCAF")
set(TKQADraw_DEPS "TKBRep;TKNIS;TKMath;TKernel;TKService;TKG2d;TKDraw;PTKernel;TKV3d;TKGeomBase;TKG3d;TKViewerTest;TKCDF;TKDCAF;TKLCAF;TKFillet;TKTopAlgo;TKHLR;TKBool;TKGeomAlgo;TKPrim;TKBO;TKShHealing;TKOffset;TKFeat;TKCAF;TKIGES;TKXSBase;TKMesh;TKXCAF;TKSTEP;TKXDESTEP;TKXSDRAW;TKSTL;TKVoxel;TKShapeSchema;TKPShape")
set(TKIVtkDraw_DEPS "TKernel;TKBRep;TKDraw;TKG2d;TKG3d;TKGeomAlgo;TKGeomBase;TKMath;TKMesh;TKService;TKTopAlgo;TKV3d;TKOpenGl;TKIVtk")
set(DRAWEXE_DEPS "TKDraw;TKMesh;TKTopAlgo;TKHLR;TKGeomAlgo;TKGeomBase;TKG2d;TKBRep;TKMath;TKG3d;TKernel;TKService")


if (BUILD_FoundationClasses)
 LIST(APPEND USED_TOOLKITS TKernel )
 foreach( TK ${TKernel_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKMath )
 foreach( TK ${TKMath_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
endif()

if (BUILD_ModelingData)
 LIST(APPEND USED_TOOLKITS TKG2d )
 foreach( TK ${TKG2d_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKG3d )
 foreach( TK ${TKG3d_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKGeomBase )
 foreach( TK ${TKGeomBase_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKBRep )
 foreach( TK ${TKBRep_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
endif()

if (BUILD_ModelingAlgorithms)
 LIST(APPEND USED_TOOLKITS TKGeomAlgo )
 foreach( TK ${TKGeomAlgo_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKTopAlgo )
 foreach( TK ${TKTopAlgo_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKPrim )
 foreach( TK ${TKPrim_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKBO )
 foreach( TK ${TKBO_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKBool )
 foreach( TK ${TKBool_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKHLR )
 foreach( TK ${TKHLR_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKFillet )
 foreach( TK ${TKFillet_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKOffset )
 foreach( TK ${TKOffset_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKFeat )
 foreach( TK ${TKFeat_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKMesh )
 foreach( TK ${TKMesh_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKXMesh )
 foreach( TK ${TKXMesh_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKShHealing )
 foreach( TK ${TKShHealing_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
endif()

if (BUILD_Visualization)
 LIST(APPEND USED_TOOLKITS TKService )
 foreach( TK ${TKService_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKV3d )
 foreach( TK ${TKV3d_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKOpenGl )
 foreach( TK ${TKOpenGl_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKMeshVS )
 foreach( TK ${TKMeshVS_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKNIS )
 foreach( TK ${TKNIS_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKVoxel )
 foreach( TK ${TKVoxel_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 if (USE_VTK)
   LIST(APPEND USED_TOOLKITS TKIVtk )
   foreach( TK ${TKIVtk_DEPS})
      LIST(APPEND USED_TOOLKITS ${TK} )
   endforeach()
 endif()
endif()

if (BUILD_ApplicationFramework)
 LIST(APPEND USED_TOOLKITS PTKernel )
 foreach( TK ${PTKernel_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKPShape )
 foreach( TK ${TKPShape_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKCDF )
 foreach( TK ${TKCDF_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKLCAF )
 foreach( TK ${TKLCAF_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKCAF )
 foreach( TK ${TKCAF_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKBinL )
 foreach( TK ${TKBinL_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKXmlL )
 foreach( TK ${TKXmlL_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKShapeSchema )
 foreach( TK ${TKShapeSchema_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKPLCAF )
 foreach( TK ${TKPLCAF_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKBin )
 foreach( TK ${TKBin_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKXml )
 foreach( TK ${TKXml_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKPCAF )
 foreach( TK ${TKPCAF_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS FWOSPlugin )
 foreach( TK ${FWOSPlugin_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKStdLSchema )
 foreach( TK ${TKStdLSchema_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKStdSchema )
 foreach( TK ${TKStdSchema_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKTObj )
 foreach( TK ${TKTObj_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKBinTObj )
 foreach( TK ${TKBinTObj_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKXmlTObj )
 foreach( TK ${TKXmlTObj_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
endif()

if (BUILD_DataExchange)
 LIST(APPEND USED_TOOLKITS TKXSBase )
 foreach( TK ${TKXSBase_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKSTEPBase )
 foreach( TK ${TKSTEPBase_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKSTEPAttr )
 foreach( TK ${TKSTEPAttr_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKSTEP209 )
 foreach( TK ${TKSTEP209_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKSTEP )
 foreach( TK ${TKSTEP_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKIGES )
 foreach( TK ${TKIGES_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKXCAF )
 foreach( TK ${TKXCAF_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKXCAFSchema )
 foreach( TK ${TKXCAFSchema_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKXDEIGES )
 foreach( TK ${TKXDEIGES_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKXDESTEP )
 foreach( TK ${TKXDESTEP_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKSTL )
 foreach( TK ${TKSTL_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKVRML )
 foreach( TK ${TKVRML_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKXmlXCAF )
 foreach( TK ${TKXmlXCAF_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKBinXCAF )
 foreach( TK ${TKBinXCAF_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
endif()

if (BUILD_Draw)
 LIST(APPEND USED_TOOLKITS TKDraw )
 foreach( TK ${TKDraw_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKTopTest )
 foreach( TK ${TKTopTest_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKViewerTest )
 foreach( TK ${TKViewerTest_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKXSDRAW )
 foreach( TK ${TKXSDRAW_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKDCAF )
 foreach( TK ${TKDCAF_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKXDEDRAW )
 foreach( TK ${TKXDEDRAW_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKTObjDRAW )
 foreach( TK ${TKTObjDRAW_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 LIST(APPEND USED_TOOLKITS TKQADraw )
 foreach( TK ${TKQADraw_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
 if (USE_VTK)
   LIST(APPEND USED_TOOLKITS TKIVtkDraw )
   foreach( TK ${TKIVtkDraw_DEPS})
      LIST(APPEND USED_TOOLKITS ${TK} )
   endforeach()
 endif()
 LIST(APPEND USED_TOOLKITS DRAWEXE )
 foreach( TK ${DRAWEXE_DEPS})
    LIST(APPEND USED_TOOLKITS ${TK} )
 endforeach()
endif()

list( APPEND USED_TOOLKITS ${BUILD_TOOLKITS})

foreach( TOOLKIT ${USED_TOOLKITS} )
 set(TurnONthe${TOOLKIT} ON)
 foreach( TK ${${TOOLKIT}_DEPS})
   set(TurnONthe${TK} ON)
 endforeach()
endforeach()
