// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <Plate_HArray1OfPinpointConstraint.hxx>

#include <Standard_Type.hxx>

#include <Standard_RangeError.hxx>
#include <Standard_DimensionMismatch.hxx>
#include <Standard_OutOfRange.hxx>
#include <Standard_OutOfMemory.hxx>
#include <Plate_PinpointConstraint.hxx>
#include <Plate_Array1OfPinpointConstraint.hxx>

 


IMPLEMENT_STANDARD_TYPE(Plate_HArray1OfPinpointConstraint)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(Plate_HArray1OfPinpointConstraint)


IMPLEMENT_DOWNCAST(Plate_HArray1OfPinpointConstraint,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(Plate_HArray1OfPinpointConstraint)


#define ItemHArray1 Plate_PinpointConstraint
#define ItemHArray1_hxx <Plate_PinpointConstraint.hxx>
#define TheArray1 Plate_Array1OfPinpointConstraint
#define TheArray1_hxx <Plate_Array1OfPinpointConstraint.hxx>
#define TCollection_HArray1 Plate_HArray1OfPinpointConstraint
#define TCollection_HArray1_hxx <Plate_HArray1OfPinpointConstraint.hxx>
#define Handle_TCollection_HArray1 Handle_Plate_HArray1OfPinpointConstraint
#define TCollection_HArray1_Type_() Plate_HArray1OfPinpointConstraint_Type_()
#include <TCollection_HArray1.gxx>

