// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#ifndef _PlotMgt_PlotterDriverPtr_HeaderFile
#define _PlotMgt_PlotterDriverPtr_HeaderFile

class PlotMgt_PlotterDriver;

typedef PlotMgt_PlotterDriver* PlotMgt_PlotterDriverPtr;

#endif
