// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <Interface_HArray1OfHAsciiString.hxx>

#include <Standard_Type.hxx>

#include <Standard_RangeError.hxx>
#include <Standard_DimensionMismatch.hxx>
#include <Standard_OutOfRange.hxx>
#include <Standard_OutOfMemory.hxx>
#include <TCollection_HAsciiString.hxx>
#include <Interface_Array1OfHAsciiString.hxx>

 


IMPLEMENT_STANDARD_TYPE(Interface_HArray1OfHAsciiString)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(Interface_HArray1OfHAsciiString)


IMPLEMENT_DOWNCAST(Interface_HArray1OfHAsciiString,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(Interface_HArray1OfHAsciiString)


#define ItemHArray1 Handle(TCollection_HAsciiString)
#define ItemHArray1_hxx <TCollection_HAsciiString.hxx>
#define TheArray1 Interface_Array1OfHAsciiString
#define TheArray1_hxx <Interface_Array1OfHAsciiString.hxx>
#define TCollection_HArray1 Interface_HArray1OfHAsciiString
#define TCollection_HArray1_hxx <Interface_HArray1OfHAsciiString.hxx>
#define Handle_TCollection_HArray1 Handle_Interface_HArray1OfHAsciiString
#define TCollection_HArray1_Type_() Interface_HArray1OfHAsciiString_Type_()
#include <TCollection_HArray1.gxx>

