// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <Contap_TheSegmentOfTheSearchOfContour.hxx>

#ifndef _Adaptor2d_HCurve2d_HeaderFile
#include <Adaptor2d_HCurve2d.hxx>
#endif
#ifndef _Standard_DomainError_HeaderFile
#include <Standard_DomainError.hxx>
#endif
#ifndef _Adaptor3d_HVertex_HeaderFile
#include <Adaptor3d_HVertex.hxx>
#endif
#ifndef _Contap_ThePathPointOfTheSearchOfContour_HeaderFile
#include <Contap_ThePathPointOfTheSearchOfContour.hxx>
#endif
 

#define TheVertex Handle_Adaptor3d_HVertex
#define TheVertex_hxx <Adaptor3d_HVertex.hxx>
#define TheArc Handle_Adaptor2d_HCurve2d
#define TheArc_hxx <Adaptor2d_HCurve2d.hxx>
#define ThePathPoint Contap_ThePathPointOfTheSearchOfContour
#define ThePathPoint_hxx <Contap_ThePathPointOfTheSearchOfContour.hxx>
#define IntStart_Segment Contap_TheSegmentOfTheSearchOfContour
#define IntStart_Segment_hxx <Contap_TheSegmentOfTheSearchOfContour.hxx>
#include <IntStart_Segment.gxx>

