// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <GraphTools_ListNodeOfListOfSequenceOfInteger.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _TColStd_SequenceOfInteger_HeaderFile
#include <TColStd_SequenceOfInteger.hxx>
#endif
#ifndef _GraphTools_ListOfSequenceOfInteger_HeaderFile
#include <GraphTools_ListOfSequenceOfInteger.hxx>
#endif
#ifndef _GraphTools_ListIteratorOfListOfSequenceOfInteger_HeaderFile
#include <GraphTools_ListIteratorOfListOfSequenceOfInteger.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(GraphTools_ListNodeOfListOfSequenceOfInteger)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_MapNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(GraphTools_ListNodeOfListOfSequenceOfInteger)


IMPLEMENT_DOWNCAST(GraphTools_ListNodeOfListOfSequenceOfInteger,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(GraphTools_ListNodeOfListOfSequenceOfInteger)


#define Item TColStd_SequenceOfInteger
#define Item_hxx <TColStd_SequenceOfInteger.hxx>
#define TCollection_ListNode GraphTools_ListNodeOfListOfSequenceOfInteger
#define TCollection_ListNode_hxx <GraphTools_ListNodeOfListOfSequenceOfInteger.hxx>
#define TCollection_ListIterator GraphTools_ListIteratorOfListOfSequenceOfInteger
#define TCollection_ListIterator_hxx <GraphTools_ListIteratorOfListOfSequenceOfInteger.hxx>
#define Handle_TCollection_ListNode Handle_GraphTools_ListNodeOfListOfSequenceOfInteger
#define TCollection_ListNode_Type_() GraphTools_ListNodeOfListOfSequenceOfInteger_Type_()
#define TCollection_List GraphTools_ListOfSequenceOfInteger
#define TCollection_List_hxx <GraphTools_ListOfSequenceOfInteger.hxx>
#include <TCollection_ListNode.gxx>

