#pragma once

#include "../TKernel/Precompiled.h"
#include "../TKMath/Precompiled.h"
#include "../TKGeomBase/Precompiled.h"
#include "../TKG2d/Precompiled.h"
#include "../TKG3d/Precompiled.h"
#include "../TKGeomAlgo/Precompiled.h"

#include "Bisector.hxx"
#include "Bisector_Curve.hxx"
#include "Geom2d_TrimmedCurve.hxx"
#include "gp.hxx"
#include "gp_Pnt2d.hxx"
#include "gp_Vec2d.hxx"
#include "gp_Pnt.hxx"
#include "gp_Vec.hxx"

#include "BRepApprox_Approx.hxx"
#include "AppParCurves_Constraint.hxx"
#include "GeomAbs_SurfaceType.hxx"
#include "IntSurf_Quadric.hxx"
#include "gp_Trsf.hxx"
#include "BRepLib.hxx"
#include "BRepBndLib.hxx"
#include "BRepBuilderAPI.hxx"
#include "BRepCheck.hxx"
#include "BRepClass_FaceClassifier.hxx"
#include "BRepClass_FaceExplorer.hxx"
#include "BRepClass_Intersector.hxx"
#include "BRepClass3d_SolidClassifier.hxx"
#include "BRepClass3d_SolidExplorer.hxx"
#include "BRepExtrema_ExtCC.hxx"
#include "BRepExtrema_ExtCF.hxx"
#include "BRepExtrema_ExtFF.hxx"
#include "BRepExtrema_ExtPC.hxx"
#include "BRepExtrema_ExtPF.hxx"
#include "BRepGProp.hxx"
#include "BRepMAT2d_Explorer.hxx"
#include "BRepTopAdaptor_Tool.hxx"
#include "MAT_Graph.hxx"
#include "MAT_Edge.hxx"
#include "MAT_Zone.hxx"
#include "MAT2d_Tool2d.hxx"

