// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <StepAP203_HArray1OfClassifiedItem.hxx>

#include <Standard_Type.hxx>

#include <Standard_RangeError.hxx>
#include <Standard_DimensionMismatch.hxx>
#include <Standard_OutOfRange.hxx>
#include <Standard_OutOfMemory.hxx>
#include <StepAP203_ClassifiedItem.hxx>
#include <StepAP203_Array1OfClassifiedItem.hxx>

 


IMPLEMENT_STANDARD_TYPE(StepAP203_HArray1OfClassifiedItem)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(StepAP203_HArray1OfClassifiedItem)


IMPLEMENT_DOWNCAST(StepAP203_HArray1OfClassifiedItem,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(StepAP203_HArray1OfClassifiedItem)


#define ItemHArray1 StepAP203_ClassifiedItem
#define ItemHArray1_hxx <StepAP203_ClassifiedItem.hxx>
#define TheArray1 StepAP203_Array1OfClassifiedItem
#define TheArray1_hxx <StepAP203_Array1OfClassifiedItem.hxx>
#define TCollection_HArray1 StepAP203_HArray1OfClassifiedItem
#define TCollection_HArray1_hxx <StepAP203_HArray1OfClassifiedItem.hxx>
#define Handle_TCollection_HArray1 Handle_StepAP203_HArray1OfClassifiedItem
#define TCollection_HArray1_Type_() StepAP203_HArray1OfClassifiedItem_Type_()
#include <TCollection_HArray1.gxx>

